Repository InternLM/lmdeploy, pull requests merged in 2023-10, with the labels that each got.

#532 [Fix] Set the default value of `step` being 0
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#487 make IPv6 compatible, safe run for coroutine interrupting
  benchmark/profile_restful_api.py
  docs/en/restful_api.md
  docs/zh_cn/restful_api.md
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#539 Fix typo in `docs/en/pytorch.md`
  docs/en/pytorch.md
Labels: documentation

#517 [bug] fix mismatched shape for decoder output tensor
  src/turbomind/models/llama/LlamaV2.cc
Labels: Bug:P1

#482 support deploy qwen-14b-chat
  README.md
  README_zh-CN.md
  lmdeploy/model.py
  lmdeploy/serve/turbomind/deploy.py
Labels: improvement

#500 [doc] Update benchmark command in w4a16.md
  docs/en/w4a16.md
  docs/zh_cn/w4a16.md
Labels: documentation

#543 Move `tokenizer.py` to the folder of lmdeploy
  benchmark/profile_generation.py
  benchmark/profile_restful_api.py
  benchmark/profile_serving.py
  benchmark/profile_throughput.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/turbomind/deploy.py
  lmdeploy/tokenizer.py
  lmdeploy/turbomind/__init__.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/decode.py
  lmdeploy/turbomind/turbomind.py
  tests/python/test_tokenizer.py
Labels: improvement

#587 update solar chat template
  lmdeploy/model.py
Labels: improvement

#586 Revert "[Docs] Simplify `build.md`"
  docs/en/build.md
  docs/zh_cn/build.md
Labels: Bug:P1, documentation

#591 Fix crash and remove `sys_instruct` from `chat.py` and `client.py`
  benchmark/README.md
  benchmark/profile_generation.py
  lmdeploy/serve/client.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/turbomind/chat.py
Labels: Bug:P0

#602 Add "build from docker" section
  builder/manywheel/entrypoint_build.sh
  docs/en/build.md
  docs/zh_cn/build.md
Labels: documentation

#541 Add more user-friendly CLI
  README.md
  README_zh-CN.md
  docs/en/kv_int8.md
  docs/en/pytorch.md
  docs/en/restful_api.md
  docs/en/serving.md
  docs/en/supported_models/codellama.md
  docs/en/w4a16.md
  docs/zh_cn/kv_int8.md
  docs/zh_cn/restful_api.md
  docs/zh_cn/serving.md
  docs/zh_cn/supported_models/codellama.md
  docs/zh_cn/w4a16.md
  lmdeploy/cli/__init__.py
  lmdeploy/cli/chat.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/lite.py
  lmdeploy/cli/serve.py
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/kv_qparams.py
  lmdeploy/model.py
  lmdeploy/pytorch/chat.py
  lmdeploy/serve/client.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/turbomind/deploy.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/decode.py
  lmdeploy/turbomind/generate_gemm_config.py
  setup.py
  tests/test_lmdeploy/test_cli.py
Labels: enhancement

#467 support inference a batch of prompts
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement
