Repository InternLM/lmdeploy, pull requests merged in 2023-09, with the labels that each got.

#320 add llama_gemm to wheel
  .gitignore
  MANIFEST.in
  examples/cpp/llama/generate_gemm_config.py
  lmdeploy/turbomind/generate_gemm_config.py
  setup.py
  src/turbomind/models/llama/CMakeLists.txt
Labels: improvement

#309 Decode generated token_ids incrementally
  docs/en/restful_api.md
  docs/zh_cn/restful_api.md
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/serve/turbomind/triton_models/postprocessing/1/model.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/tokenizer.py
Labels: improvement

#344 Fix profile_serving hung issue
  benchmark/profile_serving.py
  lmdeploy/serve/turbomind/chatbot.py
Labels: Bug:P1

#367 [Doc] Fix quantization docs link
  README.md
Labels: documentation

#370 [Docs] Simplify `build.md`
  docs/en/build.md
  docs/zh_cn/build.md
Labels: documentation

#372 Update lmdeploy logo
  README.md
  README_zh-CN.md
  resources/lmdeploy-logo.png
  resources/lmdeploy-logo.svg
Labels: documentation

#346 bug-fix: when using stream is False, continuous batching doesn't work
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#377 [Fix] Set max dynamic smem size for decoder MHA to support context length > 8k
  src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_128.cu
Labels: Bug:P1

#378 Support baichuan2-chat chat template
  README.md
  README_zh-CN.md
  lmdeploy/model.py
  lmdeploy/serve/turbomind/deploy.py
  lmdeploy/turbomind/turbomind.py
Labels: enhancement

#359 Support codellama
  README.md
  README_zh-CN.md
  docs/en/supported_models/codellama.md
  docs/zh_cn/supported_models/codellama.md
  lmdeploy/model.py
  lmdeploy/serve/client.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/serve/turbomind/deploy.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/tokenizer.py
  requirements.txt
  src/turbomind/kernels/decoder_masked_multihead_attention.h
  src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.cuh
  src/turbomind/kernels/unfused_attention_kernels.cu
  src/turbomind/kernels/unfused_attention_kernels.h
  src/turbomind/models/llama/LlamaContextAttentionLayer.cc
  src/turbomind/models/llama/LlamaDecoderSelfAttentionLayer.cc
  src/turbomind/models/llama/llama_params.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#400 more general pypi ci
  builder/manywheel/build_wheel.sh
  builder/manywheel/entrypoint_build.sh
Labels: improvement

#412 more general pypi ci
  builder/manywheel/build_wheel.sh
  builder/manywheel/entrypoint_build.sh
Labels: Bug:P1

#411 Fix build.md
  docs/en/build.md
  docs/zh_cn/build.md
Labels: Bug:P1

#415 Fix memory leak
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
Labels: Bug:P1

#407 Reduce gil switching
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
Labels: improvement

#416 Fix token count bug
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#364 Profile token generation with more settings
  benchmark/README.md
  benchmark/profile_generation.py
Labels: improvement

#466 Fix side effect brought by supporting codellama: `sequence_start` is always true when calling `model.get_prompt`
  lmdeploy/turbomind/chat.py
Labels: Bug:P0

#470 Miss meta instruction of internlm-chat model
  lmdeploy/model.py
Labels: Bug:P0

#352 expose stop words and filter eoa
  lmdeploy/model.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/utils.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#488 Fix memory leak
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h
  src/turbomind/triton_backend/transformer_triton_backend.hpp
Labels: Bug:P1
