Repository InternLM/lmdeploy, pull requests merged in 2023-12, with the labels that each got.

#788 Fix early-exit condition in attention kernel
  src/turbomind/kernels/decoder_multihead_attention/decoder_multihead_attention_template.h
Labels: Bug:P0

#787 Fix missed arguments when benchmark static inference performance
  benchmark/profile_generation.py
  benchmark/profile_throughput.py
  docs/en/benchmark/profile_throughput.md
  docs/zh_cn/benchmark/profile_throughput.md
Labels: Bug:P1

#796 fix extra colon in InternLMChat7B template
  lmdeploy/model.py
Labels: Bug:P1

#806 Fix local kv head num
  src/turbomind/models/llama/LlamaV2.cc
Labels: Bug:P0

#794 Report the inference benchmark of models with different size
  benchmark/benchmark_13b.sh
  benchmark/benchmark_20b.sh
  benchmark/benchmark_70b.sh
  benchmark/benchmark_7b.sh
  benchmark/profile_generation.py
  benchmark/profile_restful_api.py
  benchmark/profile_serving.py
  benchmark/profile_throughput.py
  docs/en/benchmark/a100_fp16.md
Labels: improvement

#809 Fix out-of-bound access
  src/turbomind/models/llama/LlamaBatch.cc
Labels: Bug:P0

#812 Simplify block manager
  src/turbomind/models/llama/BlockManager.cc
  src/turbomind/models/llama/BlockManager.h
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/SequenceManager.cc
  src/turbomind/models/llama/SequenceManager.h
Labels: improvement

#818 Set smem size for repetition penalty kernel
  src/turbomind/kernels/sampling_penalty_kernels.cu
Labels: Bug:P1

#813 Disable attention mask when it is not needed
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/unified_decoder.cc
  src/turbomind/models/llama/unified_decoder.h
Labels: improvement

#795 FIFO pipe strategy for api_server
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#820 simplify the header of the benchmark table
  README.md
  README_zh-CN.md
  benchmark/profile_generation.py
  benchmark/profile_restful_api.py
  benchmark/profile_serving.py
  benchmark/profile_throughput.py
  docs/en/kv_int8.md
  docs/zh_cn/kv_int8.md
Labels: improvement

#816 fix finish_reason
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#805 Add api.py
  lmdeploy/__init__.py
  lmdeploy/api.py
  lmdeploy/cli/serve.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/openai/api_server.py
  tests/test_lmdeploy/test_cli.py
Labels: planned feature

#825 Support building docker image manually in CI
  .github/md-link-config.json
  .github/workflows/docker.yml
  docker/Dockerfile
Labels: enhancement

#828 add encode for opencompass
  docs/en/restful_api.md
  docs/zh_cn/restful_api.md
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#799 support image_embs input
  lmdeploy/serve/turbomind/triton_models/interactive/config.pbtxt
  lmdeploy/turbomind/turbomind.py
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/SequenceManager.h
Labels: planned feature

#803 Support turbomind bf16
  CMakeLists.txt
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/deploy/target_model/fp.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/kernels/activation_kernels.cu
  src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.cuh
  src/turbomind/kernels/decoder_masked_multihead_attention_utils.h
  src/turbomind/kernels/decoder_multihead_attention/array_ops.h
  src/turbomind/kernels/decoder_multihead_attention/decoder_multihead_attention.cu
  src/turbomind/kernels/decoder_multihead_attention/kv_cache.cu
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDenseWeight.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaLinear.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/flash_attention2/CMakeLists.txt
  src/turbomind/models/llama/flash_attention2/flash_api.cpp
  src/turbomind/models/llama/flash_attention2/flash_fwd_hdim128_bf16_sm80.cu
  src/turbomind/models/llama/flash_attention2/flash_fwd_hdim256_bf16_sm80.cu
  src/turbomind/models/llama/flash_attention2/flash_fwd_hdim32_bf16_sm80.cu
  src/turbomind/models/llama/flash_attention2/flash_fwd_hdim64_bf16_sm80.cu
  src/turbomind/models/llama/fused_multi_head_attention/llama_flash_attention_kernel.cu
  src/turbomind/models/llama/llama_decoder_kernels.cu
  src/turbomind/models/llama/llama_kernels.cu
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/models/llama/unified_decoder.cc
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
  src/turbomind/utils/cuda_type_utils.cuh
Labels: planned feature

#847 fix turbomind awq
  lmdeploy/turbomind/deploy/target_model/base.py
Labels: Bug:P1

#793 fix: awq should save bin files
  docs/zh_cn/turbomind.md
  lmdeploy/lite/apis/auto_awq.py
Labels: improvement

#850 Fix stop requests by await before turbomind queue.get()
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#848 [Fix] Fix meta tensor error
  lmdeploy/lite/utils/load.py
Labels: Bug:P1

#862 Fix cuda reinitialization in a multiprocessing setting
  lmdeploy/turbomind/deploy/target_model/base.py
Labels: Bug:P1

#856 launch gradio server directly with hf model
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/api_server_backend.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/turbomind_coupled.py
Labels: Bug:P1

#872 add tritonclient req
  requirements/serve.txt
Labels: Bug:P2

#735 [Feature] Add params config for api server web_ui
  lmdeploy/serve/gradio/api_server_backend.py
  lmdeploy/serve/gradio/triton_server_backend.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/openai/api_client.py
Labels: enhancement

#870 add top_k value for /v1/completions and update the documents
  docs/en/restful_api.md
  docs/zh_cn/restful_api.md
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#845 export "num_tokens_per_iter", "max_prefill_iters" and etc when converting a model
  lmdeploy/turbomind/deploy/target_model/base.py
Labels: improvement

#879 Move `api_server` dependencies from serve.txt to runtime.txt
  requirements/runtime.txt
  requirements/serve.txt
Labels: improvement

#875 Fix uninitialized parameter
  src/turbomind/models/llama/SequenceManager.cc
Labels: Bug:P1

#884 Refactor benchmark bash script
  benchmark/benchmark.sh
  benchmark/benchmark_13b.sh
  benchmark/benchmark_20b.sh
  benchmark/benchmark_70b.sh
  benchmark/benchmark_7b.sh
  benchmark/benchmark_all.sh
  benchmark/config/internlm_20b.ini
  benchmark/config/internlm_20b_4bit.ini
  benchmark/config/llama_13b.ini
  benchmark/config/llama_13b_4bit.ini
  benchmark/config/llama_70b.ini
  benchmark/config/llama_70b_4bit.ini
  benchmark/config/llama_7b.ini
  benchmark/config/llama_7b_4bit.ini
  docs/en/benchmark/a100_fp16.md
Labels: improvement

#844 Add test case for function regression
  .github/workflows/test.yml
  README.md
  README_zh-CN.md
  autotest/README.md
  autotest/chat_prompt_case.yaml
  autotest/config.yaml
  autotest/conftest.py
  autotest/pytest.ini
  autotest/restful_prompt_case.yaml
  autotest/test_order1_w4_quantization.py
  autotest/test_order2_convert.py
  autotest/test_order3_command_chat.py
  autotest/test_order3_hf_command_chat.py
  autotest/utils/rule_condition_assert.py
  autotest/utils/run_client_chat.py
  autotest/utils/run_restful_chat.py
Labels: improvement

#830 Compute cross entropy loss given a list of input tokens
  lmdeploy/turbomind/turbomind.py
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
Labels: planned feature

#877 Support QoS in api_server
  docs/en/qos.md
  docs/zh_cn/qos.md
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/serve/qos_engine/__init__.py
  lmdeploy/serve/qos_engine/inner_group_schd.py
  lmdeploy/serve/qos_engine/qos_config.json.template
  lmdeploy/serve/qos_engine/qos_engine.py
  lmdeploy/serve/qos_engine/usage_stats.py
Labels: planned feature

#893 Update test triton CI
  .github/scripts/test_triton_server.py
  .github/workflows/test.yml
Labels: improvement

#891 Update dockerfile
  .github/workflows/docker.yml
  docker/Dockerfile
  lmdeploy/__main__.py
Labels: improvement

#897 Fix overflow
  src/turbomind/kernels/activation_kernels.cu
Labels: Bug:P0

#874 add image chat demo
  README.md
  README_zh-CN.md
  examples/vl/README.md
  examples/vl/app.py
  examples/vl/extract_xcomposer_llm.py
  examples/vl/qwen_model.py
  examples/vl/xcomposer_model.py
  lmdeploy/serve/gradio/constants.py
Labels: planned feature
