Repository InternLM/lmdeploy, pull requests merged in 2023-11, with the labels that each got.

#544 Improve api_server and webui usage
  README.md
  README_zh-CN.md
  benchmark/profile_restful_api.py
  benchmark/profile_throughput.py
  docs/en/restful_api.md
  docs/en/supported_models/codellama.md
  docs/zh_cn/restful_api.md
  docs/zh_cn/supported_models/codellama.md
  lmdeploy/cli/serve.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/__init__.py
  lmdeploy/serve/gradio/api_server_backend.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/constants.py
  lmdeploy/serve/gradio/css.py
  lmdeploy/serve/gradio/triton_server_backend.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/turbomind/chat.py
Labels: improvement

#637 fix: gradio gr.Button.update deprecated after 4.0.0
  requirements.txt
Labels: improvement

#296 Refactor model conversion
  lmdeploy/cli/cli.py
  lmdeploy/serve/turbomind/deploy.py
  lmdeploy/turbomind/deploy/__init__.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/baichuan.py
  lmdeploy/turbomind/deploy/source_model/baichuan_awq.py
  lmdeploy/turbomind/deploy/source_model/base.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/source_model/llama_awq.py
  lmdeploy/turbomind/deploy/source_model/meta_llama.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
  lmdeploy/turbomind/deploy/source_model/qwen_awq.py
  lmdeploy/turbomind/deploy/target_model/__init__.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/deploy/target_model/fp.py
  lmdeploy/turbomind/deploy/target_model/w4.py
Labels: improvement

#499 [Enchance] internlm message to prompt
  lmdeploy/model.py
Labels: improvement

#634 update turbomind session_len with model.session_len
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#578 FIX: fix stop_session func bug
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#553 Manage session id using random int for gradio local mode
  lmdeploy/serve/gradio/api_server_backend.py
  lmdeploy/serve/gradio/triton_server_backend.py
  lmdeploy/serve/gradio/turbomind_coupled.py
Labels: improvement

#630 fix benchmark serving computation mistake
  benchmark/profile_restful_api.py
  benchmark/profile_serving.py
  benchmark/profile_throughput.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/protocol.py
Labels: Bug:P1

#599 Add UltraCM and WizardLM chat templates
  lmdeploy/model.py
Labels: improvement

#580 Add extra_requires to reduce dependencies
  README.md
  README_zh-CN.md
  docs/en/faq.md
  docs/en/supported_models/codellama.md
  docs/en/w4a16.md
  docs/zh_cn/faq.md
  docs/zh_cn/supported_models/codellama.md
  docs/zh_cn/w4a16.md
  requirements.txt
  requirements/build.txt
  requirements/lite.txt
  requirements/runtime.txt
  requirements/serve.txt
  requirements/test.txt
  setup.py
Labels: enhancement

#590 TurboMind 2
  .gitignore
  CMakeLists.txt
  examples/cpp/llama/llama_triton_example.cc
  src/turbomind/kernels/CMakeLists.txt
  src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_128.cu
  src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.cuh
  src/turbomind/kernels/decoder_multihead_attention/CMakeLists.txt
  src/turbomind/kernels/decoder_multihead_attention/array_ops.h
  src/turbomind/kernels/decoder_multihead_attention/decoder_multihead_attention.cu
  src/turbomind/kernels/decoder_multihead_attention/decoder_multihead_attention.h
  src/turbomind/kernels/decoder_multihead_attention/decoder_multihead_attention_params.h
  src/turbomind/kernels/decoder_multihead_attention/decoder_multihead_attention_template.h
  src/turbomind/kernels/decoder_multihead_attention/iterator.h
  src/turbomind/kernels/decoder_multihead_attention/kv_cache.cu
  src/turbomind/kernels/decoder_multihead_attention/kv_cache.h
  src/turbomind/kernels/decoder_multihead_attention/test_decoder_multihead_attention.cu
  src/turbomind/kernels/decoder_multihead_attention/test_utils.cu
  src/turbomind/kernels/decoder_multihead_attention/test_utils.h
  src/turbomind/kernels/decoder_multihead_attention/thread_map.h
  src/turbomind/kernels/gemm_s_f16/cta_iterator.h
  src/turbomind/kernels/gemm_s_f16/gemm_template.h
  src/turbomind/kernels/unfused_attention_kernels.cu
  src/turbomind/kernels/unfused_attention_kernels.h
  src/turbomind/models/llama/Barrier.h
  src/turbomind/models/llama/BlockManager.cc
  src/turbomind/models/llama/BlockManager.h
  src/turbomind/models/llama/CMakeLists.txt
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaContextAttentionLayer.cc
  src/turbomind/models/llama/LlamaContextAttentionLayer.h
  src/turbomind/models/llama/LlamaContextDecoder.cc
  src/turbomind/models/llama/LlamaContextDecoder.h
  src/turbomind/models/llama/LlamaDecoder.cc
  src/turbomind/models/llama/LlamaDecoder.h
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDecoderSelfAttentionLayer.cc
  src/turbomind/models/llama/LlamaDecoderSelfAttentionLayer.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/Request.h
  src/turbomind/models/llama/SequenceManager.cc
  src/turbomind/models/llama/SequenceManager.h
  src/turbomind/models/llama/llama_kernels.cu
  src/turbomind/models/llama/llama_kernels.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/models/llama/llama_utils.cu
  src/turbomind/models/llama/llama_utils.h
  src/turbomind/models/llama/test_cache_manager.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
  src/turbomind/triton_backend/transformer_triton_backend.hpp
  src/turbomind/utils/cuda_utils.h
  src/turbomind/utils/debug_utils.h
Labels: enhancement

#682 Fix init of batch state
  src/turbomind/models/llama/LlamaBatch.cc
Labels: Bug:P0

#644 Fix wrong eos_id and bos_id obtained through grpc api
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/serve/turbomind/triton_models/preprocessing/1/model.py
  lmdeploy/serve/turbomind/triton_models/preprocessing/config.pbtxt
  lmdeploy/serve/turbomind/utils.py
Labels: Bug:P1

#753 [Fix] build docker image failed since `packaging` is missing
  docker/Dockerfile
Labels: Bug:P0

#758 [Fix] Rollback the data type of `input_ids` to `TYPE_UINT32` in preprocessor's proto
  lmdeploy/serve/turbomind/triton_models/preprocessing/config.pbtxt
Labels: Bug:P0

#754 fix turbomind build on sm<80
  src/turbomind/models/llama/flash_attention2/flash_fwd_launch_template.h
Labels: Bug:P1

#736 Report first-token-latency and token-latency percentiles
  benchmark/README.md
  benchmark/profile_generation.py
  benchmark/profile_restful_api.py
  benchmark/profile_serving.py
  benchmark/profile_throughput.py
  docs/en/restful_api.md
  docs/zh_cn/restful_api.md
  lmdeploy/cli/serve.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#763 Update benchmark user guide
  docs/en/benchmark/profile_api_server.md
  docs/en/benchmark/profile_generation.md
  docs/en/benchmark/profile_throughput.md
  docs/en/benchmark/profile_triton_server.md
  docs/zh_cn/benchmark/profile_api_server.md
  docs/zh_cn/benchmark/profile_generation.md
  docs/zh_cn/benchmark/profile_throughput.md
  docs/zh_cn/benchmark/profile_triton_server.md
Labels: documentation
