Repository InternLM/lmdeploy, pull requests merged in 2023-08, with the labels that each got.

#173 [Docs] Translate turbomind.md
  docs/zh_cn/turbomind.md
Labels: documentation

#188 Fix build test error and move turbmind csrc test cases to `tests/csrc`
  CMakeLists.txt
  src/turbomind/kernels/logprob_kernels.cu
  tests/csrc/CMakeLists.txt
  tests/csrc/gemm_dequantize/CMakeLists.txt
  tests/csrc/gemm_dequantize/th_gemm_dequantize.cc
  tests/csrc/gemm_dequantize/th_gemm_dequantize.py
  tests/csrc/int8_gemm/CMakeLists.txt
  tests/csrc/int8_gemm/int8_gemm_test.cu
  tests/csrc/unittests/CMakeLists.txt
  tests/csrc/unittests/gtest_utils.h
  tests/csrc/unittests/test_attention_kernels.cu
  tests/csrc/unittests/test_context_attention_layer.cu
  tests/csrc/unittests/test_gemm.cu
  tests/csrc/unittests/test_gpt_kernels.cu
  tests/csrc/unittests/test_int8.cu
  tests/csrc/unittests/test_logprob_kernels.cu
  tests/csrc/unittests/test_penalty_kernels.cu
  tests/csrc/unittests/test_sampling.cu
  tests/csrc/unittests/test_sampling_kernels.cu
  tests/csrc/unittests/test_sampling_layer.cu
  tests/csrc/unittests/test_tensor.cu
  tests/csrc/unittests/unittest_utils.h
  tests/unittests/test_activation.cu
Labels: Bug:P1

#191 Fix launching client error by moving lmdeploy/turbomind/utils.py to lmdeploy/utils.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/utils.py
Labels: Bug:P1

#162 app.py support local model
  README.md
  README_zh-CN.md
  docs/en/build.md
  docs/zh_cn/build.md
  lmdeploy/app.py
  lmdeploy/serve/gradio/__init__.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/css.py
Labels: enhancement

#197 Improve postprocessing in TIS serving by applying Incremental de-tokenizing
  benchmark/profile_serving.py
  lmdeploy/serve/client.py
  lmdeploy/serve/turbomind/chatbot.py
Labels: enhancement

#199 [Feature] Add script to split HuggingFace model to the smallest sharded checkpoints
  lmdeploy/lite/apis/get_small_sharded_hf.py
Labels: enhancement

#200 Add non-stream inference api for chatbot
  lmdeploy/serve/client.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/turbomind/chat.py
Labels: enhancement

#178 [Refactor] Support multi-session chat
  README.md
  docs/en/pytorch.md
  lmdeploy/pytorch/adapters/__init__.py
  lmdeploy/pytorch/adapters/base.py
  lmdeploy/pytorch/adapters/internlm.py
  lmdeploy/pytorch/adapters/llama2.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/dist.py
  lmdeploy/pytorch/model.py
  lmdeploy/pytorch/session.py
  lmdeploy/pytorch/utils.py
  tests/pytorch/test_dist.py
  tests/pytorch/test_model.py
  tests/pytorch/test_utils.py
Labels: enhancement

#211 Add release note template
  .github/release.yml
Labels: improvement

#202 [Feature] Blazing fast W4A16 inference
  CMakeLists.txt
  docs/en/serving.md
  lmdeploy/serve/turbomind/deploy.py
  src/turbomind/kernels/CMakeLists.txt
  src/turbomind/kernels/gemm_s_f16/CMakeLists.txt
  src/turbomind/kernels/gemm_s_f16/common.h
  src/turbomind/kernels/gemm_s_f16/cta_iterator.h
  src/turbomind/kernels/gemm_s_f16/format.cu
  src/turbomind/kernels/gemm_s_f16/format.h
  src/turbomind/kernels/gemm_s_f16/gemm_s4_f16.cu
  src/turbomind/kernels/gemm_s_f16/gemm_s4_f16.h
  src/turbomind/kernels/gemm_s_f16/gemm_s4_f16_kernel.h
  src/turbomind/kernels/gemm_s_f16/gemm_template.h
  src/turbomind/kernels/gemm_s_f16/metric.h
  src/turbomind/kernels/gemm_s_f16/warp_iterator.h
  src/turbomind/models/llama/CMakeLists.txt
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDecoderLayerWeight.h
  src/turbomind/models/llama/LlamaDenseWeight.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaLinear.h
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/LlamaWeight.h
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
  src/turbomind/utils/memory_utils.cu
Labels: enhancement

#222 Fix TIS client got-no-space-result side effect brought by PR #197
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/serve/turbomind/triton_models/postprocessing/config.pbtxt
Labels: Bug:P0

#241 Remove specified version in user guide
  docs/en/w4a16.md
  docs/zh_cn/w4a16.md
Labels: documentation

#161 [Feature] Profiling tool for huggingface and deepspeed models
  benchmark/profile_hf_generation.py
Labels: enhancement

#252 Remove chat template
  lmdeploy/model.py
Labels: improvement

#236 adjust app.py dependency
  lmdeploy/serve/gradio/app.py
Labels: Bug:P1

#253 docs(quantzation): update description
  README.md
  README_zh-CN.md
  docs/en/kv_int8.md
  docs/zh_cn/kv_int8.md
Labels: documentation

#267 [Fix] Implement `movmatrix` using warp shuffling for CUDA < 11.8
  src/turbomind/kernels/gemm_s_f16/gemm_template.h
Labels: Bug:P0

#261 Add 'accelerate' to requirement list
  requirements.txt
Labels: Bug:P0

#230 [Feature] Qwen-7B, dynamic NTK scaling and logN scaling support in turbomind
  README.md
  README_zh-CN.md
  examples/cpp/llama/tokenizer.py
  lmdeploy/model.py
  lmdeploy/serve/turbomind/deploy.py
  lmdeploy/turbomind/tokenizer.py
  requirements.txt
  src/turbomind/kernels/decoder_masked_multihead_attention.h
  src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_128.cu
  src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.cuh
  src/turbomind/kernels/decoder_masked_multihead_attention_utils.h
  src/turbomind/kernels/unfused_attention_kernels.cu
  src/turbomind/kernels/unfused_attention_kernels.h
  src/turbomind/models/llama/LlamaContextAttentionLayer.cc
  src/turbomind/models/llama/LlamaContextAttentionLayer.h
  src/turbomind/models/llama/LlamaContextDecoder.cc
  src/turbomind/models/llama/LlamaContextDecoder.h
  src/turbomind/models/llama/LlamaDecoder.cc
  src/turbomind/models/llama/LlamaDecoder.h
  src/turbomind/models/llama/LlamaDecoderSelfAttentionLayer.cc
  src/turbomind/models/llama/LlamaDecoderSelfAttentionLayer.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
Labels: enhancement

#262 [Feature] Support TP for W4A16
  lmdeploy/serve/turbomind/deploy.py
Labels: improvement

#256 Check-in FAQ
  docs/en/faq.md
  docs/zh_cn/faq.md
Labels: documentation

#208 add readthedocs
  .gitignore
  .readthedocs.yml
  README.md
  README_zh-CN.md
  docs/en/Makefile
  docs/en/_static/css/readthedocs.css
  docs/en/_static/image/lmdeploy-logo.png
  docs/en/api.rst
  docs/en/conf.py
  docs/en/index.rst
  docs/en/make.bat
  docs/en/pytorch.md
  docs/en/switch_language.md
  docs/zh_cn/Makefile
  docs/zh_cn/_static/css/readthedocs.css
  docs/zh_cn/_static/image/lmdeploy-logo.png
  docs/zh_cn/api.rst
  docs/zh_cn/conf.py
  docs/zh_cn/index.rst
  docs/zh_cn/make.bat
  docs/zh_cn/switch_language.md
  requirements/docs.txt
  requirements/readthedocs.txt
Labels: documentation

#225 pass args including meta_prompt to model
  lmdeploy/model.py
  lmdeploy/serve/turbomind/chatbot.py
Labels: improvement

#285 Pad tok_embedding and output weights to make their shape divisible by TP
  lmdeploy/serve/turbomind/deploy.py
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/LlamaWeight.h
Labels: Bug:P1

#193 [Feature] Support decode with DP in pytorch
  .gitignore
  benchmark/benchmark_decode.py
  lmdeploy/pytorch/decode.py
  lmdeploy/pytorch/model.py
  tests/pytorch/test_decode.py
Labels: enhancement

#321 Fix readthedocs building
  .readthedocs.yml
Labels: documentation

#196 Add flashattention2
  CMakeLists.txt
  README.md
  README_zh-CN.md
  src/turbomind/models/llama/CMakeLists.txt
  src/turbomind/models/llama/LlamaContextAttentionLayer.cc
  src/turbomind/models/llama/flash_attention2/CMakeLists.txt
  src/turbomind/models/llama/flash_attention2/README.md
  src/turbomind/models/llama/flash_attention2/block_info.h
  src/turbomind/models/llama/flash_attention2/flash.h
  src/turbomind/models/llama/flash_attention2/flash_api.cpp
  src/turbomind/models/llama/flash_attention2/flash_fwd_hdim128_fp16_sm80.cu
  src/turbomind/models/llama/flash_attention2/flash_fwd_hdim256_fp16_sm80.cu
  src/turbomind/models/llama/flash_attention2/flash_fwd_hdim32_fp16_sm80.cu
  src/turbomind/models/llama/flash_attention2/flash_fwd_hdim64_fp16_sm80.cu
  src/turbomind/models/llama/flash_attention2/flash_fwd_kernel.h
  src/turbomind/models/llama/flash_attention2/flash_fwd_launch_template.h
  src/turbomind/models/llama/flash_attention2/kernel_traits.h
  src/turbomind/models/llama/flash_attention2/softmax.h
  src/turbomind/models/llama/flash_attention2/static_switch.h
  src/turbomind/models/llama/flash_attention2/utils.h
  src/turbomind/models/llama/fused_multi_head_attention/llama_flash_attention_kernel.cu
  src/turbomind/models/llama/llama_kernels.cu
  src/turbomind/models/llama/llama_kernels.h
  tests/csrc/unittests/test_context_attention_layer.cu
Labels: enhancement
