Repository InternLM/lmdeploy, pull requests merged in 2024-11, with the labels that each got.

#2681 Support min_tokens, min_p parameters for api_server
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: Bug:P1

#2697 fix index error when computing ppl on long-text prompt
  docs/en/llm/pipeline.md
  docs/zh_cn/llm/pipeline.md
  lmdeploy/serve/utils.py
Labels: Bug:P1

#2677 Better tp exit log.
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P2

#2519 support yarn in turbomind backend
  lmdeploy/pytorch/backends/default/rotary_embedding.py
  lmdeploy/pytorch/backends/rotary_embedding.py
  lmdeploy/pytorch/models/qwen2.py
  lmdeploy/pytorch/nn/__init__.py
  lmdeploy/pytorch/nn/rotary_embedding.py
  lmdeploy/turbomind/deploy/config.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  src/turbomind/kernels/attention/attention_params.h
  src/turbomind/kernels/attention/attention_universal.h
  src/turbomind/kernels/attention/kv_cache_utils_v2.cu
  src/turbomind/kernels/attention/kv_cache_utils_v2.h
  src/turbomind/kernels/attention/rotary_embedding.h
  src/turbomind/kernels/attention/test_attention.cu
  src/turbomind/models/llama/llama_params.h
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: enhancement

#2698 miss to read moe_ffn weights from converted tm model
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
Labels: Bug:P1

#2706 Fix turbomind TP
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: Bug:P1

#2670 feat: support dynamic/llama3 rotary embedding in ascend graph mode
  lmdeploy/pytorch/backends/dlinfer/rotary_embedding.py
Labels: improvement

#2627 add linear op on dlinfer platform
  lmdeploy/pytorch/backends/dlinfer/linear.py
  lmdeploy/pytorch/backends/dlinfer/op_backend.py
  lmdeploy/pytorch/kernels/dlinfer/__init__.py
  lmdeploy/pytorch/kernels/dlinfer/linear.py
Labels: enhancement

#2707 Add ensure_ascii = False for json.dumps
  lmdeploy/model.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/serve/async_engine.py
Labels: improvement

#2688 fix decoding kernel for deepseekv2
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
  tests/pytorch/kernel/test_paged_attention.py
Labels: Bug:P1

#2715 support turbomind head_dim 64
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/supported_models.py
  src/turbomind/kernels/attention/CMakeLists.txt
  src/turbomind/kernels/attention/attention.cu
  src/turbomind/kernels/attention/codegen/attention_sm70_64_f16.cu
  src/turbomind/kernels/attention/codegen/attention_sm75_64_f16.cu
  src/turbomind/kernels/attention/codegen/attention_sm80_64_bf16.cu
  src/turbomind/kernels/attention/codegen/attention_sm80_64_f16.cu
  src/turbomind/kernels/attention/codegen/decoding_sm70_64_f16_f16.cu
  src/turbomind/kernels/attention/codegen/decoding_sm70_64_f16_u4.cu
  src/turbomind/kernels/attention/codegen/decoding_sm70_64_f16_u8.cu
  src/turbomind/kernels/attention/codegen/decoding_sm75_64_f16_f16.cu
  src/turbomind/kernels/attention/codegen/decoding_sm75_64_f16_u4.cu
  src/turbomind/kernels/attention/codegen/decoding_sm75_64_f16_u8.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_64_bf16_bf16.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_64_bf16_u4.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_64_bf16_u8.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_64_f16_f16.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_64_f16_u4.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_64_f16_u8.cu
  src/turbomind/kernels/attention/decoding.cu
  src/turbomind/kernels/attention/impl_16816.h
  src/turbomind/kernels/attention/impl_1688.h
  src/turbomind/kernels/attention/impl_81616.h
  src/turbomind/kernels/attention/kv_cache_utils_v2.cu
  src/turbomind/kernels/attention/reduce.cu
  tests/test_lmdeploy/test_auto_backend.py
Labels: enhancement

#2718 fix tp exit code for pytorch engine
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P1

#2676 Flatten cache and add flashattention
  lmdeploy/pytorch/backends/cuda/attention.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/kernels/cuda/__init__.py
  lmdeploy/pytorch/kernels/cuda/flashattention.py
  lmdeploy/pytorch/kernels/cuda/flatten_kv_cache.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/mixtral.py
  lmdeploy/pytorch/models/utils/cudagraph.py
  tests/pytorch/kernel/test_flash_attention.py
  tests/pytorch/kernel/test_flatten_kv_cache.py
  tests/pytorch/kernel/test_paged_attention.py
Labels: improvement

#2710 [Feature]: support LlavaForConditionalGeneration with turbomind inference
  docs/en/multi_modal/llava.md
  docs/zh_cn/multi_modal/llava.md
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/llava.py
  lmdeploy/turbomind/generate_gemm_config.py
  lmdeploy/turbomind/supported_models.py
Labels: enhancement

#2690 Support ep, column major moe kernel.
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/backends/dlinfer/moe.py
  lmdeploy/pytorch/backends/moe.py
  lmdeploy/pytorch/kernels/cuda/fused_moe.py
  lmdeploy/pytorch/nn/moe.py
Labels: improvement

#2723 Support Qwen2-MoE models
  autotest/config.yaml
  lmdeploy/turbomind/deploy/config.py
  lmdeploy/turbomind/deploy/module.py
  lmdeploy/turbomind/deploy/source_model/mixtral.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
  lmdeploy/turbomind/supported_models.py
  src/turbomind/kernels/gemm/moe_utils_v2.cu
  src/turbomind/kernels/gemm/moe_utils_v2.h
  src/turbomind/kernels/gemm/test/test_moe_utils.cu
  src/turbomind/kernels/gemm/test/testbed.h
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDenseWeight.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaFfnLayer.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/models/llama/moe_ffn_layer.cc
  src/turbomind/models/llama/moe_ffn_layer.h
  src/turbomind/models/llama/unified_decoder.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: enhancement

#2725 Support mixtral moe AWQ quantization.
  autotest/utils/quantization_utils.py
  docs/en/quantization/w4a16.md
  docs/zh_cn/quantization/w4a16.md
  lmdeploy/cli/utils.py
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/quantization/activation/observer.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/lite/quantization/calibration.py
Labels: enhancement

#2719 Check server input
  lmdeploy/model.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#2744 fix issue that mono-internvl failed to fallback pytorch engine
  lmdeploy/turbomind/supported_models.py
Labels: Bug:P1

#2738 Support chemvlm
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/vl/model/internvl.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#2716 Support molmo in turbomind
  docs/en/multi_modal/index.rst
  docs/en/multi_modal/molmo.md
  docs/zh_cn/multi_modal/index.rst
  docs/zh_cn/multi_modal/molmo.md
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/turbomind/deploy/config.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/molmo.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/molmo.py
  lmdeploy/vl/templates.py
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/LlamaWeight.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: enhancement

#2756 Update ascend readme
  docs/en/get_started/ascend/get_started.md
  docs/zh_cn/get_started/ascend/get_started.md
Labels: documentation

#2758 Remove use_fast=True when loading tokenizer for lite auto_awq
  lmdeploy/lite/apis/calibrate.py
Labels: Bug:P1

#2761 set wrong head_dim for mistral-nemo
  lmdeploy/turbomind/deploy/source_model/llama.py
Labels: Bug:P1

#2737 feature: support qwen2.5 fuction_call
  docs/en/llm/api_server_tools.md
  docs/zh_cn/llm/api_server_tools.md
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#2765 Update supported models & Ascend doc
  docs/en/get_started/ascend/get_started.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/get_started/ascend/get_started.md
  docs/zh_cn/supported_models/supported_models.md
Labels: documentation

#2767 [Feature] support minicpm-v_2_6 for pytorch engine.
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/pytorch/models/minicpmv26.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/supported_models.py
Labels: enhancement

#2787 Support qwen2-vl AWQ quantization
  autotest/config.yaml
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/lite/utils/batch_split.py
  lmdeploy/vl/model/qwen2.py
Labels: enhancement

#2804 Optimize update_step_ctx on Ascend
  lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
Labels: improvement

#2825 disable prefix-caching for vl model
  lmdeploy/api.py
Labels: Bug:P1

#2817 Add Ascend installation adapter
  requirements/runtime_ascend.txt
  requirements_ascend.txt
  setup.py
Labels: improvement
