Repository InternLM/lmdeploy, pull requests merged in 2024-06, with the labels that each got.

#1715 update dockerfile and docs
  docker/Dockerfile
  docs/en/get_started.md
  docs/en/multi_modal/cogvlm.md
  docs/zh_cn/get_started.md
  docs/zh_cn/multi_modal/cogvlm.md
  lmdeploy/vl/model/cogvlm.py
Labels: improvement

#1714 lazy import VLAsyncEngine to avoid bringing in VLMs dependencies when deploying LLMs
  lmdeploy/archs.py
Labels: improvement

#1702 Refactor converter about get_input_model_registered_name and get_output_model_registered_name_and_config
  lmdeploy/archs.py
  lmdeploy/lite/utils/export_turbomind.py
  lmdeploy/messages.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/source_model/llama_awq.py
  lmdeploy/turbomind/deploy/source_model/meta_llama.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/utils.py
  tests/test_lmdeploy/test_turbomind/test_converter.py
  tests/test_lmdeploy/test_utils.py
Labels: improvement

#1736 docs: add BentoLMDeploy in README
  README.md
  README_zh-CN.md
Labels: documentation

#1705 Refine max_new_tokens logic to improve user experience
  lmdeploy/serve/async_engine.py
Labels: improvement

#1708 support MiniCPM-Llama3-V 2.5
  README.md
  README_zh-CN.md
  docs/en/multi_modal/minicpmv.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/multi_modal/minicpmv.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/minicpmv.py
  lmdeploy/turbomind/deploy/source_model/minicpmv_awq.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/minicpmv.py
  lmdeploy/vl/templates.py
Labels: enhancement

#1603 Refactor loading weights
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/__init__.py
  lmdeploy/pytorch/kernels/rerope_attention.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/dbrx.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/functional.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/internlm.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/mistral.py
  lmdeploy/pytorch/models/mixtral.py
  lmdeploy/pytorch/models/patch.py
  lmdeploy/pytorch/models/phi3.py
  lmdeploy/pytorch/models/qwen.py
  lmdeploy/pytorch/models/qwen2.py
  lmdeploy/pytorch/models/starcoder2.py
  lmdeploy/pytorch/tools/make_inputs.py
  lmdeploy/pytorch/weight_loader/__init__.py
  lmdeploy/pytorch/weight_loader/adapter_weight_loader.py
  lmdeploy/pytorch/weight_loader/dist_utils.py
  lmdeploy/pytorch/weight_loader/model_weight_loader.py
Labels: improvement

#1770 lock setuptools version in dockerfile
  docker/Dockerfile
Labels: Bug:P1

#1692 Fix openai package can not use proxy stream mode
  lmdeploy/serve/proxy/proxy.py
Labels: Bug:P1

#1768 Fix finish_reason
  lmdeploy/serve/async_engine.py
Labels: Bug:P1

#1754 fix uncached stop words
  lmdeploy/pytorch/engine/engine.py
Labels: Bug:P1

#1751 refactor config
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/configurations/__init__.py
  lmdeploy/pytorch/configurations/builder.py
  lmdeploy/pytorch/configurations/chatglm.py
  lmdeploy/pytorch/configurations/cogvlm.py
  lmdeploy/pytorch/configurations/dbrx.py
  lmdeploy/pytorch/configurations/default.py
  lmdeploy/pytorch/configurations/falcon.py
  lmdeploy/pytorch/configurations/gemma.py
  lmdeploy/pytorch/configurations/qwen.py
Labels: improvement

#1780 Add anomaly handler
  CMakeLists.txt
  src/turbomind/kernels/attention/attention_params.h
  src/turbomind/models/llama/CMakeLists.txt
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/Request.h
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/models/llama/unified_decoder.cc
  src/turbomind/utils/CMakeLists.txt
  src/turbomind/utils/anomaly_handler.cu
  src/turbomind/utils/anomaly_handler.h
  src/turbomind/utils/logger.h
Labels: improvement

#1782 support qwen2 1.5b
  lmdeploy/turbomind/deploy/source_model/deepseek_vl.py
  lmdeploy/turbomind/deploy/source_model/internlm2.py
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/source_model/xcomposer2.py
  lmdeploy/turbomind/deploy/source_model/xcomposer2_awq.py
  tests/test_lmdeploy/test_turbomind/test_converter.py
  tests/test_lmdeploy/test_utils.py
Labels: Bug:P1

#1761 fix falcon attention
  lmdeploy/pytorch/kernels/pagedattention.py
  lmdeploy/pytorch/models/llama.py
Labels: Bug:P1

#1773 Encode raw image file to base64
  lmdeploy/vl/templates.py
  lmdeploy/vl/utils.py
  tests/test_lmdeploy/test_vl_encode.py
Labels: improvement

#1769 skip inference for oversized inputs
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/engine_instance.py
Labels: improvement

#1789 Refine AsyncEngine exception handler
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#1791 fix: prevent numpy breakage
  requirements/runtime.txt
Labels: improvement

#1795 [side-effect] fix weight_type caused by PR #1702
  lmdeploy/turbomind/deploy/converter.py
  tests/test_lmdeploy/test_turbomind/test_converter.py
Labels: Bug:P1

#1765 More accurate time logging for ImageEncoder and fix concurrent image processing corruption
  lmdeploy/vl/engine.py
Labels: improvement

#1499 Optimize kernel launch for triton2.2.0 and triton2.3.0
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/check_env/triton_custom_add.py
  lmdeploy/pytorch/kernels/alibi_pagedattention.py
  lmdeploy/pytorch/kernels/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/fill_kv_cache.py
  lmdeploy/pytorch/kernels/fused_moe.py
  lmdeploy/pytorch/kernels/fused_rotary_emb.py
  lmdeploy/pytorch/kernels/mbgmm.py
  lmdeploy/pytorch/kernels/mbgmv.py
  lmdeploy/pytorch/kernels/multinomial_sampling.py
  lmdeploy/pytorch/kernels/pagedattention.py
  lmdeploy/pytorch/kernels/rearange_all_gather.py
  lmdeploy/pytorch/kernels/rms_norm.py
  lmdeploy/pytorch/kernels/triton_utils.py
  lmdeploy/pytorch/kernels/w8a8_triton_kernels.py
Labels: improvement

#1799 feat: auto set awq model_format from hf
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#1811 check driver mismatch
  lmdeploy/pytorch/check_env/__init__.py
Labels: improvement

#1812 fix best_match_model
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: Bug:P3

#1798 PyTorchEngine support latest internlm2 modeling.
  lmdeploy/lite/quantization/calibration.py
  lmdeploy/pytorch/modeling/modeling_internlm2.py
  lmdeploy/pytorch/models/internlm2.py
Labels: BC-breaking, improvement

#1724 Add GLM-4-9B-Chat
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/tokenizer.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/glm4.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/deploy/target_model/fp.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/utils.py
  src/turbomind/kernels/attention/array_ops.h
  src/turbomind/kernels/attention/attention_universal.h
  src/turbomind/kernels/attention/kv_cache_utils_v2.cu
  src/turbomind/kernels/attention/kv_cache_utils_v2.h
  src/turbomind/kernels/attention/reference.cu
  src/turbomind/kernels/attention/reference.h
  src/turbomind/kernels/attention/test_attention.cu
  src/turbomind/models/llama/unified_attention_layer.cc
  tests/test_lmdeploy/test_model.py
  tests/test_lmdeploy/test_tokenizer.py
Labels: enhancement

#1821 Fix Request completed log
  src/turbomind/models/llama/LlamaV2.cc
Labels: Bug:P0

#1807 AsyncEngine create cancel task in exception.
  lmdeploy/pytorch/engine/request.py
  lmdeploy/serve/async_engine.py
Labels: improvement

#1824 fix qwen-vl-chat
  lmdeploy/vl/model/qwen.py
Labels: Bug:P1

#1753 Detokenize with prompt token ids
  benchmark/profile_throughput.py
  lmdeploy/pytorch/chat.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/vl.py
  lmdeploy/tokenizer.py
  lmdeploy/turbomind/chat.py
Labels: Bug:P1

#1829 Update engine.py to fix small typos
  lmdeploy/vl/engine.py
Labels: Bug:P3

#1621 Torch deepseek v2
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/configurations/deepseek_v2.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/cuda/fill_kv_cache.py
  lmdeploy/pytorch/kernels/cuda/fused_moe.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
  lmdeploy/pytorch/kernels/cuda/rms_norm.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/pytorch/tools/make_inputs.py
  lmdeploy/pytorch/weight_loader/dist_utils.py
  lmdeploy/pytorch/weight_loader/model_weight_loader.py
  tests/pytorch/kernel/test_mbgmv.py
  tests/pytorch/kernel/test_paged_attention.py
  tests/pytorch/tools/test_make_inputs.py
Labels: enhancement

#1797 Support internvl-chat for pytorch engine
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/configurations/builder.py
  lmdeploy/pytorch/configurations/default.py
  lmdeploy/pytorch/configurations/internvl.py
  lmdeploy/pytorch/configurations/llava.py
  lmdeploy/pytorch/configurations/llava_hf.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/internvl.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/phi3.py
  lmdeploy/pytorch/supported_models.py
Labels: enhancement

#1837 fix image encoder request queue
  lmdeploy/vl/engine.py
Labels: improvement

#1838 Harden stream callback
  lmdeploy/turbomind/turbomind.py
  src/turbomind/models/llama/LlamaBatch.cc
Labels: improvement

#1793 Support Qwen2-1.5b awq
  lmdeploy/lite/apis/calibrate.py
Labels: improvement

#1652 Add interfaces to the pipeline to obtain logits and ppl
  docs/en/advance/long_context.md
  docs/en/inference/pipeline.md
  docs/en/inference/vl_pipeline.md
  docs/zh_cn/advance/long_context.md
  docs/zh_cn/inference/pipeline.md
  docs/zh_cn/inference/vl_pipeline.md
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/utils.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/vl/templates.py
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
Labels: enhancement

#1161 remove chat template config in turbomind engine
  lmdeploy/cli/chat.py
  lmdeploy/cli/cli.py
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/turbomind.py
Labels: BC-breaking, improvement

#1859 [side-effect] bring back "--cap" argument in chat cli
  lmdeploy/cli/chat.py
Labels: Bug:P1

#1860 Fix vl session-len
  lmdeploy/archs.py
  lmdeploy/utils.py
  tests/test_lmdeploy/test_utils.py
Labels: Bug:P1

#1873 fix gradio vl "stop_words"
  lmdeploy/serve/gradio/vl.py
Labels: Bug:P1
