Repository InternLM/lmdeploy, pull requests merged in 2024-02, with the labels that each got.

#1071 fix use TM_LOG_LEVEL environment variable first
  lmdeploy/api.py
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#1088 Speed up torch engine w8a8 model init
  lmdeploy/pytorch/modeling/convert_to_qmodules.py
  lmdeploy/pytorch/models/q_modules.py
Labels: improvement

#1100 fix turbomind CUDA runtime error invalid argument
  lmdeploy/serve/async_engine.py
Labels: Bug:P1

#1094 [Fix] Add safety check for incremental decode
  lmdeploy/tokenizer.py
  tests/test_lmdeploy/test_tokenizer.py
Labels: Bug:P1

#1092 make logging.logger's behavior consistent with MMLogger
  lmdeploy/pytorch/modeling/modeling_baichuan.py
  lmdeploy/pytorch/modeling/modeling_internlm.py
  lmdeploy/pytorch/modeling/modeling_internlm2.py
  lmdeploy/pytorch/modeling/modeling_llama.py
  lmdeploy/serve/qos_engine/inner_group_schd.py
  lmdeploy/serve/qos_engine/qos_engine.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/turbomind/utils.py
  lmdeploy/utils.py
Labels: improvement

#1093 fix device for get_ppl
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#1097 remove owned_session
  benchmark/profile_torch_throughput.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/serve/async_engine.py
  lmdeploy/tokenizer.py
Labels: improvement

#1085 unify engine initialization in pipeline
  lmdeploy/serve/async_engine.py
Labels: improvement

#1091 Add skip_special_tokens in GenerationConfig
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/serve/turbomind/triton_models/postprocessing/1/model.py
  lmdeploy/serve/turbomind/triton_models/postprocessing/config.pbtxt
  lmdeploy/serve/turbomind/utils.py
  lmdeploy/tokenizer.py
Labels: improvement

#1119 use default stop words for turbomind backend in pipeline
  lmdeploy/serve/async_engine.py
Labels: improvement

#1115 Add input_token_len to Response and update Response document
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
Labels: improvement

#1069 Support loading model from modelscope
  README.md
  README_zh-CN.md
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/turbomind/utils.py
  lmdeploy/utils.py
Labels: enhancement

#1126 fix pipeline init turbomind from workspace
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/utils.py
Labels: Bug:P1

#1036 fix embedding copy size
  src/turbomind/models/llama/LlamaV2.cc
Labels: Bug:P1

#1070 use stricter rules to get weight file
  lmdeploy/turbomind/deploy/source_model/llama.py
Labels: improvement

#1122 fix pytorch engine with peft==0.8.2
  lmdeploy/pytorch/adapter/adapter.py
  requirements/runtime.txt
Labels: Bug:P2

#1121 docs add debug turbomind guide
  docs/en/advance/debug_turbomind.md
  docs/zh_cn/advance/debug_turbomind.md
Labels: documentation

#1107 check pytorch engine environment
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/check_env/triton_custom_add.py
  lmdeploy/pytorch/engine/engine.py
Labels: improvement

#1162 Update Dockerfile order to launch the http service by `docker run` directly
  docs/en/index.rst
  docs/en/serving/restful_api.md
  docs/zh_cn/index.rst
  docs/zh_cn/serving/restful_api.md
Labels: improvement

#1137 support triton2.2
  lmdeploy/pytorch/kernels/pagedattention.py
  requirements/runtime.txt
Labels: Bug:P2

#1166 Support torch cache_max_entry_count
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/cli/chat.py
  lmdeploy/cli/serve.py
  lmdeploy/messages.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#953 Remove the manual model conversion during benchmark
  benchmark/benchmark.sh
  benchmark/benchmark_all.sh
  benchmark/benchmark_pytorch_engine_a100.sh
  benchmark/benchmark_turbomind_engine_a100.sh
  benchmark/config/internlm_20b.ini
  benchmark/config/internlm_20b_4bit.ini
  benchmark/config/llama_13b.ini
  benchmark/config/llama_13b_4bit.ini
  benchmark/config/llama_70b.ini
  benchmark/config/llama_70b_4bit.ini
  benchmark/config/llama_7b.ini
  benchmark/config/llama_7b_4bit.ini
  benchmark/profile_generation.py
  benchmark/profile_restful_api.py
  benchmark/profile_throughput.py
  benchmark/profile_torch_generation.py
  benchmark/profile_torch_throughput.py
  docs/en/benchmark/a100_fp16.md
  docs/en/benchmark/profile_api_server.md
  docs/en/benchmark/profile_generation.md
  docs/en/benchmark/profile_throughput.md
  docs/en/benchmark/profile_triton_server.md
  docs/zh_cn/benchmark/profile_api_server.md
  docs/zh_cn/benchmark/profile_generation.md
  docs/zh_cn/benchmark/profile_throughput.md
  docs/zh_cn/benchmark/profile_triton_server.md
  lmdeploy/cli/utils.py
  lmdeploy/turbomind/generate_gemm_config.py
Labels: improvement

#1138 Use asyncio.Lifoque for turbomind async_stream_infer
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#1149 Update api_server.py
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#1174 Add `top_k` in ChatCompletionRequest
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/serve/qos_engine/qos_engine.py
Labels: Bug:P1

#1175 minor fix benchmark generation guide and script
  benchmark/benchmark_pytorch_engine_a100.sh
  benchmark/benchmark_turbomind_engine_a100.sh
  benchmark/profile_throughput.py
  docs/en/benchmark/profile_generation.md
Labels: Bug:P2

#1181 Fix session length for profile generation
  benchmark/profile_generation.py
Labels: Bug:P1

#1185 fix torch engine infer
  docs/en/index.rst
  docs/zh_cn/index.rst
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/passkey_retrieval.py
Labels: Bug:P1

#1075 Support mistral and sliding window attention
  README.md
  README_zh-CN.md
  docs/en/advance/pytorch_new_model.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/advance/pytorch_new_model.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/cli/cli.py
  lmdeploy/model.py
  lmdeploy/pytorch/adapter/adapter.py
  lmdeploy/pytorch/block.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/mbgmm.py
  lmdeploy/pytorch/kernels/mbgmv.py
  lmdeploy/pytorch/kernels/pagedattention.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/functional.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/mistral.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/peft.py
  lmdeploy/pytorch/paging/block_manager/__init__.py
  lmdeploy/pytorch/paging/block_manager/base_block_manager.py
  lmdeploy/pytorch/paging/block_manager/default_block_manager.py
  lmdeploy/pytorch/paging/block_manager/window_block_manager.py
  lmdeploy/pytorch/paging/eviction_helper/base_eviction_helper.py
  lmdeploy/pytorch/paging/eviction_helper/recompute_eviction_helper.py
  lmdeploy/pytorch/paging/scheduler.py
  lmdeploy/pytorch/tools/make_inputs.py
  tests/pytorch/kernel/test_mbgmm.py
  tests/pytorch/kernel/test_mbgmv.py
  tests/pytorch/kernel/test_paged_attention.py
  tests/pytorch/paging/test_block_manager.py
  tests/pytorch/tools/test_make_inputs.py
Labels: enhancement

#1186 auto generate pipeline api for readthedocs
  docs/en/api.rst
  docs/en/api/pipeline.rst
  docs/en/index.rst
  docs/zh_cn/api.rst
  docs/zh_cn/api/pipeline.rst
  docs/zh_cn/index.rst
  requirements/readthedocs.txt
Labels: documentation

#1159 torch engine support chatglm3
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/module_map.py
Labels: enhancement

#1160 Support qwen1.5 in pytorch engine
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/cli/cli.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/qwen2.py
Labels: enhancement

#1192 Added tutorial document for deploying lmdeploy on Jetson series boards.
  README.md
  README_zh-CN.md
Labels: documentation

#1179 Use LifoQueue for turbomind async_stream_infer
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#1133 Support mixtral for pytorch engine
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/models/mixtral.py
  lmdeploy/pytorch/models/module_map.py
Labels: enhancement

#1163 Support torch deepseek moe
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/module_map.py
Labels: enhancement

#1205 fix module map
  lmdeploy/pytorch/models/module_map.py
Labels: Bug:P0

#1207 [Fix] Correct session length warning
  lmdeploy/serve/gradio/api_server_backend.py
  lmdeploy/serve/gradio/turbomind_coupled.py
Labels: Bug:P2

#1172 Update torch TP device map.
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P2

#1184 Support gemma model in pytorch engine
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/cli/cli.py
  lmdeploy/model.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/kernels/__init__.py
  lmdeploy/pytorch/kernels/fused_rotary_emb.py
  lmdeploy/pytorch/kernels/pagedattention.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/module_map.py
  requirements/runtime.txt
  tests/pytorch/kernel/test_fused_rotary_emb.py
Labels: enhancement

#1164 Update interactive output len strategy and response
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#1096 Support `min_new_tokens` generation config in pytorch engine
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/messages.py
Labels: improvement
