Repository InternLM/lmdeploy, pull requests merged in 2024-08, with the labels that each got.

#2201 Fix chunked prefill
  lmdeploy/turbomind/deploy/target_model/base.py
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/SequenceManager.cc
  src/turbomind/models/llama/SequenceManager.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/models/llama/unified_decoder.cc
  src/turbomind/models/llama/unified_decoder.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: enhancement

#2206 Check errors for attention kernels
  src/turbomind/models/llama/unified_attention_layer.cc
Labels: improvement

#2207 support VLMs with Qwen as the language model
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
Labels: enhancement

#2209 clearify the model type LLM or MLLM in supported model matrix
  README.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
Labels: documentation

#2131 Fix gradio serve using a wrong chat template
  lmdeploy/model.py
  lmdeploy/serve/gradio/turbomind_coupled.py
Labels: Bug:P1

#2212 fix runtime error when using dynamic scale rotary embed for InternLM2…
  lmdeploy/pytorch/kernels/dipu/apply_rotary_pos_emb.py
Labels: Bug:P1

#2182 update base image to support cuda12.4 in dockerfile
  .github/workflows/docker.yml
  docker/Dockerfile
  generate.sh
Labels: improvement

#2202 Stop synchronizing for `length_criterion`
  src/turbomind/kernels/stop_criteria_kernels.cu
  src/turbomind/layers/DynamicDecodeLayer.cc
  src/turbomind/models/llama/LlamaBatch.cc
Labels: improvement

#2139 adapt MiniCPM-Llama3-V-2_5 new code
  lmdeploy/vl/model/minicpmv.py
  lmdeploy/vl/templates.py
Labels: improvement

#2237 docs: add Japanese README
  README.md
  README_ja.md
  README_zh-CN.md
Labels: documentation

#2218 Add peer-access-enabled allocator
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h
  src/turbomind/utils/allocator.h
Labels: Bug:P1

#2038 Reorganize the user guide and update the get_started section
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/advance/debug_turbomind.md
  docs/en/benchmark/evaluate_with_opencompass.md
  docs/en/benchmark/profile_api_server.md
  docs/en/build.md
  docs/en/conf.py
  docs/en/get_started.md
  docs/en/index.rst
  docs/en/installation.md
  docs/en/llm/api_server.md
  docs/en/llm/api_server_tools.md
  docs/en/llm/gradio.md
  docs/en/llm/pipeline.md
  docs/en/llm/proxy_server.md
  docs/en/llm/qos.md
  docs/en/multi_modal/api_server_vl.md
  docs/en/multi_modal/cogvlm.md
  docs/en/multi_modal/index.rst
  docs/en/multi_modal/internvl.md
  docs/en/multi_modal/llava.md
  docs/en/multi_modal/vl_pipeline.md
  docs/en/quantization/kv_quant.md
  docs/en/quantization/w4a16.md
  docs/en/quantization/w8a8.md
  docs/en/supported_models/codellama.md
  docs/zh_cn/advance/debug_turbomind.md
  docs/zh_cn/benchmark/evaluate_with_opencompass.md
  docs/zh_cn/benchmark/profile_api_server.md
  docs/zh_cn/build.md
  docs/zh_cn/conf.py
  docs/zh_cn/get_started.md
  docs/zh_cn/index.rst
  docs/zh_cn/installation.md
  docs/zh_cn/llm/api_server.md
  docs/zh_cn/llm/api_server_tools.md
  docs/zh_cn/llm/gradio.md
  docs/zh_cn/llm/pipeline.md
  docs/zh_cn/llm/proxy_server.md
  docs/zh_cn/llm/qos.md
  docs/zh_cn/multi_modal/api_server_vl.md
  docs/zh_cn/multi_modal/index.rst
  docs/zh_cn/multi_modal/internvl.md
  docs/zh_cn/multi_modal/llava.md
  docs/zh_cn/multi_modal/vl_pipeline.md
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/supported_models/codellama.md
  generate.sh
Labels: documentation

#2246 cancel support baichuan2 7b awq in pytorch engine
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
Labels: documentation

#1931 Remove deprecated arguments from API and clarify model_name and chat_template_name
  .gitignore
  README.md
  README_ja.md
  README_zh-CN.md
  autotest/tools/convert/test_convert.py
  benchmark/profile_generation.py
  docs/en/benchmark/evaluate_with_opencompass.md
  docs/en/get_started.md
  docs/en/llm/codellama.md
  docs/en/multi_modal/cogvlm.md
  docs/en/multi_modal/minicpmv.md
  docs/en/multi_modal/xcomposer2d5.md
  docs/en/supported_models/codellama.md
  docs/zh_cn/benchmark/evaluate_with_opencompass.md
  docs/zh_cn/llm/codellama.md
  docs/zh_cn/multi_modal/cogvlm.md
  docs/zh_cn/multi_modal/minicpmv.md
  docs/zh_cn/multi_modal/xcomposer2d5.md
  docs/zh_cn/supported_models/codellama.md
  lmdeploy/api.py
  lmdeploy/archs.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/lite.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/deploy/target_model/fp.py
  lmdeploy/turbomind/deploy/target_model/plora.py
  lmdeploy/turbomind/deploy/target_model/plora_w4.py
  lmdeploy/turbomind/deploy/target_model/w4.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/utils.py
  lmdeploy/vl/templates.py
  tests/test_lmdeploy/test_async_engine.py
Labels: BC-breaking, improvement

#2084 Add user guide about slora serving
  docs/en/index.rst
  docs/en/llm/api_server_lora.md
  docs/zh_cn/index.rst
  docs/zh_cn/llm/api_server_lora.md
Labels: documentation

#2134 Fix duplicated session_id when pipeline is used by multithreads
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
Labels: BC-breaking, improvement

#2256 enable run vlm with pytorch engine in gradio
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/vl.py
Labels: Bug:P1

#2285 remove eviction param
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/engine.py
Labels: improvement

#2245 support vlm custom image process parameters in openai input format
  lmdeploy/pytorch/configurations/phi3_vision.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/vl/engine.py
  lmdeploy/vl/model/base.py
  lmdeploy/vl/model/internvl.py
  lmdeploy/vl/templates.py
Labels: enhancement

#2275 fix side-effect: failed to update tm model config with tm engine config
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#2313 Add stream options to control usage
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#2240 fix the issue missing dependencies in the Dockerfile and pip
  docker/Dockerfile
  docker/InternVL_Dockerfile
  docs/en/multi_modal/internvl.md
  docs/zh_cn/multi_modal/internvl.md
  requirements/runtime.txt
Labels: Bug:P1

#2321 add device type for pytorch engine in cli
  lmdeploy/cli/cli.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/turbomind/chat.py
Labels: improvement

#2333 Update error status_code to raise error in openai client
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#2337 Change to use device instead of device-type in cli
  lmdeploy/cli/cli.py
  lmdeploy/cli/lite.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
Labels: improvement

#2342 Add GEMM test utils
  src/turbomind/kernels/gemm/gemm.cu
  src/turbomind/kernels/gemm/test/gemm_bench.cu
  src/turbomind/kernels/gemm/test/gemm_test.cu
  src/turbomind/kernels/gemm/test/models.h
  src/turbomind/kernels/gemm/test/quantization_impl.h
  src/turbomind/kernels/gemm/test/test_utils.cu
  src/turbomind/kernels/gemm/test/test_utils.h
  src/turbomind/kernels/gemm/test/testbed.h
  src/turbomind/kernels/gemm/types.h
  src/turbomind/models/llama/LlamaLinear.cu
Labels: improvement

#2343 Add environment variable to control SILU fusion
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
Labels: improvement

#2325 Fix the way to get "quantization_config" from model's coniguration
  lmdeploy/cli/utils.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#2339 Use single thread per model instance
  lmdeploy/turbomind/turbomind.py
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/Request.h
Labels: improvement

#2344 add cache to speed up docker building
  docker/Dockerfile
Labels: improvement

#2345 add max_prefill_token_num argument in CLI
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
Labels: improvement

#2215 Fix hidden size and support mistral nemo
  lmdeploy/turbomind/deploy/source_model/deepseek_vl.py
  lmdeploy/turbomind/deploy/source_model/glm4.py
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
  lmdeploy/turbomind/deploy/target_model/base.py
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDecoderLayerWeight.h
  src/turbomind/models/llama/LlamaFfnLayer.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/LlamaWeight.h
  src/turbomind/models/llama/unified_attention_layer.h
  src/turbomind/models/llama/unified_decoder.cc
  src/turbomind/models/llama/unified_decoder.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
Labels: enhancement

#2329 Support custom logits processors
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/messages.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: enhancement

#1962 torch engine optimize prefill for long context
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
Labels: improvement

#2358 Default rope_scaling_factor of TurbomindEngineConfig to None
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/turbomind/chat.py
Labels: Bug:P1

#2352 Refactor turbomind (1/N)
  src/turbomind/kernels/attention/attention_params.h
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDecoderLayerWeight.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaFfnLayer.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/LlamaWeight.h
  src/turbomind/models/llama/context.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/models/llama/unified_attention_layer.h
  src/turbomind/models/llama/unified_decoder.cc
  src/turbomind/models/llama/unified_decoder.h
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h
  src/turbomind/triton_backend/transformer_triton_backend.hpp
Labels: improvement

#2351 support openbmb/MiniCPM-V-2_6
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/multi_modal/minicpmv.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/multi_modal/minicpmv.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/model.py
  lmdeploy/vl/model/minicpmv.py
  lmdeploy/vl/templates.py
Labels: enhancement

#2361 Support phi3.5 for pytorch engine
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/multi_modal/index.rst
  docs/en/multi_modal/phi3.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/multi_modal/index.rst
  docs/zh_cn/multi_modal/phi3.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/phi3_moe.py
  lmdeploy/pytorch/supported_models.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#2362 Fix the logic of update engine_config to TurbomindModelConfig for both tm model and hf model
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#2388 fix cache position for pytorch engine
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/internlm.py
  lmdeploy/pytorch/models/phi3.py
  lmdeploy/pytorch/models/starcoder2.py
Labels: Bug:P2

#2372 Add auto_gptq to lmdeploy lite
  lmdeploy/cli/lite.py
  lmdeploy/lite/apis/gptq.py
  lmdeploy/lite/modeling/__init__.py
  lmdeploy/lite/modeling/internlm2_gptq.py
  lmdeploy/lite/utils/calib_dataloader.py
Labels: enhancement

#2378 Reorganize the table of content of get_started
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/advance/debug_turbomind.md
  docs/en/benchmark/evaluate_with_opencompass.md
  docs/en/get_started/ascend/get_started.md
  docs/en/get_started/get_started.md
  docs/en/get_started/index.rst
  docs/en/get_started/installation.md
  docs/en/index.rst
  docs/en/llm/qos.md
  docs/en/multi_modal/cogvlm.md
  docs/en/multi_modal/internvl.md
  docs/en/multi_modal/minicpmv.md
  docs/en/multi_modal/phi3.md
  docs/en/multi_modal/xcomposer2d5.md
  docs/en/quantization/w4a16.md
  docs/zh_cn/advance/debug_turbomind.md
  docs/zh_cn/benchmark/evaluate_with_opencompass.md
  docs/zh_cn/get_started/ascend/get_started.md
  docs/zh_cn/get_started/get_started.md
  docs/zh_cn/get_started/index.rst
  docs/zh_cn/get_started/installation.md
  docs/zh_cn/index.rst
  docs/zh_cn/llm/qos.md
  docs/zh_cn/multi_modal/cogvlm.md
  docs/zh_cn/multi_modal/internvl.md
  docs/zh_cn/multi_modal/minicpmv.md
  docs/zh_cn/multi_modal/phi3.md
  docs/zh_cn/multi_modal/xcomposer2d5.md
  docs/zh_cn/quantization/w4a16.md
Labels: documentation

#2278 build(ascend): add Dockerfile for ascend aarch64 910B
  .pre-commit-config.yaml
  docker/Dockerfile_aarch64_910B
Labels: enhancement

#2395 Fix /v1/completions batch order wrong
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1
