Repository InternLM/lmdeploy, pull requests merged in 2024-05, with the labels that each got.

#1507 Remove split batch inside pipline inference function
  lmdeploy/serve/async_engine.py
Labels: improvement

#1533 Fix turbomind import in windows
  lmdeploy/turbomind/__init__.py
Labels: Bug:P1

#1534 Update docker docs for VL api
  docs/en/serving/api_server_vl.md
  docs/zh_cn/serving/api_server.md
Labels: documentation

#1527 Remove first empty chunck for api_server
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#1528 add benchmark script to profile pipeline APIs
  benchmark/profile_pipeline_api.py
  lmdeploy/serve/async_engine.py
Labels: improvement

#1488 doc: add example of deploying api server to Kubernetes
  docs/en/serving/api_server.md
  docs/zh_cn/serving/api_server.md
  k8s/deployment.yaml
  k8s/service.yaml
Labels: documentation

#1546 Fix convert qwen2 to turbomind
  lmdeploy/turbomind/deploy/converter.py
Labels: Bug:P1

#1429 PyTorch Engine hash table based prefix caching
  benchmark/profile_throughput.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/block.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/paging/block_manager/base_block_manager.py
  lmdeploy/pytorch/paging/block_manager/default_block_manager.py
  lmdeploy/pytorch/paging/block_manager/window_block_manager.py
  lmdeploy/pytorch/paging/block_trie.py
  lmdeploy/pytorch/paging/eviction_helper/__init__.py
  lmdeploy/pytorch/paging/eviction_helper/base_eviction_helper.py
  lmdeploy/pytorch/paging/eviction_helper/copy_eviction_helper.py
  lmdeploy/pytorch/paging/eviction_helper/recompute_eviction_helper.py
  lmdeploy/pytorch/paging/scheduler.py
  tests/pytorch/paging/test_block_manager.py
  tests/pytorch/paging/test_block_trie.py
  tests/pytorch/paging/test_scheduler.py
Labels: enhancement

#1447 Optimize slora
  lmdeploy/pytorch/adapter/adapter.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/mbgmm.py
  lmdeploy/pytorch/kernels/mbgmv.py
  lmdeploy/pytorch/models/peft.py
  lmdeploy/pytorch/paging/block_manager/__init__.py
  lmdeploy/pytorch/paging/block_manager/base_block_manager.py
  lmdeploy/pytorch/paging/block_manager/default_block_manager.py
  lmdeploy/pytorch/paging/block_manager/window_block_manager.py
  lmdeploy/pytorch/paging/scheduler.py
  tests/pytorch/kernel/test_mbgmm.py
  tests/pytorch/kernel/test_mbgmv.py
Labels: improvement

#1575 Use a faster format for images in VLMs
  lmdeploy/vl/utils.py
Labels: improvement

#1568 Fix typo in w8a8.md
  docs/en/quantization/w8a8.md
Labels: documentation

#1566 add chat-template args to chat cli
  lmdeploy/cli/cli.py
  lmdeploy/pytorch/chat.py
Labels: improvement

#1497 support phi3
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/pytorch/dist_utils.py
  lmdeploy/pytorch/kernels/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/pagedattention.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/phi3.py
Labels: enhancement

#1550 Get the max session len from config.json
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/utils.py
Labels: improvement

#1450 Turbomind prefix caching
  .github/workflows/lint.yml
  benchmark/profile_generation.py
  benchmark/profile_pipeline_api.py
  benchmark/profile_throughput.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/serve.py
  lmdeploy/messages.py
  lmdeploy/turbomind/deploy/target_model/base.py
  src/turbomind/models/llama/BlockManager.cc
  src/turbomind/models/llama/BlockTrie.cc
  src/turbomind/models/llama/BlockTrie.h
  src/turbomind/models/llama/CMakeLists.txt
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/SequenceManager.cc
  src/turbomind/models/llama/SequenceManager.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: enhancement

#1598 fix logger init
  lmdeploy/utils.py
Labels: Bug:P1

#1353 Optimize w8a8 kernel
  lmdeploy/pytorch/kernels/w8a8_triton_kernels.py
Labels: improvement

#1594 Bugfix: wrongly assign gen_config with True
  lmdeploy/serve/qos_engine/qos_engine.py
Labels: Bug:P1

#1605 support python 3.12
  .github/workflows/cuda11.8-whl-release.yml
  .github/workflows/pypi.yml
  builder/manywheel/Dockerfile_2014
  builder/manywheel/build_all_wheel.sh
  builder/manywheel/entrypoint_build.sh
  requirements/runtime.txt
  src/turbomind/kernels/stop_criteria_kernels.cu
Labels: improvement

#1545 Enable search scale for awq
  docs/en/quantization/w4a16.md
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/quantization/w8a8.md
  lmdeploy/cli/lite.py
  lmdeploy/cli/utils.py
  lmdeploy/legacy/pytorch/modules/linear.py
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/lite/quantization/__init__.py
  lmdeploy/lite/quantization/activation/observer.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/lite/quantization/calibration.py
  lmdeploy/lite/utils/batch_split.py
  lmdeploy/lite/utils/calib_dataloader.py
Labels: enhancement

#1606 Enable split-kv for attention
  src/turbomind/kernels/attention/attention_universal.h
  src/turbomind/kernels/attention/test_attention.cu
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/models/llama/unified_attention_layer.h
Labels: Bug:P1, turbomind

#1520 Optimize moe
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/__init__.py
  lmdeploy/pytorch/kernels/fused_moe.py
  lmdeploy/pytorch/models/dbrx.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/mixtral.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/patch.py
  lmdeploy/pytorch/models/qwen2_moe.py
  lmdeploy/utils.py
  tests/pytorch/kernel/test_fused_moe.py
Labels: improvement

#1640 Fix xcomposer2 vision model process
  lmdeploy/vl/model/xcomposer2.py
Labels: Bug:P1

#1636 Fix NTK scaling
  src/turbomind/models/llama/LlamaBatch.cc
Labels: Bug:P2, turbomind

#1616 Fix illegal memory access when seq_len < 64
  src/turbomind/kernels/attention/attention.h
  src/turbomind/kernels/attention/attention_universal.h
  src/turbomind/kernels/attention/test_attention.cu
  src/turbomind/models/llama/unified_attention_layer.cc
Labels: Bug:P1

#1591 Balance vision model weights on multi gpus
  docs/en/inference/vl_pipeline.md
  docs/zh_cn/inference/vl_pipeline.md
  lmdeploy/__init__.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/vl/engine.py
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/model/internvl.py
  lmdeploy/vl/model/internvl_llava.py
  lmdeploy/vl/model/llava.py
  lmdeploy/vl/model/mini_gemeni.py
  lmdeploy/vl/model/qwen.py
  lmdeploy/vl/model/utils.py
  lmdeploy/vl/model/xcomposer2.py
  lmdeploy/vl/model/yi.py
  lmdeploy/vl/templates.py
  requirements/runtime.txt
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc
  src/turbomind/layers/sampling_layers/TopKSamplingLayer.cu
  src/turbomind/layers/sampling_layers/TopPSamplingLayer.cu
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: improvement

#1648 fix deepseek-vl when tp is 1
  lmdeploy/vl/model/deepseek.py
Labels: Bug:P1

#1561 fix logprobs output
  lmdeploy/turbomind/turbomind.py
  src/turbomind/kernels/sampling_topk_kernels.cu
  src/turbomind/models/llama/LlamaBatch.cc
Labels: Bug:P1

#1553 [Feature] Support vl models quantization
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/deepseek_vl_awq.py
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/turbomind/deploy/source_model/xcomposer2.py
  lmdeploy/turbomind/deploy/source_model/xcomposer2_awq.py
  lmdeploy/turbomind/deploy/target_model/__init__.py
  lmdeploy/turbomind/deploy/target_model/plora_w4.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/model/internvl.py
  lmdeploy/vl/model/internvl_llava.py
  lmdeploy/vl/model/llava.py
  lmdeploy/vl/model/mini_gemeni.py
  lmdeploy/vl/model/qwen.py
  lmdeploy/vl/model/xcomposer2.py
  lmdeploy/vl/model/yi.py
  src/turbomind/kernels/gemm_s_f16/gemm_s4_f16.cu
  src/turbomind/kernels/gemm_s_f16/gemm_s4_f16.h
  src/turbomind/kernels/gemm_s_f16/gemm_template.h
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDecoderLayerWeight.h
  src/turbomind/models/llama/LlamaLinear.h
Labels: enhancement

#1654 fix fused-moe in triton2.2.0
  lmdeploy/pytorch/kernels/fused_moe.py
Labels: Bug:P1

#1627 Custom vl user input
  docs/en/inference/vl_pipeline.md
  docs/zh_cn/inference/vl_pipeline.md
  lmdeploy/model.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/vl/templates.py
  tests/test_lmdeploy/test_vl_template.py
Labels: improvement

#1649 Optimize GQA/MQA
  lmdeploy/pytorch/kernels/pagedattention.py
  tests/pytorch/kernel/test_paged_attention.py
Labels: improvement

#1597 Update doc for prefix caching
  docs/en/inference/turbomind_config.md
  docs/zh_cn/inference/turbomind_config.md
Labels: documentation

#1657 Update VL document
  README.md
  README_zh-CN.md
  docs/en/inference/vl_pipeline.md
  docs/en/quantization/w4a16.md
  docs/zh_cn/inference/vl_pipeline.md
  docs/zh_cn/quantization/w4a16.md
Labels: documentation

#1679 Add health endpoint
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#1690 fix typos
  docs/en/inference/vl_pipeline.md
  docs/zh_cn/inference/vl_pipeline.md
  lmdeploy/__init__.py
  lmdeploy/cli/serve.py
  lmdeploy/messages.py
  lmdeploy/vl/engine.py
Labels: Bug:P1

#1687 upgrade the version of the dependency package peft
  requirements/runtime.txt
Labels: improvement

#1677 Follow the conventional model_name
  autotest/utils/run_restful_chat.py
  lmdeploy/serve/async_engine.py
  tests/test_lmdeploy/test_async_engine.py
Labels: BC-breaking, improvement

#1684 API Image URL fetch timeout
  docs/en/faq.md
  docs/zh_cn/faq.md
  lmdeploy/vl/utils.py
Labels: improvement
