Repository InternLM/lmdeploy, pull requests merged in 2024-07, with the labels that each got.

#1886 fix qwen2 cache_position for PyTorch Engine when transformers>4.41.2
  lmdeploy/pytorch/models/qwen2.py
Labels: Bug:P1

#1892 docs: update cache-max-entry-count help message
  lmdeploy/cli/utils.py
Labels: improvement

#1875 misc: rm unnecessary files
  CMakeLists.txt
  examples/cpp/llama/CMakeLists.txt
  examples/cpp/llama/llama_triton_example.cc
  src/turbomind/models/BaseWeight.h
  src/turbomind/utils/CMakeLists.txt
  src/turbomind/utils/IA3.h
  src/turbomind/utils/ScaleList.h
  src/turbomind/utils/activation_types.h
  src/turbomind/utils/conv2d.h
  src/turbomind/utils/convert_data_type.h
  src/turbomind/utils/cublasFP8MMWrapper.cu
  src/turbomind/utils/cublasFP8MMWrapper.h
  src/turbomind/utils/gpu_buf.h
  src/turbomind/utils/prompt_learning.h
  src/turbomind/utils/wenet_conv2d.h
  src/turbomind/utils/word_list.cc
  src/turbomind/utils/word_list.h
Labels: improvement

#1881 Fix error link reference
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDecoderLayerWeight.h
  src/turbomind/models/llama/LlamaDenseWeight.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaFfnLayer.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/LlamaWeight.h
  src/turbomind/models/llama/llama_gemm.cc
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/models/llama/unified_attention_layer.h
  src/turbomind/triton_backend/llama/CMakeLists.txt
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h
  src/turbomind/triton_backend/transformer_triton_backend.cpp
  src/turbomind/triton_backend/transformer_triton_backend.hpp
Labels: Bug:P3

#1890 Fix internlm-xcomposer2-vl awq search scale
  lmdeploy/lite/quantization/calibration.py
Labels: Bug:P2

#1823 drop stop words
  lmdeploy/pytorch/engine/engine.py
Labels: improvement

#1874 fix SamplingDecodeTest and SamplingDecodeTest2 unittest failure
  debug.sh
  tests/csrc/unittests/test_sampling_layer.cu
Labels: Bug:P2

#1877 docs: update faq for turbomind so not found
  docs/en/faq.md
  docs/zh_cn/faq.md
Labels: documentation

#1876 Add usage in stream response
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#1845 Support phi3-vision
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/pytorch/configurations/phi3_vision.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/phi3_vision.py
  lmdeploy/vl/templates.py
Labels: enhancement

#1880 [Doc]: Change to sphinx-book-theme in readthedocs
  docs/en/.readthedocs.yaml
  docs/en/_static/css/readthedocs.css
  docs/en/conf.py
  docs/en/index.rst
  docs/en/switch_language.md
  docs/zh_cn/.readthedocs.yaml
  docs/zh_cn/_static/css/readthedocs.css
  docs/zh_cn/conf.py
  docs/zh_cn/index.rst
  docs/zh_cn/switch_language.md
  requirements/docs.txt
Labels: documentation

#1899 Remove deprecated chat cli and vl examples
  README.md
  README_zh-CN.md
  autotest/tools/chat/test_command_chat_hf_pytorch.py
  autotest/utils/run_client_chat.py
  examples/vl/README.md
  examples/vl/app.py
  examples/vl/extract_xcomposer_llm.py
  examples/vl/qwen_model.py
  examples/vl/xcomposer_model.py
  lmdeploy/cli/chat.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/entrypoint.py
  lmdeploy/turbomind/supported_models.py
  tests/test_lmdeploy/test_auto_backend.py
Labels: BC-breaking, improvement

#1909 Fix smem size for fused split-kv reduction
  src/turbomind/kernels/attention/attention_template.h
  src/turbomind/kernels/attention/attention_universal.h
  src/turbomind/kernels/attention/decoding_template.h
Labels: Bug:P1

#1854 vision model use tp number of gpu
  lmdeploy/vl/model/base.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/cogvlm.py
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/model/internvl.py
  lmdeploy/vl/model/internvl_llava.py
  lmdeploy/vl/model/llava.py
  lmdeploy/vl/model/llava_hf.py
  lmdeploy/vl/model/llava_next.py
  lmdeploy/vl/model/mini_gemeni.py
  lmdeploy/vl/model/minicpmv.py
  lmdeploy/vl/model/phi3_vision.py
  lmdeploy/vl/model/qwen.py
  lmdeploy/vl/model/xcomposer2.py
  lmdeploy/vl/model/yi.py
Labels: improvement

#1922 misc: add default api_server_url for api_client
  lmdeploy/serve/openai/api_client.py
Labels: improvement

#1911 Support internvl2 chat template
  lmdeploy/model.py
  lmdeploy/turbomind/supported_models.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#1924 support gemma2 in pytorch engine
  README.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/pytorch/configurations/gemma.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/supported_models.py
Labels: enhancement

#1946 docs: update compatibility section in README
  README.md
  README_zh-CN.md
Labels: documentation

#1940 refactor: update awq linear and rm legacy
  lmdeploy/legacy/__init__.py
  lmdeploy/legacy/pytorch/__init__.py
  lmdeploy/legacy/pytorch/accel.py
  lmdeploy/legacy/pytorch/adapters/__init__.py
  lmdeploy/legacy/pytorch/adapters/base.py
  lmdeploy/legacy/pytorch/adapters/internlm.py
  lmdeploy/legacy/pytorch/adapters/llama2.py
  lmdeploy/legacy/pytorch/chat.py
  lmdeploy/legacy/pytorch/decode.py
  lmdeploy/legacy/pytorch/dist.py
  lmdeploy/legacy/pytorch/model.py
  lmdeploy/legacy/pytorch/session.py
  lmdeploy/legacy/pytorch/utils.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/lite/quantization/modules/__init__.py
  lmdeploy/lite/quantization/modules/linear.py
Labels: improvement

#1944 feat: add gpu topo for check_env
  lmdeploy/cli/cli.py
Labels: improvement

#1956 fix llama3 chat template
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: Bug:P2

#1952 fix transformers version check for InternVL2
  lmdeploy/tokenizer.py
  tests/test_lmdeploy/test_tokenizer.py
Labels: improvement

#1763 Add tools to api_server for InternLM2 model
  docs/en/index.rst
  docs/en/serving/api_server.md
  docs/en/serving/api_server_tools.md
  docs/zh_cn/index.rst
  docs/zh_cn/serving/api_server.md
  docs/zh_cn/serving/api_server_tools.md
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/vl/templates.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#1930 Upgrade gradio
  lmdeploy/cli/serve.py
  lmdeploy/serve/gradio/api_server_backend.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  requirements/serve.txt
Labels: improvement

#1971 fix: set PYTHONIOENCODING to UTF-8 before start tritonserver
  lmdeploy/serve/turbomind/triton_python_backend/README.md
Labels: Bug:P2

#1889 feat: support llama2 and internlm2 on 910B
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/devices/ascend.py
  lmdeploy/pytorch/engine/devices/dipu.py
  lmdeploy/pytorch/kernels/ascend/__init__.py
  lmdeploy/pytorch/kernels/default/__init__.py
  lmdeploy/pytorch/kernels/default/multinomial_sampling.py
  lmdeploy/pytorch/kernels/dipu/__init__.py
  lmdeploy/pytorch/kernels/dipu/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/dipu/fill_kv_cache.py
  lmdeploy/pytorch/kernels/dipu/fused_rotary_emb.py
  lmdeploy/pytorch/kernels/dipu/pagedattention.py
  lmdeploy/pytorch/kernels/dipu/rms_norm.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/module_map.py
Labels: enhancement

#1977 docs: update kv quant doc
  docs/en/quantization/kv_quant.md
  docs/zh_cn/quantization/kv_quant.md
Labels: documentation

#1979 Fix internvl2-40b model export
  lmdeploy/turbomind/deploy/source_model/internvl.py
Labels: Bug:P1

#1912 refactor sampling layer setup
  src/turbomind/kernels/sampling_topp_kernels.cu
  src/turbomind/kernels/sampling_topp_kernels.h
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.h
  src/turbomind/layers/sampling_layers/CMakeLists.txt
  src/turbomind/layers/sampling_layers/TopKSamplingLayer.cc
  src/turbomind/layers/sampling_layers/TopKSamplingLayer.h
  src/turbomind/layers/sampling_layers/TopPSamplingLayer.cc
  src/turbomind/layers/sampling_layers/TopPSamplingLayer.h
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/utils/allocator.h
Labels: improvement

#1982 fix unexpected argument error when deploying "cogvlm-chat-hf"
  lmdeploy/model.py
  lmdeploy/vl/templates.py
Labels: Bug:P1

#1983 support internvl2-1b
  lmdeploy/pytorch/models/llama.py
  lmdeploy/turbomind/supported_models.py
Labels: enhancement

#1941 fix mixtral and mistral cache_position
  lmdeploy/pytorch/models/mistral.py
  lmdeploy/pytorch/models/mixtral.py
Labels: Bug:P1

#1988 docs: sync the core features in README to index.rst
  docs/en/index.rst
  docs/zh_cn/index.rst
Labels: documentation

#1998 Fix table rendering for readthedocs
  docs/en/conf.py
  docs/zh_cn/conf.py
  requirements/docs.txt
Labels: documentation

#2007 Fix the session_len assignment logic
  lmdeploy/utils.py
  tests/test_lmdeploy/test_turbomind/test_converter.py
  tests/test_lmdeploy/test_utils.py
Labels: Bug:P1

#1985 Fix logprobs openai api
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P2

#2011 feat: support llama2 and internlm2 on 910B
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/devices/ascend.py
  lmdeploy/pytorch/engine/devices/dipu.py
  lmdeploy/pytorch/kernels/ascend/__init__.py
  lmdeploy/pytorch/kernels/default/__init__.py
  lmdeploy/pytorch/kernels/default/multinomial_sampling.py
  lmdeploy/pytorch/kernels/dipu/__init__.py
  lmdeploy/pytorch/kernels/dipu/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/dipu/fill_kv_cache.py
  lmdeploy/pytorch/kernels/dipu/fused_rotary_emb.py
  lmdeploy/pytorch/kernels/dipu/pagedattention.py
  lmdeploy/pytorch/kernels/dipu/rms_norm.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/module_map.py
Labels: enhancement

#1947 Support glm 4v
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/configurations/chatglm.py
  lmdeploy/pytorch/configurations/cogvlm.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/glm_4v.py
  lmdeploy/vl/templates.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#2016 docs: fix Ada compatibility
  docs/en/quantization/w4a16.md
Labels: documentation

#2010 Add exception handler to imge encoder
  lmdeploy/messages.py
  lmdeploy/vl/engine.py
Labels: improvement

#1932 support internlm-xcomposer2d5-7b
  docs/en/multi_modal/xcomposer2d5.md
  docs/zh_cn/multi_modal/xcomposer2d5.md
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/model.py
  lmdeploy/turbomind/deploy/source_model/xcomposer2.py
  lmdeploy/turbomind/deploy/target_model/plora_w4.py
  lmdeploy/vl/model/xcomposer2.py
  lmdeploy/vl/templates.py
  lmdeploy/vl/tools/__init__.py
  lmdeploy/vl/tools/merge_xcomposer2d5_task.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#2013 add chat template for codegeex4
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#1995 Avoid the same session id for openai endpoint
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#2023 Fix internvl2-40b awq inference
  lmdeploy/turbomind/deploy/source_model/internvl.py
Labels: Bug:P1

#2033 Fix side effect of #1995
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#2037 update xcomposer2d5 docs
  docs/en/multi_modal/xcomposer2d5.md
  docs/zh_cn/multi_modal/xcomposer2d5.md
Labels: documentation

#1986 Remove the triton inference server backend "turbomind_backend"
  CMakeLists.txt
  MANIFEST.in
  README.md
  benchmark/profile_serving.py
  docs/en/benchmark/profile_triton_server.md
  docs/en/index.rst
  docs/en/inference/turbomind.md
  docs/zh_cn/benchmark/profile_triton_server.md
  docs/zh_cn/index.rst
  docs/zh_cn/inference/turbomind.md
  lmdeploy/cli/serve.py
  lmdeploy/serve/client.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/triton_server_backend.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/serve/turbomind/service_docker_up.sh
  lmdeploy/serve/turbomind/triton_models/interactive/1/placeholder
  lmdeploy/serve/turbomind/triton_models/interactive/config.pbtxt
  lmdeploy/serve/turbomind/triton_models/postprocessing/1/model.py
  lmdeploy/serve/turbomind/triton_models/postprocessing/config.pbtxt
  lmdeploy/serve/turbomind/triton_models/preprocessing/1/model.py
  lmdeploy/serve/turbomind/triton_models/preprocessing/config.pbtxt
  lmdeploy/serve/turbomind/triton_models/tokenizer/placeholder
  lmdeploy/serve/turbomind/triton_models/weights/config.ini
  lmdeploy/serve/turbomind/utils.py
  lmdeploy/turbomind/deploy/converter.py
  src/turbomind/triton_backend/CMakeLists.txt
  src/turbomind/triton_backend/libfastertransformer.cc
  src/turbomind/triton_backend/libtriton_fastertransformer.ldscript
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
  src/turbomind/triton_backend/triton_utils.hpp
Labels: improvement

#1993 Support glm4 awq
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/lite/quantization/calibration.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/glm4_awq.py
  lmdeploy/turbomind/deploy/target_model/w4.py
  lmdeploy/turbomind/supported_models.py
Labels: enhancement

#2082 Disable peer access code
  src/turbomind/utils/allocator.h
Labels: Bug:P1

#2086 set log level ERROR in benchmark scripts
  benchmark/profile_generation.py
  benchmark/profile_throughput.py
Labels: Bug:P2

#2071 raise thread exception
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#1898 Fix index error when profiling token generation with `-ct 1`
  benchmark/profile_generation.py
Labels: Bug:P1

#2097 Remove kv cache offline quantization
  lmdeploy/lite/quantization/calibration.py
  lmdeploy/lite/utils/batch_split.py
Labels: improvement

#2105 Remove `session_len` and deprecated short names of the chat templates
  lmdeploy/model.py
  lmdeploy/pytorch/chat.py
  lmdeploy/turbomind/chat.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#2108 clarify "n>1" in GenerationConfig hasn't been supported yet
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#2122 Support llama3
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/target_model/base.py
  src/turbomind/kernels/attention/array_ops.h
  src/turbomind/kernels/attention/attention_params.h
  src/turbomind/kernels/attention/attention_universal.h
  src/turbomind/kernels/attention/kv_cache_utils_v2.cu
  src/turbomind/kernels/attention/kv_cache_utils_v2.h
  src/turbomind/kernels/attention/test_attention.cu
  src/turbomind/models/llama/llama_params.h
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: enhancement

#2123 Llama3.1 prompt engineering
  docs/en/serving/api_server_tools.md
  docs/zh_cn/serving/api_server_tools.md
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#2157 [Hotfix] miss parentheses when calcuating the coef of llama3 rope
  src/turbomind/models/llama/unified_attention_layer.cc
Labels: Bug:P0

#2165 wrong expression
  README.md
Labels: documentation

#1913 PyTorch Engine AWQ support
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/pytorch/adapter/adapter.py
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/awq_modules.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/peft.py
  lmdeploy/pytorch/weight_loader/dist_utils.py
  requirements/runtime.txt
Labels: enhancement

#2111 Fix gmem to smem WAW conflict in awq gemm kernel
  src/turbomind/kernels/gemm_s_f16/cta_iterator.h
Labels: Bug:P1

#2172 Support specifying a prefix of assistant response
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#2156 Strict check for `name_map` in `InternLM2Chat7B`
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#1984 Phi3 awq
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/pytorch/configurations/builder.py
  lmdeploy/pytorch/configurations/internvl.py
  lmdeploy/pytorch/models/phi3.py
Labels: enhancement
