Repository InternLM/lmdeploy, pull requests merged in 2024-01, with the labels that each got.

#839 Perform fuzzy matching on chat template according to model path
  README.md
  README_zh-CN.md
  lmdeploy/model.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/turbomind.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#899 Improve user guide
  README.md
  README_zh-CN.md
  docs/en/_static/css/readthedocs.css
  docs/en/_static/image/lmdeploy-logo.png
  docs/en/_static/image/lmdeploy-logo.svg
  docs/en/benchmark/profile_api_server.md
  docs/en/benchmark/profile_generation.md
  docs/en/benchmark/profile_throughput.md
  docs/en/benchmark/profile_triton_server.md
  docs/en/get_started.md
  docs/en/index.rst
  docs/en/inference/load_hf.md
  docs/en/inference/pipeline.md
  docs/en/inference/pytorch.md
  docs/en/inference/turbomind.md
  docs/en/inference/turbomind_config.md
  docs/en/quantization/kv_int8.md
  docs/en/quantization/w4a16.md
  docs/en/quantization/w8a8.md
  docs/en/serving/qos.md
  docs/en/serving/restful_api.md
  docs/en/serving/serving.md
  docs/en/supported_models/codellama.md
  docs/zh_cn/_static/css/readthedocs.css
  docs/zh_cn/_static/image/lmdeploy-logo.png
  docs/zh_cn/_static/image/lmdeploy-logo.svg
  docs/zh_cn/benchmark/profile_api_server.md
  docs/zh_cn/benchmark/profile_generation.md
  docs/zh_cn/benchmark/profile_throughput.md
  docs/zh_cn/benchmark/profile_triton_server.md
  docs/zh_cn/conf.py
  docs/zh_cn/get_started.md
  docs/zh_cn/index.rst
  docs/zh_cn/inference/load_hf.md
  docs/zh_cn/inference/pipeline.md
  docs/zh_cn/inference/turbomind.md
  docs/zh_cn/inference/turbomind_config.md
  docs/zh_cn/quantization/kv_int8.md
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/quantization/w8a8.md
  docs/zh_cn/serving/qos.md
  docs/zh_cn/serving/restful_api.md
  docs/zh_cn/serving/serving.md
  docs/zh_cn/supported_models/codellama.md
  requirements/docs.txt
Labels: documentation

#902 check-in generation config
  lmdeploy/__init__.py
  lmdeploy/messages.py
  tests/test_lmdeploy/test_messages.py
Labels: planned feature

#904 Fix context decoding stuck issue when tp > 1
  src/turbomind/models/llama/LlamaBatch.cc
Labels: Bug:P1

#907 check-in ModelConfig
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: planned feature

#911 [Fix] set scaling_factor 1 forcefully when sequence length is less than max_pos_emb
  src/turbomind/models/llama/LlamaBatch.cc
Labels: Bug:P1

#914 fix pytorch llama2 with new transformers
  lmdeploy/pytorch/models/module_map.py
Labels: Bug:P1

#908 pytorch engine config
  benchmark/profile_torch_generation.py
  benchmark/profile_torch_throughput.py
  lmdeploy/pytorch/__init__.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/__init__.py
  lmdeploy/pytorch/engine/engine.py
Labels: planned feature

#909 Check-in turbomind engine config
  lmdeploy/turbomind/__init__.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/engine_config.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: planned feature

#892 register deepseek model
  lmdeploy/model.py
Labels: planned feature

#917 Remove `flash-attn` dependency of lmdeploy lite module
  docs/en/faq.md
  docs/zh_cn/faq.md
  requirements/lite.txt
Labels: improvement

#919 fix local variable 'output_ids' referenced before assignment
  lmdeploy/serve/turbomind/chatbot.py
Labels: Bug:P1

#912 Improve setup by removing pycuda dependency and adding cuda runtime and cublas to RPATH
  lmdeploy/__init__.py
  lmdeploy/pytorch/utils.py
  requirements/runtime.txt
  setup.py
  src/turbomind/python/CMakeLists.txt
Labels: improvement

#921 remove unused settings in turbomind engine config
  lmdeploy/turbomind/engine_config.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#849 [Feature]Merge `lmdeploy lite calibrate` and `lmdeploy lite auto_awq`
  docs/en/quantization/w4a16.md
  docs/zh_cn/quantization/w4a16.md
  lmdeploy/cli/lite.py
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
Labels: enhancement

#894 S-LoRA support
  benchmark/profile_torch_generation.py
  benchmark/profile_torch_throughput.py
  lmdeploy/pytorch/adapter/adapter.py
  lmdeploy/pytorch/block.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/dist_utils.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/pytorch/kernels/fill_kv_cache.py
  lmdeploy/pytorch/kernels/mbgmm.py
  lmdeploy/pytorch/kernels/mbgmv.py
  lmdeploy/pytorch/kernels/pagedattention.py
  lmdeploy/pytorch/kernels/rearange_all_gather.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/functional.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/patch.py
  lmdeploy/pytorch/models/peft.py
  lmdeploy/pytorch/paging/block_manager.py
  lmdeploy/pytorch/paging/scheduler.py
  requirements/runtime.txt
  tests/pytorch/kernel/test_mbgmm.py
  tests/pytorch/kernel/test_mbgmv.py
  tests/pytorch/kernel/test_paged_attention.py
  tests/pytorch/kernel/test_rearange_all_gather.py
Labels: planned feature

#916 Refactor LLM inference pipeline API
  README.md
  README_zh-CN.md
  benchmark/profile_generation.py
  benchmark/profile_throughput.py
  benchmark/profile_torch_generation.py
  benchmark/profile_torch_throughput.py
  docs/en/inference/pipeline.md
  docs/en/serving/qos.md
  docs/zh_cn/inference/pipeline.md
  docs/zh_cn/serving/qos.md
  lmdeploy/__init__.py
  lmdeploy/api.py
  lmdeploy/cli/serve.py
  lmdeploy/messages.py
  lmdeploy/model.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/tokenizer.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/engine_config.py
  lmdeploy/turbomind/hf_repo/modeling_lmdeploy.py
  lmdeploy/turbomind/turbomind.py
  tests/test_lmdeploy/test_model.py
Labels: planned feature

#915 Add user guide about pytorch engine
  README.md
  README_zh-CN.md
  docs/en/advance/pytorch_new_model.md
  docs/en/index.rst
  docs/en/inference/pytorch.md
  docs/zh_cn/advance/pytorch_new_model.md
  docs/zh_cn/index.rst
  docs/zh_cn/inference/pytorch.md
Labels: documentation

#928 Cleanup fixed attributes in turbomind engine config
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/turbomind/engine_config.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#918 Refactor gradio and api_server
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
Labels: planned feature

#929 fix pipeline stop_words type error
  lmdeploy/serve/async_engine.py
Labels: Bug:P1

#934 fix get_gpu_mem
  lmdeploy/pytorch/utils.py
Labels: improvement

#931 remove instance_num argument
  docs/en/inference/load_hf.md
  docs/en/inference/pipeline.md
  docs/en/serving/restful_api.md
  docs/en/supported_models/codellama.md
  docs/zh_cn/inference/load_hf.md
  docs/zh_cn/inference/pipeline.md
  docs/zh_cn/serving/restful_api.md
  docs/zh_cn/supported_models/codellama.md
  lmdeploy/api.py
  lmdeploy/cli/serve.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#925 Fix matching results of several chat templates like llama2, solar, yi and so on
  lmdeploy/model.py
  requirements/runtime.txt
  tests/test_lmdeploy/test_model.py
Labels: improvement

#887 pass stop words to openai api
  docs/en/serving/restful_api.md
  docs/zh_cn/serving/restful_api.md
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/tokenizer.py
  lmdeploy/turbomind/turbomind.py
  tests/test_lmdeploy/test_tokenizer.py
Labels: Bug:P1

#930 add pytorch random sampling
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/messages.py
Labels: improvement

#941 Fix scripts in benchmark doc
  docs/en/benchmark/profile_triton_server.md
  docs/zh_cn/benchmark/profile_generation.md
  docs/zh_cn/benchmark/profile_triton_server.md
Labels: documentation

#933 fix profile generation multiprocessing error
  benchmark/profile_generation.py
Labels: Bug:P1

#936 modify type hint of api to avoid import _turbomind
  benchmark/profile_torch_generation.py
  benchmark/profile_torch_throughput.py
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/__init__.py
  lmdeploy/api.py
  lmdeploy/messages.py
  lmdeploy/pytorch/__init__.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/__init__.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/turbomind/__init__.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/engine_config.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#946 accelerate pytorch benchmark
  benchmark/profile_torch_throughput.py
  lmdeploy/pytorch/engine/engine.py
Labels: improvement

#922 Upgrade lmdeploy cli
  .github/workflows/test.yml
  docs/en/get_started.md
  docs/en/inference/load_hf.md
  docs/en/quantization/kv_int8.md
  docs/en/quantization/w4a16.md
  docs/en/quantization/w8a8.md
  docs/en/serving/qos.md
  docs/en/serving/restful_api.md
  docs/en/serving/serving.md
  docs/en/supported_models/codellama.md
  docs/zh_cn/get_started.md
  docs/zh_cn/inference/load_hf.md
  docs/zh_cn/quantization/kv_int8.md
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/quantization/w8a8.md
  docs/zh_cn/serving/qos.md
  docs/zh_cn/serving/restful_api.md
  docs/zh_cn/serving/serving.md
  docs/zh_cn/supported_models/codellama.md
  lmdeploy/cli/__init__.py
  lmdeploy/cli/chat.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/entrypoint.py
  lmdeploy/cli/lite.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/messages.py
  lmdeploy/pytorch/chat.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/api_server_backend.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/turbomind.py
  tests/test_lmdeploy/test_cli.py
Labels: planned feature

#947 Remove `tp` from pipline argument list
  lmdeploy/api.py
Labels: improvement

#945 Update get_started and w4a16 tutorials
  README.md
  README_zh-CN.md
  docs/en/benchmark/a100_fp16.md
  docs/en/get_started.md
  docs/en/index.rst
  docs/en/inference/pipeline.md
  docs/en/quantization/w4a16.md
  docs/en/serving/serving.md
  docs/zh_cn/get_started.md
  docs/zh_cn/index.rst
  docs/zh_cn/inference/pipeline.md
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/serving/serving.md
Labels: documentation

#949 set gradio default value the same as chat.py
  lmdeploy/serve/gradio/turbomind_coupled.py
Labels: improvement

#959 fix cli with special arg names
  lmdeploy/cli/utils.py
Labels: Bug:P1

#958 set random seed when it is None
  lmdeploy/serve/async_engine.py
Labels: improvement

#956 avoid run get_logger when import lmdeploy
  lmdeploy/__init__.py
  lmdeploy/api.py
  lmdeploy/messages.py
  lmdeploy/tokenizer.py
  lmdeploy/turbomind/__init__.py
Labels: improvement

#960 fix logger in tokenizer
  lmdeploy/tokenizer.py
Labels: Bug:P1

#957 support mlp s-lora
  lmdeploy/pytorch/adapter/adapter.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/peft.py
Labels: improvement

#968 skip resume logic for pytorch backend
  lmdeploy/serve/gradio/api_server_backend.py
  lmdeploy/serve/gradio/turbomind_coupled.py
Labels: improvement

#963 Support internlm2
  .pre-commit-config.yaml
  README.md
  README_zh-CN.md
  docs/en/advance/long_context.md
  docs/en/index.rst
  docs/en/quantization/w4a16.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/advance/long_context.md
  docs/zh_cn/index.rst
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/lite/quantization/calibration.py
  lmdeploy/messages.py
  lmdeploy/model.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/fill_kv_cache.py
  lmdeploy/pytorch/modeling/convert_to_qmodules.py
  lmdeploy/pytorch/modeling/modeling_internlm2.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/passkey_retrieval.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/baichuan.py
  lmdeploy/turbomind/deploy/source_model/baichuan_awq.py
  lmdeploy/turbomind/deploy/source_model/internlm2.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/source_model/llama_awq.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
  lmdeploy/turbomind/deploy/source_model/qwen_awq.py
Labels: planned feature

#988 add guide about installation on cuda 12+ platform
  README.md
  README_zh-CN.md
  docs/en/get_started.md
  docs/zh_cn/get_started.md
Labels: documentation

#942 fix TorchEngine stuck when benchmarking with `tp>1`
  benchmark/profile_torch_generation.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/engine/request.py
Labels: Bug:P1

#977 fix module mapping error of baichuan model
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/module_map.py
Labels: Bug:P1

#985 fix import error for triton server
  lmdeploy/tokenizer.py
Labels: Bug:P1

#996 fix qwen-vl example
  examples/vl/app.py
Labels: Bug:P1

#991 hide stop word
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/paging/scheduler.py
Labels: improvement

#995 add docs for evaluation with opencompass
  docs/en/benchmark/evaluate_with_opencompass.md
  docs/en/conf.py
  docs/en/index.rst
  docs/zh_cn/benchmark/evaluate_with_opencompass.md
  docs/zh_cn/conf.py
  docs/zh_cn/index.rst
  requirements/docs.txt
Labels: documentation

#1013 fix missing init file in modules
  .github/scripts/check_lmdeploy.py
  .github/workflows/lint.yml
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/pytorch/modeling/__init__.py
  lmdeploy/turbomind/hf_repo/config.json
  lmdeploy/turbomind/hf_repo/configuration_lmdeploy.py
  lmdeploy/turbomind/hf_repo/modeling_lmdeploy.py
Labels: Bug:P1

#1034 optimize sleep
  lmdeploy/pytorch/engine/engine.py
Labels: improvement

#984 set example values to /v1/chat/completions in swagger UI
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#1039 Update adapters cli argument
  lmdeploy/cli/chat.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/lite.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
Labels: improvement

#1004 add alignment tools
  docs/en/advance/pytorch_new_model.md
  docs/zh_cn/advance/pytorch_new_model.md
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/tools/__init__.py
  lmdeploy/pytorch/tools/layout_convert.py
  lmdeploy/pytorch/tools/make_inputs.py
  tests/pytorch/tools/test_layout_convert.py
  tests/pytorch/tools/test_make_inputs.py
Labels: enhancement

#1026 update docs for kvint8
  docs/en/build.md
  docs/en/quantization/kv_int8.md
  docs/en/quantization/w4a16.md
  docs/en/serving/restful_api.md
  docs/zh_cn/build.md
  docs/zh_cn/quantization/kv_int8.md
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/serving/restful_api.md
Labels: documentation

#1017 Fix turbomind end session bug. Add huggingface demo document
  docs/en/serving/gradio.md
  docs/zh_cn/serving/gradio.md
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#1025 Support linking the custom built mpi
  CMakeLists.txt
  src/turbomind/utils/CMakeLists.txt
Labels: improvement

#1050 update indexes_containing_token function
  lmdeploy/tokenizer.py
Labels: Bug:P1

#1027 fix flash kernel on sm 70
  lmdeploy/pytorch/kernels/biased_pagedattention.py
  lmdeploy/pytorch/kernels/pagedattention.py
Labels: Bug:P1

#1042 Fix baichuan2 lora
  lmdeploy/pytorch/accel.py
  lmdeploy/pytorch/adapter/adapter.py
  lmdeploy/pytorch/kernels/alibi_pagedattention.py
  lmdeploy/pytorch/kernels/mbgmm.py
  lmdeploy/pytorch/kernels/mbgmv.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/functional.py
  lmdeploy/pytorch/models/peft.py
  tests/pytorch/kernel/test_mbgmm.py
  tests/pytorch/kernel/test_mbgmv.py
Labels: Bug:P1

#1049 [doc] Introduce project OpenAOE
  README.md
  README_zh-CN.md
  docs/en/serving/restful_api.md
  docs/zh_cn/serving/restful_api.md
Labels: documentation

#961 support min_length for turbomind backend
  lmdeploy/messages.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/kernels/sampling_penalty_kernels.cu
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.h
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
Labels: enhancement

#1052 Fix modelconfig in pytorch engine, support YI.
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/cli/cli.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P1

#1037 repetition penalty for long context
  src/turbomind/kernels/sampling_penalty_kernels.cu
  src/turbomind/kernels/sampling_penalty_kernels.h
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.h
  tests/csrc/unittests/test_penalty_kernels.cu
Labels: Bug:P1

#974 Add stream mode function to pipeline
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
Labels: enhancement

#1051 update pipeline guide and FAQ about OOM
  docs/en/faq.md
  docs/en/inference/pipeline.md
  docs/zh_cn/faq.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/messages.py
Labels: documentation

#1067 docs update cache_max_entry_count for turbomind config
  docs/en/inference/turbomind_config.md
  docs/zh_cn/inference/turbomind_config.md
Labels: documentation

#1022 Remove model name when loading hf model
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/messages.py
  lmdeploy/model.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/turbomind/utils.py
  tests/test_lmdeploy/test_get_model.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#1048 [Feature] Add api key and ssl to http server
  docs/en/serving/restful_api.md
  docs/zh_cn/serving/restful_api.md
  lmdeploy/api.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/proxy/proxy.py
Labels: enhancement

#1073 support internlm2-1_8b
  lmdeploy/model.py
Labels: improvement

#1072 [Fix] Support QLinear in rowwise_parallelize_linear_fn and colwise_parallelize_linear_fn
  lmdeploy/pytorch/dist_utils.py
Labels: Bug:P1

#1079 Update chat template for internlm2 base model
  lmdeploy/model.py
Labels: improvement

#1074 Remove caching tokenizer.json
  lmdeploy/tokenizer.py
Labels: improvement

#1064 fix and change all logger using get_logger
  benchmark/profile_hf_generation.py
  lmdeploy/legacy/pytorch/adapters/__init__.py
  lmdeploy/legacy/pytorch/adapters/base.py
  lmdeploy/legacy/pytorch/adapters/internlm.py
  lmdeploy/legacy/pytorch/adapters/llama2.py
  lmdeploy/legacy/pytorch/chat.py
  lmdeploy/legacy/pytorch/decode.py
  lmdeploy/legacy/pytorch/model.py
  lmdeploy/legacy/pytorch/session.py
  lmdeploy/legacy/pytorch/utils.py
  lmdeploy/pytorch/modeling/modeling_baichuan.py
  lmdeploy/pytorch/modeling/modeling_internlm.py
  lmdeploy/pytorch/modeling/modeling_internlm2.py
  lmdeploy/pytorch/modeling/modeling_llama.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/serve/qos_engine/inner_group_schd.py
  lmdeploy/serve/qos_engine/qos_engine.py
  lmdeploy/serve/turbomind/chatbot.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/turbomind/utils.py
  lmdeploy/utils.py
Labels: improvement

#992 Fix fast tokenizer swallows prefix space when there are too many white spaces
  benchmark/profile_throughput.py
  benchmark/profile_torch_throughput.py
  lmdeploy/pytorch/chat.py
  lmdeploy/serve/async_engine.py
  lmdeploy/tokenizer.py
  lmdeploy/turbomind/chat.py
  tests/test_lmdeploy/test_model.py
  tests/test_lmdeploy/test_tokenizer.py
Labels: Bug:P1
