Repository InternLM/lmdeploy, pull requests merged in 2024-10, with the labels that each got.

#2540 [Feature] Add argument to disable FastAPI docs
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#2559 set outlines<0.1.0
  requirements/runtime.txt
Labels: Bug:P1

#2563 support downloading models from openmind_hub
  lmdeploy/utils.py
Labels: enhancement

#2535 add check for device with cap 7.x
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/models/llama.py
  requirements/runtime.txt
  tests/pytorch/kernel/test_apply_rotary.py
  tests/pytorch/kernel/test_multinomial_sampling.py
  tests/pytorch/kernel/test_rms_norm.py
Labels: improvement

#2558 Add tool role for langchain usage
  lmdeploy/model.py
Labels: improvement

#2568 llama support tie word embedding
  lmdeploy/pytorch/models/llama.py
Labels: improvement

#2588 fix: make exit_flag verification for ascend more general
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P1

#2601 Fix spacing in README
  README.md
Labels: documentation

#2553 optimize paged attention on triton3
  .github/workflows/unit-test.yml
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/kernels/cuda/fill_kv_cache.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
  lmdeploy/pytorch/kernels/cuda/w8a8_triton_kernels.py
  requirements/runtime.txt
  tests/pytorch/kernel/test_paged_attention.py
Labels: improvement

#2619 refactor for multi backends in dlinfer
  lmdeploy/pytorch/backends/dlinfer/__init__.py
  lmdeploy/pytorch/backends/dlinfer/apply_rotary_emb.py
  lmdeploy/pytorch/backends/dlinfer/ascend/__init__.py
  lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
  lmdeploy/pytorch/backends/dlinfer/attention.py
  lmdeploy/pytorch/backends/dlinfer/moe.py
  lmdeploy/pytorch/backends/dlinfer/norm.py
  lmdeploy/pytorch/backends/dlinfer/op_backend.py
  lmdeploy/pytorch/backends/selector.py
  lmdeploy/pytorch/kernels/dlinfer/__init__.py
  lmdeploy/pytorch/kernels/dlinfer/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/dlinfer/fill_kv_cache.py
  lmdeploy/pytorch/kernels/dlinfer/fused_rotary_emb.py
  lmdeploy/pytorch/kernels/dlinfer/moe_gating_topk_softmax.py
  lmdeploy/pytorch/kernels/dlinfer/pagedattention.py
  lmdeploy/pytorch/kernels/dlinfer/rms_norm.py
Labels: improvement

#2620 Copy sglang/bench_serving.py to lmdeploy as serving benchmark script
  .github/workflows/stable.yml
  autotest/utils/benchmark_utils.py
  benchmark/README.md
  benchmark/profile_restful_api.py
  docs/en/advance/debug_turbomind.md
  docs/en/benchmark/profile_api_server.md
  docs/zh_cn/advance/debug_turbomind.md
  docs/zh_cn/benchmark/profile_api_server.md
Labels: improvement

#2560 set capture mode thread_local
  lmdeploy/pytorch/backends/cuda/graph_runner.py
Labels: Bug:P1

#2607 Add barrier to prevent TP nccl kernel waiting.
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#2613 [ascend] refactor fused_moe on ascend platform
  lmdeploy/pytorch/backends/dlinfer/moe.py
  lmdeploy/pytorch/kernels/dlinfer/__init__.py
  lmdeploy/pytorch/kernels/dlinfer/fused_moe.py
Labels: improvement

#2618 Raise an error for the wrong chat template
  lmdeploy/serve/async_engine.py
Labels: improvement

#2632 refine pre-post-process
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/logits_process.py
Labels: improvement

#2587 feat(ascend): support w4a16
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/cli/lite.py
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/pytorch/backends/dlinfer/awq_modules.py
  lmdeploy/pytorch/backends/dlinfer/op_backend.py
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/kernels/dlinfer/__init__.py
  lmdeploy/pytorch/kernels/dlinfer/awq_kernels.py
Labels: enhancement

#2626 small block_m for sm7.x
  lmdeploy/pytorch/kernels/cuda/alibi_pagedattention.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
Labels: improvement

#2615 Add distributed context in pytorch engine to support torchrun
  lmdeploy/pytorch/backends/cuda/attention.py
  lmdeploy/pytorch/distributed.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/minicpm3.py
  lmdeploy/pytorch/models/qwen2_moe.py
  lmdeploy/pytorch/nn/attention.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/nn/moe.py
  lmdeploy/pytorch/nn/utils.py
  lmdeploy/pytorch/weight_loader/model_weight_loader.py
Labels: Bug:P1

#2636 [maca] add maca backend support.
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/backends/dlinfer/__init__.py
  lmdeploy/pytorch/backends/dlinfer/maca/__init__.py
  lmdeploy/pytorch/backends/dlinfer/maca/op_backend.py
  lmdeploy/pytorch/backends/selector.py
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/utils.py
Labels: enhancement

#2605 Support mllama for pytorch engine
  docs/en/multi_modal/index.rst
  docs/en/multi_modal/mllama.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/multi_modal/index.rst
  docs/zh_cn/multi_modal/mllama.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/pytorch/backends/attention.py
  lmdeploy/pytorch/backends/cuda/attention.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/configurations/mllama.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/models/mllama.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/utils/cudagraph.py
  lmdeploy/pytorch/paging/block_manager/base_block_manager.py
  lmdeploy/pytorch/paging/block_manager/default_block_manager.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/utils.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/mllama.py
  lmdeploy/vl/templates.py
  tests/pytorch/paging/test_block_manager.py
Labels: enhancement

#2641 update check for triton
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/check_env/triton_custom_add.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
Labels: improvement

#2646 Fix error in python3.8.
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P1

#2596 Support llama3.2 LLM models in turbomind engine
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/quantization/w4a16.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/turbomind/supported_models.py
Labels: improvement

#2645 add --eager-mode to cli
  benchmark/profile_generation.py
  benchmark/profile_pipeline_api.py
  benchmark/profile_throughput.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
Labels: enhancement

#2653 Check whether device support bfloat16
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/configurations/cogvlm.py
  lmdeploy/pytorch/configurations/qwen.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/utils.py
  tests/pytorch/kernel/test_apply_rotary.py
  tests/pytorch/kernel/test_multinomial_sampling.py
  tests/pytorch/kernel/test_rms_norm.py
Labels: improvement

#2644 Align UT with triton fill_kv_cache_quant kernel
  tests/pytorch/kernel/test_fill_kv_cache.py
Labels: Bug:P1

#2655 Update get_started tutorial about deploying on ascend platform
  docs/en/get_started/ascend/get_started.md
  docs/zh_cn/get_started/ascend/get_started.md
Labels: documentation

#2654 Add warning message about `do_sample` to alert BC
  lmdeploy/api.py
  lmdeploy/serve/async_engine.py
Labels: improvement

#2647 [ascend] add ascend graph mode
  lmdeploy/pytorch/backends/dlinfer/activation.py
  lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
  lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
  lmdeploy/pytorch/backends/dlinfer/op_backend.py
  lmdeploy/pytorch/backends/dlinfer/rotary_embedding.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/kernels/dlinfer/activation.py
  lmdeploy/pytorch/kernels/dlinfer/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/dlinfer/pagedattention.py
Labels: enhancement

#2662 Update ascend get_started tutorial about installing nnal
  docs/en/get_started/ascend/get_started.md
  docs/zh_cn/get_started/ascend/get_started.md
Labels: documentation

#2663 miss device_type when checking is_bf16_supported on ascend platform
  lmdeploy/pytorch/check_env/__init__.py
Labels: Bug:P1

#2664 fix syntax in Dockerfile_aarch64_ascend
  docker/Dockerfile_aarch64_ascend
Labels: Bug:P1

#2666 Set history_cross_kv_seqlens to 0 by default
  lmdeploy/pytorch/messages.py
Labels: Bug:P1

#2667 fix build error in ascend dockerfile
  docker/Dockerfile_aarch64_ascend
Labels: Bug:P1

#2657 bugfix: llava-hf/llava-interleave-qwen-7b-hf (#2497)
  lmdeploy/vl/model/llava_hf.py
Labels: Bug:P1

#2668 fix inference mode error for qwen2-vl
  lmdeploy/pytorch/models/qwen2_vl.py
Labels: Bug:P1

#2669 fix supported model list in ascend graph mode
  docs/en/get_started/ascend/get_started.md
  docs/zh_cn/get_started/ascend/get_started.md
  lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
Labels: improvement

#2672 remove dlinfer version
  docker/Dockerfile_aarch64_ascend
Labels: improvement

#2671 Call cuda empty_cache to prevent OOM when quantizing model
  lmdeploy/lite/quantization/calibration.py
Labels: improvement
