Repository InternLM/lmdeploy, pull requests merged in 2024-03, with the labels that each got.

#1168 Fix falcon chatglm2 template
  lmdeploy/model.py
Labels: Bug:P1

#1197 Batched sampling
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/pytorch/kernels/__init__.py
  lmdeploy/pytorch/kernels/multinomial_sampling.py
  lmdeploy/pytorch/messages.py
  tests/pytorch/engine/test_logits_process.py
  tests/pytorch/kernel/test_multinomial_sampling.py
Labels: improvement

#1203 Add parameter `max_prefill_token_num`
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/messages.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#1223 optmize baichuan in pytorch engine
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/module_map.py
Labels: improvement

#1215 torch optmize chatglm3
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/chatglm2.py
Labels: improvement

#1230 Fix `None` session_len
  lmdeploy/serve/async_engine.py
Labels: Bug:P0

#1228 fix multinomial sampling
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/kernels/multinomial_sampling.py
  tests/pytorch/kernel/test_multinomial_sampling.py
Labels: Bug:P0

#1206 Async torch engine
  benchmark/profile_generation.py
  benchmark/profile_throughput.py
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/pytorch/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/qos_engine/qos_engine.py
  lmdeploy/turbomind/turbomind.py
  tests/pytorch/engine/test_request.py
Labels: enhancement

#1209 fix returning logits in prefill phase of pytorch engine
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/messages.py
Labels: Bug:P2

#1234 optimize pytorch engine inference with falcon model
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/patch.py
Labels: Bug:P1

#1211 Auto backend for pipeline and serve when backend is not set to pytorch explicitly
  .github/workflows/unit-test.yml
  lmdeploy/api.py
  lmdeploy/archs.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/serve.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/turbomind/supported_models.py
  tests/test_lmdeploy/test_auto_backend.py
Labels: enhancement

#1239 fix bf16 multinomial sampling
  lmdeploy/pytorch/kernels/multinomial_sampling.py
Labels: Bug:P0

#1237 remove unused kernel in pytorch engine
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/kernels/__init__.py
  lmdeploy/pytorch/kernels/biased_pagedattention.py
  lmdeploy/pytorch/kernels/flashattention_nopad.py
  tests/pytorch/kernel/test_paged_attention.py
Labels: improvement

#1240 reduce torchengine prefill mem usage
  lmdeploy/pytorch/engine/engine.py
Labels: Bug:P2

#1245 fix config for readthedocs
  docs/en/.readthedocs.yaml
  docs/zh_cn/.readthedocs.yaml
Labels: documentation

#1243 update badges in README
  .github/md-link-config.json
  README.md
  README_zh-CN.md
Labels: documentation

#1238 Hide qos functions from swagger UI if not applied
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#1248 Update serving guide including api_server and gradio
  .github/md-link-config.json
  README.md
  README_zh-CN.md
  docs/en/get_started.md
  docs/en/index.rst
  docs/en/serving/gradio.md
  docs/en/serving/restful_api.md
  docs/zh_cn/get_started.md
  docs/zh_cn/index.rst
  docs/zh_cn/serving/gradio.md
  docs/zh_cn/serving/restful_api.md
Labels: documentation

#1246 fix different stop/bad words length in batch
  src/turbomind/models/llama/LlamaBatch.cc
Labels: Bug:P1

#1256 rm unused var
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
Labels: improvement

#1247 Color log formatter
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/pytorch/models/patch.py
  lmdeploy/pytorch/paging/scheduler.py
  lmdeploy/utils.py
Labels: improvement

#1258 Add tensor core GQA dispatch for `[4,5,6,8]`
  src/turbomind/kernels/attention/attention_universal.h
  src/turbomind/kernels/attention/decoding.cu
  src/turbomind/kernels/attention/decoding_128_bf16_sm80.cu
  src/turbomind/kernels/attention/decoding_128_f16_sm80.cu
  src/turbomind/kernels/attention/decoding_config.h
  src/turbomind/kernels/attention/decoding_sm80.h
Labels: enhancement, turbomind

#1251 optimize filling kv cache kernel in pytorch engine
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/fill_kv_cache.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/functional.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/internlm.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/mistral.py
  lmdeploy/pytorch/models/mixtral.py
  lmdeploy/pytorch/models/peft.py
  lmdeploy/pytorch/models/qwen2.py
  tests/pytorch/kernel/test_fill_kv_cache.py
Labels: improvement

#1253 lazy load convert_pv jit function
  lmdeploy/pytorch/kernels/pagedattention.py
Labels: Bug:P3

#1216 Refactor chat template and support accurate name matching.
  examples/vl/qwen_model.py
  examples/vl/xcomposer_model.py
  lmdeploy/cli/cli.py
  lmdeploy/model.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/utils.py
  requirements/readthedocs.txt
  requirements/runtime.txt
  tests/test_lmdeploy/test_async_engine.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#1277 [BUG] fix the case when num_used_blocks < 0
  lmdeploy/pytorch/paging/block_manager/window_block_manager.py
Labels: Bug:P2

#1200 Support passing json file to chat template
  docs/en/advance/chat_template.md
  docs/en/index.rst
  docs/en/inference/pipeline.md
  docs/en/serving/restful_api.md
  docs/zh_cn/advance/chat_template.md
  docs/zh_cn/index.rst
  docs/zh_cn/inference/pipeline.md
  docs/zh_cn/serving/restful_api.md
  examples/vl/qwen_model.py
  examples/vl/xcomposer_model.py
  lmdeploy/cli/chat.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#1270 Check bf16 model in torch engine
  lmdeploy/pytorch/check_env/__init__.py
Labels: Bug:P2

#1281 fix bf16 check
  lmdeploy/pytorch/check_env/__init__.py
Labels: Bug:P1

#1278 [Fix] fix triton server chatbot init error
  benchmark/profile_serving.py
  lmdeploy/serve/turbomind/chatbot.py
Labels: Bug:P1

#1282 Fix concatenate issue in profile serving
  benchmark/profile_serving.py
  lmdeploy/serve/turbomind/chatbot.py
Labels: Bug:P2

#1272 better cache allocation in pytorch engine
  lmdeploy/messages.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/utils.py
Labels: improvement

#1214 Add inference pipeline for VL models
  docs/en/index.rst
  docs/en/inference/vl_pipeline.md
  docs/zh_cn/index.rst
  docs/zh_cn/inference/vl_pipeline.md
  lmdeploy/api.py
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/tokenizer.py
  lmdeploy/turbomind/utils.py
  lmdeploy/utils.py
  lmdeploy/vl/__init__.py
  lmdeploy/vl/constants.py
  lmdeploy/vl/engine.py
  lmdeploy/vl/model/__init__.py
  lmdeploy/vl/model/base.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/llava.py
  lmdeploy/vl/model/qwen.py
  lmdeploy/vl/model/utils.py
  lmdeploy/vl/model/yi.py
  lmdeploy/vl/templates.py
  lmdeploy/vl/utils.py
  requirements/runtime.txt
  tests/test_lmdeploy/test_tokenizer.py
  tests/test_lmdeploy/test_vl_template.py
Labels: enhancement

#1287 rename restful_api.md to api_server.md
  README.md
  README_zh-CN.md
  docs/en/benchmark/profile_api_server.md
  docs/en/index.rst
  docs/en/quantization/w4a16.md
  docs/en/serving/api_server.md
  docs/en/supported_models/codellama.md
  docs/zh_cn/benchmark/profile_api_server.md
  docs/zh_cn/index.rst
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/serving/api_server.md
  docs/zh_cn/supported_models/codellama.md
Labels: documentation

#1288 Update readthedocs index
  README.md
  README_zh-CN.md
  docs/en/get_started.md
  docs/en/index.rst
  docs/zh_cn/get_started.md
  docs/zh_cn/index.rst
  requirements/readthedocs.txt
Labels: documentation

#1285 Support serving VLMs
  docs/en/index.rst
  docs/en/serving/api_server.md
  docs/en/serving/api_server_vl.md
  docs/zh_cn/index.rst
  docs/zh_cn/serving/api_server.md
  docs/zh_cn/serving/api_server_vl.md
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/vl/templates.py
Labels: enhancement

#1294 Fall back to base template if there is no chat_template in tokenizer_config.json
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#1293 Serve VLM by gradio
  lmdeploy/cli/serve.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/vl.py
Labels: enhancement

#1292 Add pipeline.chat api for easy use
  docs/en/inference/vl_pipeline.md
  docs/zh_cn/inference/vl_pipeline.md
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/vl_async_engine.py
Labels: enhancement

#1300 fix torch tp lora adapter
  lmdeploy/pytorch/models/peft.py
Labels: Bug:P1

#1304 Fix crash when api_server loads a turbomind model
  lmdeploy/archs.py
Labels: Bug:P1

#1286 Support slora to pipeline
  lmdeploy/cli/serve.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: enhancement

#1295 Fix performance issue of chatbot
  benchmark/profile_serving.py
  lmdeploy/serve/turbomind/chatbot.py
Labels: Bug:P1

#1310 add chat template for deepseek coder model
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#1265 Support qwen for pytorch engine
  .github/scripts/eval_opencompass_config.py
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/qwen.py
  lmdeploy/pytorch/supported_models.py
  tests/test_lmdeploy/test_auto_backend.py
Labels: enhancement

#1317 add missed argument
  lmdeploy/serve/gradio/vl.py
  lmdeploy/serve/vl_async_engine.py
Labels: Bug:P1

#1323 Add more log info for api_server
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/utils.py
Labels: improvement

#1325 remove cuda cache after loading vison model
  lmdeploy/vl/engine.py
  lmdeploy/vl/model/llava.py
  lmdeploy/vl/model/qwen.py
Labels: improvement

#1276 Add new chat cli with auto backend feature
  docs/en/faq.md
  docs/en/get_started.md
  docs/en/inference/load_hf.md
  docs/en/quantization/kv_int8.md
  docs/en/quantization/w4a16.md
  docs/en/quantization/w8a8.md
  docs/en/supported_models/codellama.md
  docs/zh_cn/faq.md
  docs/zh_cn/get_started.md
  docs/zh_cn/inference/load_hf.md
  docs/zh_cn/quantization/kv_int8.md
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/quantization/w8a8.md
  docs/zh_cn/supported_models/codellama.md
  lmdeploy/archs.py
  lmdeploy/cli/chat.py
  lmdeploy/cli/cli.py
  lmdeploy/cli/entrypoint.py
  lmdeploy/cli/utils.py
Labels: improvement

#1344 Fix dlpack memory leak
  src/turbomind/python/bind.cpp
Labels: Bug:P0

#1354 Fix invalid context for Internstudio platform
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h
Labels: Bug:P1

#1349 fix benchmark generation
  benchmark/profile_generation.py
  lmdeploy/pytorch/engine/engine.py
Labels: Bug:P1

#1341 fix window attention
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/pagedattention.py
  lmdeploy/pytorch/tools/make_inputs.py
  tests/pytorch/tools/test_make_inputs.py
Labels: Bug:P1

#1358 fix batchApplyRepetitionPenalty
  src/turbomind/kernels/sampling_penalty_kernels.cu
Labels: Bug:P1

#1361 Fix memory leak of DLManagedTensor
  src/turbomind/python/bind.cpp
Labels: Bug:P1

#1351 Update rewritings for qwen
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/qwen.py
Labels: improvement

#1329 Support Triton inference server python backend
  .github/scripts/check_lmdeploy.py
  benchmark/profile_triton_python_backend.py
  lmdeploy/serve/turbomind/triton_python_backend/README.md
  lmdeploy/serve/turbomind/triton_python_backend/client.py
  lmdeploy/serve/turbomind/triton_python_backend/config.pbtxt
  lmdeploy/serve/turbomind/triton_python_backend/model.py
Labels: enhancement

#1359 lazy import accelerate.init_empty_weights for vl async engine
  lmdeploy/vl/model/qwen.py
Labels: improvement

#1368 update lmdeploy pypi packages deps to cuda12
  .github/workflows/cuda11.8-whl-release.yml
  .github/workflows/pypi.yml
  setup.py
  src/turbomind/python/CMakeLists.txt
Labels: improvement

#1336 fix vlm inference with tp
  lmdeploy/turbomind/turbomind.py
  lmdeploy/vl/engine.py
  lmdeploy/vl/model/llava.py
  lmdeploy/vl/model/qwen.py
  lmdeploy/vl/model/yi.py
Labels: Bug:P1
