Repository InternLM/lmdeploy, pull requests merged in 2024-04, with the labels that each got.

#1367 torch engine support dbrx
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/dbrx.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/patch.py
  lmdeploy/pytorch/supported_models.py
  requirements/runtime.txt
Labels: enhancement

#1373 update `max_prefill_token_num` for low gpu memory
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#1372 Support qwen2 moe for pytorch engine
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/qwen2_moe.py
  lmdeploy/pytorch/supported_models.py
Labels: enhancement

#1343 Add slora example for pipeline
  docs/en/inference/pipeline.md
  docs/zh_cn/inference/pipeline.md
  lmdeploy/serve/async_engine.py
Labels: documentation

#1328 Optimize pipeline of pytorch engine
  benchmark/profile_throughput.py
  lmdeploy/pytorch/block.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/__init__.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/pagedattention.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/paging/block_manager/base_block_manager.py
  lmdeploy/pytorch/paging/block_manager/default_block_manager.py
  lmdeploy/pytorch/paging/block_manager/window_block_manager.py
  lmdeploy/pytorch/paging/scheduler.py
  lmdeploy/pytorch/tools/make_inputs.py
  tests/pytorch/paging/test_block_manager.py
  tests/pytorch/paging/test_scheduler.py
  tests/pytorch/tools/test_make_inputs.py
Labels: enhancement

#1335 Add deepseek vl
  README.md
  README_zh-CN.md
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/deepseek_vl.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/turbomind/utils.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/templates.py
Labels: enhancement

#1383 Reduce binary size, add `sm_89` and `sm_90` targets
  CMakeLists.txt
  src/turbomind/kernels/CMakeLists.txt
  src/turbomind/kernels/activation_kernels.cu
  src/turbomind/kernels/ban_bad_words.cu
  src/turbomind/kernels/bert_preprocess_kernels.cu
  src/turbomind/kernels/bert_preprocess_kernels.h
  src/turbomind/kernels/decoding_kernels.cu
  src/turbomind/kernels/flash_attention/flash_attention.cu
  src/turbomind/kernels/flash_attention/flash_attention2/flash_api.cpp
  src/turbomind/kernels/flash_attention/fused_multi_head_attention/llama_flash_attention_kernel.cu
  src/turbomind/kernels/gemm_s_f16/gemm_template.h
  src/turbomind/kernels/gpt_kernels.cu
  src/turbomind/kernels/sampling_penalty_kernels.cu
  src/turbomind/kernels/sampling_topk_kernels.cu
  src/turbomind/kernels/sampling_topp_kernels.cu
  src/turbomind/kernels/unfused_attention_kernels.cu
  src/turbomind/layers/DynamicDecodeLayer.cc
  src/turbomind/layers/FfnLayer.cc
  src/turbomind/layers/FfnLayer.h
  src/turbomind/layers/FfnWeight.h
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc
  src/turbomind/layers/sampling_layers/TopKSamplingLayer.cu
  src/turbomind/layers/sampling_layers/TopPSamplingLayer.cu
  src/turbomind/models/llama/CMakeLists.txt
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDenseWeight.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/llama_decoder_kernels.cu
  src/turbomind/models/llama/llama_gemm.cc
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/models/llama/unified_decoder.cc
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/libfastertransformer.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
  src/turbomind/utils/cublasMMWrapper.h
  tests/csrc/unittests/CMakeLists.txt
  tests/csrc/unittests/gtest_utils.h
  tests/csrc/unittests/test_attention_kernels.cu
  tests/csrc/unittests/test_context_attention_layer.cu
  tests/csrc/unittests/test_gpt_kernels.cu
  tests/csrc/unittests/test_penalty_kernels.cu
  tests/csrc/unittests/test_sampling_kernels.cu
  tests/csrc/unittests/test_sampling_layer.cu
Labels: improvement, turbomind

#1352 Use new event loop instead of the current loop for pipeline
  lmdeploy/archs.py
  lmdeploy/serve/async_engine.py
Labels: Bug:P2, improvement

#1397 Optimize inference of pytorch engine with tensor parallelism
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/tools/make_inputs.py
  tests/pytorch/tools/test_make_inputs.py
Labels: improvement

#1389 handle SIGTERM
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P1

#1400 Add model name corresponding to the test data in the doc
  docs/en/benchmark/a100_fp16.md
Labels: documentation

#1411 fix typo in get_started guide
  docs/en/get_started.md
  docs/zh_cn/get_started.md
Labels: documentation

#1406 Support qwen1.5 in turbomind engine
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/turbomind/utils.py
  tests/test_lmdeploy/test_auto_backend.py
  tests/test_lmdeploy/test_get_model.py
Labels: enhancement

#1414 Fix llama_triton_example
  examples/cpp/llama/llama_triton_example.cc
Labels: Bug:P2

#1408 add llava-v1.6-34b template
  lmdeploy/model.py
  lmdeploy/vl/model/llava.py
Labels: improvement

#1420 miss --trust-remote-code in converter, which is side effect brought by pr #1406
  .github/workflows/daily_ete_test.yml
  autotest/tools/convert/test_convert.py
  docs/en/benchmark/profile_triton_server.md
  docs/zh_cn/benchmark/profile_triton_server.md
  lmdeploy/cli/cli.py
  lmdeploy/turbomind/deploy/converter.py
Labels: Bug:P1

#1409 Add async openai demo for api_server
  docs/en/serving/api_server.md
  docs/zh_cn/serving/api_server.md
Labels: documentation

#1417 fix sampling kernel
  lmdeploy/pytorch/kernels/multinomial_sampling.py
  tests/pytorch/kernel/test_multinomial_sampling.py
Labels: Bug:P1

#1427 Fix loading single safetensor file error
  lmdeploy/vl/model/utils.py
Labels: Bug:P1

#1430 Support qwen1.5-*-AWQ model inference in turbomind
  lmdeploy/turbomind/deploy/source_model/qwen_awq.py
Labels: enhancement

#1425 support Internvl chat v1.1, v1.2 and v1.2-plus
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/internvl.py
  lmdeploy/vl/templates.py
  src/turbomind/models/llama/LlamaWeight.cc
Labels: enhancement

#1434 Initialize vl encoder first to avoid OOM
  lmdeploy/serve/vl_async_engine.py
Labels: improvement

#1403 Support model_name customization for api_server
  lmdeploy/cli/serve.py
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
Labels: improvement

#1436 add the recommendation version for Python Backend
  lmdeploy/serve/turbomind/triton_python_backend/README.md
Labels: documentation

#1412 Update kv quantization and inference guide
  README.md
  README_zh-CN.md
  docs/en/get_started.md
  docs/en/index.rst
  docs/en/inference/turbomind_config.md
  docs/en/quantization/kv_int8.md
  docs/en/quantization/kv_quant.md
  docs/en/quantization/w4a16.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/get_started.md
  docs/zh_cn/index.rst
  docs/zh_cn/inference/turbomind_config.md
  docs/zh_cn/quantization/kv_int8.md
  docs/zh_cn/quantization/kv_quant.md
  docs/zh_cn/quantization/w4a16.md
  docs/zh_cn/supported_models/supported_models.md
Labels: documentation

#1433 Expose dynamic split&fuse parameters
  benchmark/profile_throughput.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#1426 support Internvl chat llava
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/internvl_llava.py
  lmdeploy/vl/model/utils.py
  lmdeploy/vl/model/yi.py
Labels: enhancement

#1441 remove space in deepseek template
  lmdeploy/model.py
Labels: Bug:P1

#1453 warning transformers version
  lmdeploy/pytorch/check_env/__init__.py
  requirements/runtime.txt
Labels: improvement

#1462 update doc for llama3
  README.md
  autotest/utils/get_run_config.py
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
Labels: documentation

#1438 Support mini gemini llama
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/model/mini_gemeni.py
  lmdeploy/vl/model/utils.py
  lmdeploy/vl/model/yi.py
  lmdeploy/vl/templates.py
Labels: enhancement

#1444 add interactive api in service for VL models
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: enhancement

#1457 Optimize apply_rotary kernel and remove useless inference_mode
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/pytorch/kernels/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/fill_kv_cache.py
  lmdeploy/pytorch/kernels/mbgmm.py
  lmdeploy/pytorch/kernels/mbgmv.py
  lmdeploy/pytorch/kernels/pagedattention.py
  lmdeploy/pytorch/kernels/rms_norm.py
  lmdeploy/pytorch/models/internlm2.py
Labels: improvement

#1465 set infinity timeout to nccl
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#1391 support output logprobs with turbomind backend.
  CMakeLists.txt
  benchmark/profile_generation.py
  benchmark/profile_throughput.py
  examples/vl/app.py
  lmdeploy/messages.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/vl.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/kernels/sampling_topk_kernels.cu
  src/turbomind/kernels/sampling_topk_kernels.h
  src/turbomind/kernels/sampling_topp_kernels.cu
  src/turbomind/kernels/sampling_topp_kernels.h
  src/turbomind/layers/DynamicDecodeLayer.cc
  src/turbomind/layers/sampling_layers/TopKSamplingLayer.cu
  src/turbomind/layers/sampling_layers/TopPSamplingLayer.cu
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h
  src/turbomind/utils/constant.h
  tests/csrc/unittests/test_sampling_kernels.cu
Labels: enhancement

#1467 fix free repetition_penalty_workspace_ buffer
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.h
Labels: Bug:P3

#1456 Feat: format internlm2 chat template
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#1458 support internlm-xcomposer2-7b & internlm-xcomposer2-4khd-7b
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/xomposer2.py
  lmdeploy/turbomind/deploy/target_model/__init__.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/deploy/target_model/plora.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/utils.py
  lmdeploy/vl/model/xcomposer2.py
  lmdeploy/vl/templates.py
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDecoderLayerWeight.h
  src/turbomind/models/llama/LlamaDenseWeight.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaFfnLayer.h
  src/turbomind/models/llama/LlamaLinear.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/LlamaWeight.h
  src/turbomind/models/llama/llama_decoder_kernels.cu
  src/turbomind/models/llama/llama_decoder_kernels.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/models/llama/unified_attention_layer.h
  src/turbomind/models/llama/unified_decoder.cc
  src/turbomind/models/llama/unified_decoder.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
  tests/test_lmdeploy/test_auto_backend.py
Labels: enhancement

#1470 Add qwen1.5 awq quantization
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/lite/quantization/calibration.py
Labels: enhancement

#1473 get model in advance to fix downloading from modelscope error
  lmdeploy/api.py
  lmdeploy/cli/entrypoint.py
Labels: Bug:P1

#1480 Fix the side effect in engine_intance brought by #1391
  lmdeploy/pytorch/engine/engine_instance.py
Labels: Bug:P0

#1428 Add colab demo
  README.md
  README_zh-CN.md
Labels: enhancement

#1468 support starcoder2
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/starcoder2.py
  lmdeploy/pytorch/supported_models.py
Labels: enhancement

#1513 fix local variable 'response' referenced before assignment in async_engine.generate
  lmdeploy/serve/async_engine.py
Labels: Bug:P1

#1491 variable `CTA_H` & fix qkv bias
  src/turbomind/kernels/attention/CMakeLists.txt
  src/turbomind/kernels/attention/attention_params.h
  src/turbomind/kernels/attention/attention_template.h
  src/turbomind/kernels/attention/attention_universal.h
  src/turbomind/kernels/attention/codegen/decoding_sm75_128_f16_f16.cu
  src/turbomind/kernels/attention/codegen/decoding_sm75_128_f16_u4.cu
  src/turbomind/kernels/attention/codegen/decoding_sm75_128_f16_u8.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_128_bf16_bf16.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_128_bf16_u4.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_128_bf16_u8.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_128_f16_f16.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_128_f16_u4.cu
  src/turbomind/kernels/attention/codegen/decoding_sm80_128_f16_u8.cu
  src/turbomind/kernels/attention/cta_map.h
  src/turbomind/kernels/attention/decoding.cu
  src/turbomind/kernels/attention/decoding_config.h
  src/turbomind/kernels/attention/decoding_template.h
  src/turbomind/kernels/attention/kv_cache_utils_v2.cu
  src/turbomind/kernels/attention/kv_cache_utils_v2.h
  src/turbomind/kernels/attention/linear_iterator.h
  src/turbomind/kernels/attention/reduce.cu
  src/turbomind/kernels/attention/reduce.h
  src/turbomind/kernels/attention/reduce_kernel.h
  src/turbomind/kernels/attention/reduce_template.h
  src/turbomind/kernels/attention/reference.cu
  src/turbomind/kernels/attention/reference.h
  src/turbomind/kernels/attention/test_attention.cu
Labels: Bug:P1, improvement, turbomind

#1490 support OpenGVLab/InternVL-Chat-V1-5
  README.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/turbomind/deploy/source_model/internlm2.py
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/vl/model/internvl.py
Labels: enhancement

#1523 Fix typo in w8a8.md
  docs/zh_cn/quantization/w8a8.md
Labels: documentation

#1508 complete build.md
  docs/en/build.md
  docs/zh_cn/build.md
Labels: documentation

#1529 update readme wechat qrcode
  README.md
  README_zh-CN.md
Labels: documentation

#1531 fix installation requirements for windows
  requirements/runtime.txt
Labels: improvement
