Repository InternLM/lmdeploy, pull requests merged in 2024-12, with the labels that each got.

#2830 add openssh-server installation in dockerfile
  docker/Dockerfile
Labels: improvement

#2836 Add version restrictions in runtime_ascend.txt to ensure functionality
  requirements/runtime_ascend.txt
Labels: improvement

#2842 Fix gemma2 accuracy through the correct softcapping logic
  lmdeploy/pytorch/kernels/cuda/flashattention.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
  lmdeploy/pytorch/models/gemma.py
Labels: Bug:P1

#2814 better kv allocate
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#2826 profile throughput without new threads
  benchmark/profile_throughput.py
  lmdeploy/pytorch/backends/cuda/attention.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/cuda/activation.py
  lmdeploy/pytorch/kernels/cuda/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/cuda/fill_kv_cache.py
  lmdeploy/pytorch/models/utils/cudagraph.py
  tests/pytorch/engine/test_logits_process.py
Labels: improvement

#2844 fix the logic to verify whether AutoAWQ has been successfully installed
  lmdeploy/pytorch/backends/cuda/awq_modules.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
Labels: Bug:P1

#2847 [dlinfer] change dlinfer kv_cache layout and ajust paged_prefill_attention api.
  lmdeploy/pytorch/backends/dlinfer/maca/op_backend.py
  lmdeploy/pytorch/kernels/dlinfer/pagedattention.py
Labels: improvement

#2850 Supports W8A8 quantization for more models
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/pytorch/modeling/__init__.py
  lmdeploy/pytorch/modeling/convert_to_qmodules.py
  lmdeploy/pytorch/modeling/modeling_baichuan.py
  lmdeploy/pytorch/modeling/modeling_internlm.py
  lmdeploy/pytorch/modeling/modeling_internlm2.py
  lmdeploy/pytorch/modeling/modeling_llama.py
Labels: improvement

#2853 [ascend] convert kv cache to nd format in ascend graph mode
  lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
Labels: Bug:P1

#2736 [ascend]feat: support kv int8
  docs/en/get_started/ascend/get_started.md
  docs/zh_cn/get_started/ascend/get_started.md
  lmdeploy/messages.py
  lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
  lmdeploy/pytorch/backends/dlinfer/attention.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/dlinfer/fill_kv_cache.py
  lmdeploy/pytorch/kernels/dlinfer/pagedattention.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/tools/make_inputs.py
Labels: enhancement

#2849 update supported models
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
Labels: documentation

#2860 [Feature] Support for loading lora adapter weights in safetensors format
  lmdeploy/pytorch/models/patch.py
Labels: Bug:P1

#2881 fix cpu cache
  lmdeploy/pytorch/engine/cache_engine.py
Labels: Bug:P1

#2870 refactor PyTorchEngine check env
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/check_env/adapter.py
  lmdeploy/pytorch/check_env/base.py
  lmdeploy/pytorch/check_env/deeplink.py
  lmdeploy/pytorch/check_env/model.py
  lmdeploy/pytorch/check_env/torch.py
  lmdeploy/pytorch/check_env/transformers.py
  lmdeploy/pytorch/check_env/triton.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_checker.py
  requirements/runtime.txt
Labels: improvement

#2888 Fix args type in docstring
  lmdeploy/serve/async_engine.py
Labels: Bug:P2

#2862 Fix llama3.1 chat template
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: Bug:P2

#2893 [dlinfer] only compile the language model in vl models
  lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
Labels: improvement

#2889 Optimize tp broadcast
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/multimodal/data_type.py
Labels: improvement

#2906 unfeeze torch version in dockerfile
  docker/Dockerfile
Labels: improvement

#2916 Fix typo
  lmdeploy/serve/vl_async_engine.py
Labels: Bug:P2

#2872 support tp > n_kv_heads for pt models
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/configurations/builder.py
  lmdeploy/pytorch/configurations/chatglm.py
  lmdeploy/pytorch/configurations/cogvlm.py
  lmdeploy/pytorch/configurations/dbrx.py
  lmdeploy/pytorch/configurations/deepseek_v2.py
  lmdeploy/pytorch/configurations/default.py
  lmdeploy/pytorch/configurations/falcon.py
  lmdeploy/pytorch/configurations/gemma.py
  lmdeploy/pytorch/configurations/internvl.py
  lmdeploy/pytorch/configurations/llava_hf.py
  lmdeploy/pytorch/configurations/minicpm3.py
  lmdeploy/pytorch/configurations/mllama.py
  lmdeploy/pytorch/configurations/qwen.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/internlm.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/minicpmv26.py
  lmdeploy/pytorch/models/qwen2.py
  lmdeploy/pytorch/nn/attention.py
  lmdeploy/pytorch/nn/linear.py
Labels: improvement

#2874 replicate kv for some models when tp is divisble by kv_head_num
  lmdeploy/turbomind/deploy/module.py
  lmdeploy/turbomind/deploy/target_model/base.py
Labels: improvement

#2928 fix: Incorrect stats size during inference of throughput benchmark when concurrency > num_prompts
  benchmark/profile_throughput.py
Labels: Bug:P1

#2912 fix lora name and rearange wqkv for internlm2
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/internvl.py
  lmdeploy/pytorch/models/patch.py
  requirements/runtime_ascend.txt
  requirements/runtime_cuda.txt
Labels: Bug:P1

#2917 [dlinfer] fix moe op for dlinfer.
  lmdeploy/pytorch/backends/dlinfer/moe.py
  lmdeploy/pytorch/kernels/dlinfer/fused_moe.py
Labels: Bug:P1

#2914 [side effect] fix vlm quant failed
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/vl/model/base.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/model/internvl.py
  lmdeploy/vl/model/internvl_llava.py
  lmdeploy/vl/model/llava.py
  lmdeploy/vl/model/llava_hf.py
  lmdeploy/vl/model/llava_next.py
  lmdeploy/vl/model/mini_gemeni.py
  lmdeploy/vl/model/minicpmv.py
  lmdeploy/vl/model/molmo.py
  lmdeploy/vl/model/qwen.py
  lmdeploy/vl/model/xcomposer2.py
  lmdeploy/vl/model/yi.py
Labels: Bug:P1

#2933 fix torch_dtype
  lmdeploy/pytorch/config.py
Labels: Bug:P1

#2930 support unaligned qkv heads
  lmdeploy/pytorch/models/internvl.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/nn/utils.py
Labels: Bug:P1

#2947 fix mllama inference without image
  .github/workflows/unit-test.yml
  lmdeploy/pytorch/models/mllama.py
Labels: Bug:P1

#2898 Support torch_dtype modification and update FAQs for AWQ quantization
  .github/workflows/unit-test.yml
  docs/en/quantization/w4a16.md
  docs/zh_cn/quantization/w4a16.md
  lmdeploy/cli/lite.py
  lmdeploy/cli/utils.py
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/gptq.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/lite/quantization/calibration.py
  lmdeploy/lite/utils/load.py
Labels: Bug:P1

#2901 Fix exception handler for proxy server
  lmdeploy/cli/serve.py
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/proxy/constants.py
  lmdeploy/serve/proxy/proxy.py
  lmdeploy/turbomind/deploy/converter.py
Labels: Bug:P1

#2953 Fallback to pytorch engine when the model is quantized by smooth quant
  autotest/utils/config_utils.py
  lmdeploy/archs.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/supported_models.py
Labels: improvement

#2952 [dlinfer] feat: add DlinferFlashAttention to support qwen vl.
  lmdeploy/pytorch/backends/dlinfer/flash_attention.py
  lmdeploy/pytorch/backends/dlinfer/op_backend.py
  lmdeploy/pytorch/kernels/dlinfer/__init__.py
  lmdeploy/pytorch/kernels/dlinfer/flash_attention.py
Labels: enhancement

#2956 Fix torch_dtype in lite
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/utils/load.py
Labels: Bug:P1

#2402 Torchrun launching multiple api_server
  docs/en/llm/api_server.md
  docs/zh_cn/llm/api_server.md
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#2954 [side-effect] bring back quantization of qwen2-vl, glm4v and etc.
  lmdeploy/archs.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/cogvlm.py
  lmdeploy/vl/model/glm_4v.py
  lmdeploy/vl/model/mllama.py
  lmdeploy/vl/model/phi3_vision.py
  lmdeploy/vl/model/qwen2.py
Labels: Bug:P1

#2970 add a thread pool executor to control the vl engine traffic
  lmdeploy/vl/engine.py
Labels: Bug:P1

#2976 [side-effect] fix gradio demo error
  lmdeploy/serve/gradio/vl.py
Labels: Bug:P1

#2965 Optimize awq kernel in pytorch engine
  .github/workflows/benchmark.yml
  .github/workflows/daily_ete_test.yml
  .github/workflows/daily_ete_test_v100.yml
  lmdeploy/pytorch/backends/cuda/awq_modules.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/check_env/model.py
  lmdeploy/pytorch/kernels/cuda/awq_kernels.py
Labels: improvement
