Repository InternLM/lmdeploy, pull requests merged in 2024-09, with the labels that each got.

#2410 fix get_started user guide unaccessible
  README.md
  README_ja.md
  README_zh-CN.md
Labels: documentation

#2375 support do_sample parameter
  benchmark/profile_generation.py
  benchmark/profile_throughput.py
  lmdeploy/__init__.py
  lmdeploy/messages.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/passkey_retrieval.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/vl.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/turbomind.py
  tests/test_lmdeploy/test_messages.py
Labels: improvement

#2364 refactor TurbomindModelConfig
  .github/workflows/pr_ete_test.yml
  3rdparty/INIReader.h
  CMakeLists.txt
  autotest/interface/pipeline/test_pipeline_longtext_func.py
  examples/cpp/llama/llama_config.ini
  examples/cpp/llama/llama_config.yaml
  examples/cpp/llama/llama_triton_example.cc
  lmdeploy/archs.py
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/deploy/config.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/exporter.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/deploy/target_model/fp.py
  lmdeploy/turbomind/generate_gemm_config.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/triton_backend/llama/CMakeLists.txt
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/utils/cuda_utils.cc
  src/turbomind/utils/cuda_utils.h
  tests/test_lmdeploy/test_async_engine.py
  tests/test_lmdeploy/test_turbomind/test_converter.py
  tests/test_lmdeploy/test_utils.py
Labels: improvement

#1856 Support guided decoding for pytorch backend
  docs/en/advance/structed_output.md
  docs/en/index.rst
  docs/zh_cn/advance/structed_output.md
  docs/zh_cn/index.rst
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/guided_process.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/messages.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  requirements/runtime.txt
Labels: enhancement

#2413 import dlinfer before imageencoding
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/serve/vl_async_engine.py
Labels: improvement

#2417 add Ascend get_started
  .pre-commit-config.yaml
  docs/en/get_started/ascend/get_started.md
  docs/zh_cn/get_started/ascend/get_started.md
Labels: documentation

#2426 ignore *.pth when download model from model hub
  lmdeploy/utils.py
Labels: improvement

#2427 inplace logits process as default
  lmdeploy/pytorch/engine/logits_process.py
  tests/pytorch/engine/test_logits_process.py
Labels: improvement

#2312 handle invalid images
  lmdeploy/vl/templates.py
  lmdeploy/vl/utils.py
  tests/test_lmdeploy/test_vl_encode.py
Labels: improvement

#2252 Split token_embs and lm_head weights
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/utils/memory_utils.cu
  src/turbomind/utils/memory_utils.h
Labels: improvement

#2421 build: update ascend dockerfile
  docker/Dockerfile_aarch64_ascend
Labels: improvement

#2433 build nccl in dockerfile for cuda11.8
  docker/Dockerfile
Labels: improvement

#2428 Fix some issues encountered by modelscope and community
  docs/en/multi_modal/internvl.md
  docs/zh_cn/multi_modal/internvl.md
  lmdeploy/model.py
  lmdeploy/vl/engine.py
  lmdeploy/vl/model/llava_hf.py
  lmdeploy/vl/model/llava_next.py
  lmdeploy/vl/model/utils.py
  lmdeploy/vl/model/xcomposer2.py
  lmdeploy/vl/templates.py
Labels: Bug:P1

#2420 support min_p sampling parameter
  CMakeLists.txt
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/messages.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/kernels/CMakeLists.txt
  src/turbomind/kernels/sampling_kernels.cu
  src/turbomind/kernels/sampling_kernels.h
  src/turbomind/kernels/sampling_topk_kernels.cu
  src/turbomind/kernels/sampling_topk_kernels.h
  src/turbomind/kernels/sampling_topp_kernels.cu
  src/turbomind/kernels/sampling_topp_kernels.h
  src/turbomind/layers/CMakeLists.txt
  src/turbomind/layers/DynamicDecodeBaseLayer.h
  src/turbomind/layers/DynamicDecodeLayer.cc
  src/turbomind/layers/DynamicDecodeLayer.h
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.cc
  src/turbomind/layers/sampling_layers/BaseSamplingLayer.h
  src/turbomind/layers/sampling_layers/CMakeLists.txt
  src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc
  src/turbomind/layers/sampling_layers/LogitsProcessorLayer.h
  src/turbomind/layers/sampling_layers/SamplingLayer.cc
  src/turbomind/layers/sampling_layers/SamplingLayer.h
  src/turbomind/layers/sampling_layers/StopCriteriaLayer.cc
  src/turbomind/layers/sampling_layers/StopCriteriaLayer.h
  src/turbomind/layers/sampling_layers/TopKSamplingLayer.cc
  src/turbomind/layers/sampling_layers/TopKSamplingLayer.h
  src/turbomind/layers/sampling_layers/TopPSamplingLayer.cc
  src/turbomind/layers/sampling_layers/TopPSamplingLayer.h
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaV2.cc
  tests/csrc/unittests/CMakeLists.txt
  tests/csrc/unittests/test_sampling_kernels.cu
  tests/csrc/unittests/test_sampling_layer.cu
  tests/pytorch/engine/test_logits_process.py
Labels: enhancement

#2434 automatically set max_batch_size according to the device when it is not specified
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/utils.py
Labels: improvement

#2440 refactor pytorch engine(ascend)
  lmdeploy/pytorch/backends/ascend/apply_rotary_emb.py
  lmdeploy/pytorch/backends/ascend/attention.py
  lmdeploy/pytorch/backends/ascend/moe.py
  lmdeploy/pytorch/backends/ascend/norm.py
  lmdeploy/pytorch/backends/ascend/op_backend.py
  lmdeploy/pytorch/backends/base.py
  lmdeploy/pytorch/backends/cuda/graph_runner.py
  lmdeploy/pytorch/backends/default/multinomial_sampling.py
  lmdeploy/pytorch/backends/graph_runner.py
  lmdeploy/pytorch/kernels/ascend/__init__.py
  lmdeploy/pytorch/kernels/ascend/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/ascend/fill_kv_cache.py
  lmdeploy/pytorch/kernels/ascend/moe_gating_topk_softmax.py
  lmdeploy/pytorch/kernels/ascend/pagedattention.py
  lmdeploy/pytorch/kernels/ascend/rms_norm.py
Labels: enhancement

#2454 fix tensors on different devices when deploying MiniCPM-V-2_6 with tensor parallelism
  lmdeploy/vl/model/minicpmv.py
Labels: Bug:P1

#2460 fix MultinomialSampling operator builder
  lmdeploy/pytorch/backends/cuda/multinomial_sampling.py
  lmdeploy/pytorch/nn/multinomial_sampling.py
Labels: Bug:P2

#2461 Fix initialization of runtime_min_p
  src/turbomind/layers/sampling_layers/SamplingLayer.cc
  tests/csrc/unittests/test_sampling_kernels.cu
Labels: Bug:P1

#2473 Support user-sepcified data type
  lmdeploy/cli/cli.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/kernels/attention/attention.cu
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  tests/test_lmdeploy/test_turbomind/test_converter.py
Labels: enhancement

#2472 Fix "TypeError: Got unsupported ScalarType BFloat16"
  lmdeploy/serve/utils.py
Labels: Bug:P1

#2483 fix ascend atten_mask
  lmdeploy/pytorch/backends/ascend/op_backend.py
Labels: Bug:P1

#2469 Add silu mul kernel
  lmdeploy/pytorch/backends/cuda/activation.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/kernels/cuda/activation.py
  lmdeploy/pytorch/kernels/cuda/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/cuda/fused_moe.py
  lmdeploy/pytorch/kernels/cuda/rms_norm.py
  tests/pytorch/kernel/test_activation.py
Labels: improvement

#2477 Pytorch Engine reduce TTFT
  lmdeploy/pytorch/engine/engine.py
Labels: improvement

#2478 Add max_log_len option to control length of printed log
  autotest/README.md
  lmdeploy/api.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/logger.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/utils.py
Labels: improvement

#2465 Support minicpm3-4b
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/pytorch/configurations/minicpm3.py
  lmdeploy/pytorch/models/minicpm3.py
  lmdeploy/pytorch/models/module_map.py
Labels: enhancement

#2494 set served model name being repo_id from hub before it is downloaded
  lmdeploy/cli/entrypoint.py
Labels: improvement

#2488 Improve proxy server usage
  docs/en/llm/proxy_server.md
  docs/zh_cn/llm/proxy_server.md
  lmdeploy/cli/serve.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/proxy/proxy.py
Labels: improvement

#2485 CudaGraph mixin
  lmdeploy/pytorch/backends/cuda/graph_runner.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/dbrx.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/internlm.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/internvl.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/llava.py
  lmdeploy/pytorch/models/minicpm3.py
  lmdeploy/pytorch/models/mistral.py
  lmdeploy/pytorch/models/mixtral.py
  lmdeploy/pytorch/models/phi3.py
  lmdeploy/pytorch/models/phi3_moe.py
  lmdeploy/pytorch/models/qwen.py
  lmdeploy/pytorch/models/qwen2.py
  lmdeploy/pytorch/models/qwen2_moe.py
  lmdeploy/pytorch/models/qwen2_vl.py
  lmdeploy/pytorch/models/starcoder2.py
  lmdeploy/pytorch/models/utils/__init__.py
  lmdeploy/pytorch/models/utils/cudagraph.py
Labels: improvement

#2487 pytorch engine add get_logits
  lmdeploy/pytorch/backends/graph_runner.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/dbrx.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/internlm.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/internvl.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/llava.py
  lmdeploy/pytorch/models/mistral.py
  lmdeploy/pytorch/models/mixtral.py
  lmdeploy/pytorch/models/phi3.py
  lmdeploy/pytorch/models/phi3_moe.py
  lmdeploy/pytorch/models/qwen.py
  lmdeploy/pytorch/models/qwen2.py
  lmdeploy/pytorch/models/qwen2_moe.py
  lmdeploy/pytorch/models/starcoder2.py
Labels: improvement

#2466 Refactor lora
  docs/en/llm/api_server_lora.md
  docs/en/llm/pipeline.md
  docs/zh_cn/llm/api_server_lora.md
  docs/zh_cn/llm/pipeline.md
  lmdeploy/pytorch/adapter/adapter.py
  lmdeploy/pytorch/backends/base.py
  lmdeploy/pytorch/backends/cuda/lora.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/backends/cuda/slora.py
  lmdeploy/pytorch/backends/lora.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/__init__.py
  lmdeploy/pytorch/kernels/cuda/__init__.py
  lmdeploy/pytorch/kernels/cuda/fused_lora.py
  lmdeploy/pytorch/kernels/cuda/mbgmm.py
  lmdeploy/pytorch/kernels/cuda/mbgmv.py
  lmdeploy/pytorch/kernels/cuda/rearange_all_gather.py
  lmdeploy/pytorch/kernels/mbgmm.py
  lmdeploy/pytorch/kernels/mbgmv.py
  lmdeploy/pytorch/kernels/rearange_all_gather.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/patch.py
  lmdeploy/pytorch/models/utils/cudagraph.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/paging/block_manager/__init__.py
  lmdeploy/pytorch/paging/block_manager/base_block_manager.py
  lmdeploy/pytorch/paging/block_manager/default_block_manager.py
  lmdeploy/pytorch/paging/block_manager/window_block_manager.py
  lmdeploy/pytorch/paging/scheduler.py
  tests/pytorch/kernel/test_fused_lora.py
  tests/pytorch/kernel/test_mbgmm.py
  tests/pytorch/kernel/test_mbgmv.py
  tests/pytorch/kernel/test_rearange_all_gather.py
Labels: improvement

#2502 Catch exceptions thrown by turbomind inference thread
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#2506 support noaligned silu_and_mul
  lmdeploy/pytorch/backends/cuda/activation.py
  lmdeploy/pytorch/dist_utils.py
  lmdeploy/pytorch/kernels/cuda/activation.py
  lmdeploy/pytorch/kernels/cuda/fused_moe.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
  lmdeploy/pytorch/models/minicpm3.py
  tests/pytorch/kernel/test_activation.py
Labels: improvement

#2521 optimize performance of ascend backend's update_step_context() by calculating kv_start_indices in a new way
  lmdeploy/pytorch/backends/ascend/op_backend.py
Labels: improvement

#2520 Fix chatglm tokenizer failed when transformers>=4.45.0
  lmdeploy/tokenizer.py
  tests/test_lmdeploy/test_tokenizer.py
Labels: improvement

#2499 The `get_ppl` missed the last token of each iteration during multi-iter prefill
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/serve/utils.py
  lmdeploy/turbomind/deploy/config.py
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#2527 fix vl gradio
  lmdeploy/serve/gradio/vl.py
Labels: Bug:P1
