Repository InternLM/lmdeploy, pull requests merged in 2025-02, with the labels that each got.

#2961 Set max concurrent requests
  lmdeploy/cli/serve.py
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#3088 fix user guide about cogvlm deployment
  docs/en/multi_modal/cogvlm.md
  docs/zh_cn/multi_modal/cogvlm.md
Labels: Bug:P1

#3109 remove logitswarper
  lmdeploy/pytorch/engine/logits_process.py
Labels: improvement

#3086 fix postional argument
  autotest/utils/pipeline_chat.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/tokenizer.py
Labels: Bug:P1

#3110 Update benchmark script and user guide
  benchmark/profile_hf_generation.py
  benchmark/profile_triton_python_backend.py
  docs/en/benchmark/benchmark.md
  docs/en/benchmark/profile_api_server.md
  docs/en/benchmark/profile_generation.md
  docs/en/benchmark/profile_throughput.md
  docs/en/index.rst
  docs/zh_cn/benchmark/benchmark.md
  docs/zh_cn/benchmark/profile_api_server.md
  docs/zh_cn/benchmark/profile_generation.md
  docs/zh_cn/benchmark/profile_throughput.md
  docs/zh_cn/index.rst
Labels: improvement

#3125 Fix UT of deepseek chat template
  tests/test_lmdeploy/test_model.py
Labels: Bug:P2

#3122 Fix internvl2.5 error after eviction
  lmdeploy/vl/model/internvl.py
Labels: Bug:P1

#3069 support release pipeline
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/transformer_triton_backend.cpp
  src/turbomind/triton_backend/transformer_triton_backend.hpp
  src/turbomind/utils/cuda_utils.cc
  src/turbomind/utils/cuda_utils.h
  src/turbomind/utils/nccl_utils.cc
  src/turbomind/utils/nccl_utils.h
Labels: enhancement

#3137 Fix cogvlm and phi3vision
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/phi3_v.py
  lmdeploy/vl/model/cogvlm.py
  lmdeploy/vl/model/phi3_vision.py
Labels: Bug:P1

#3044 support eos_token list in turbomind
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/deploy/config.py
  lmdeploy/turbomind/deploy/source_model/base.py
  lmdeploy/turbomind/deploy/source_model/deepseek2.py
  lmdeploy/turbomind/deploy/source_model/glm4.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/source_model/molmo.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
  lmdeploy/turbomind/deploy/target_model/base.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/utils.py
  src/turbomind/engine/request.h
  src/turbomind/kernels/sampling_penalty_kernels.cu
  src/turbomind/kernels/sampling_penalty_kernels.h
  src/turbomind/layers/DynamicDecodeLayer.cc
  src/turbomind/layers/DynamicDecodeLayer.h
  src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  tests/csrc/unittests/test_sampling.cu
  tests/csrc/unittests/test_sampling_layer.cu
Labels: improvement

#3020 Use aiohttp inside proxy server && add --disable-cache-status argument
  lmdeploy/cli/serve.py
  lmdeploy/serve/proxy/proxy.py
Labels: improvement

#3136 [fix] fix vl gradio, use pipeline api and remove interactive chat
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/serve/gradio/vl.py
Labels: Bug:P1

#2918 [maca] support deepseekv2 for maca backend.
  lmdeploy/pytorch/backends/dlinfer/attention.py
  lmdeploy/pytorch/backends/dlinfer/rotary_embedding.py
  lmdeploy/pytorch/kernels/dlinfer/pagedattention.py
Labels: enhancement

#3153 fix typing
  lmdeploy/pytorch/engine/engine.py
Labels: Bug:P2

#3142 Update runtime package dependencies
  requirements/runtime_ascend.txt
  requirements/runtime_camb.txt
  requirements/runtime_cuda.txt
  requirements/runtime_maca.txt
  requirements/test.txt
Labels: improvement

#3150 fix min length penalty
  src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc
  src/turbomind/layers/sampling_layers/LogitsProcessorLayer.h
Labels: Bug:P1

#3166 fix default temperature value
  src/turbomind/models/llama/LlamaBatch.cc
Labels: Bug:P1

#3158 Use pad_token_id as image_token_id for vl models
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/internvl.py
  lmdeploy/pytorch/models/llava.py
  lmdeploy/pytorch/models/phi3_v.py
  lmdeploy/pytorch/models/qwen2_vl.py
  lmdeploy/vl/model/base.py
  lmdeploy/vl/model/cogvlm.py
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/model/glm_4v.py
  lmdeploy/vl/model/internvl.py
  lmdeploy/vl/model/llava.py
  lmdeploy/vl/model/llava_hf.py
  lmdeploy/vl/model/llava_next.py
  lmdeploy/vl/model/minicpmv.py
  lmdeploy/vl/model/phi3_vision.py
  lmdeploy/vl/model/qwen.py
  lmdeploy/vl/model/qwen2.py
  lmdeploy/vl/model/xcomposer2.py
  lmdeploy/vl/model/yi.py
Labels: Bug:P1

#3156 Fix tool call prompt for InternLM and Qwen
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: Bug:P1

#3176 fix temperature=0
  lmdeploy/pytorch/messages.py
Labels: Bug:P1

#3177 Make turbomind support embedding inputs on GPU
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#3149 [Feature] support deepseek-vl2 for pytorch engine
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/multi_modal/deepseek_vl2.md
  docs/en/multi_modal/index.rst
  docs/en/supported_models/supported_models.md
  docs/zh_cn/multi_modal/deepseek_vl2.md
  docs/zh_cn/multi_modal/index.rst
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/pytorch/configurations/cogvlm.py
  lmdeploy/pytorch/configurations/deepseek_vl2.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/deepseek_vl2.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/patch.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/vl/model/base.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/deepseek_vl2.py
  lmdeploy/vl/model/glm_4v.py
  lmdeploy/vl/model/internvl_llava.py
  lmdeploy/vl/model/llava.py
  lmdeploy/vl/model/xcomposer2.py
  lmdeploy/vl/model/yi.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#3188 fix deepseekv2 has no attribute use_mla error
  lmdeploy/pytorch/models/deepseek_v2.py
Labels: Bug:P1

#3189 fix unstoppable chat
  lmdeploy/turbomind/chat.py
Labels: Bug:P1

#3183 remove update badwords
  lmdeploy/pytorch/engine/engine.py
Labels: improvement
