Repository InternLM/lmdeploy, pull requests merged in 2025-08, with the labels that each got.

#3793 fix head_dim=None
  lmdeploy/pytorch/configurations/default.py
  lmdeploy/turbomind/deploy/source_model/llama.py
Labels: Bug:P1

#3795 Refactor FP8 MoE GEMM
  src/turbomind/kernels/gemm/gemm_universal_sm90_v3.h
  src/turbomind/kernels/gemm/gemm_universal_sm90_v5.h
  src/turbomind/kernels/gemm/kernel/sm90_q64n32.cu
  src/turbomind/kernels/gemm/kernel_impl_sm90.h
  src/turbomind/kernels/gemm/scaled_gmma_fp8_sm90.h
  src/turbomind/kernels/gemm/scheduler.cuh
  src/turbomind/kernels/gemm/test/test_gemm.cu
  src/turbomind/kernels/gemm/test/testbed_v2.h
  src/turbomind/kernels/gemm/tuner/params.h
  src/turbomind/models/llama/LlamaLinear.cu
Labels: improvement

#3813 remove 'lmdeploy convert' from CLI
  docs/en/inference/load_hf.md
  docs/zh_cn/inference/load_hf.md
  lmdeploy/cli/cli.py
  lmdeploy/serve/turbomind/__init__.py
Labels: Bug:P2

#3814 Optimize rmsnorm with head_dim=128
  lmdeploy/pytorch/kernels/cuda/rms_norm.py
  lmdeploy/pytorch/kernels/cuda/utils.py
Labels: improvement

#3798 support offloading weights & kv_cache for turbomind
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/core/allocator.h
  src/turbomind/core/module.cc
  src/turbomind/core/module.h
  src/turbomind/core/tensor.cc
  src/turbomind/core/tensor.h
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaDenseWeight.cc
  src/turbomind/models/llama/LlamaDenseWeight.h
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/LlamaWeight.h
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
Labels: enhancement

#3800 fix internvl disable_vision_encoder
  lmdeploy/pytorch/models/internvl3_hf.py
  lmdeploy/pytorch/models/utils/model.py
  lmdeploy/pytorch/weight_loader/model_weight_loader.py
Labels: Bug:P1

#3818 Simplify GEMM interface
  src/turbomind/kernels/gemm/CMakeLists.txt
  src/turbomind/kernels/gemm/arch.h
  src/turbomind/kernels/gemm/context.cu
  src/turbomind/kernels/gemm/cublas.cu
  src/turbomind/kernels/gemm/desc.h
  src/turbomind/kernels/gemm/dispatch_cache.cu
  src/turbomind/kernels/gemm/gemm.cu
  src/turbomind/kernels/gemm/kernel.cu
  src/turbomind/kernels/gemm/kernel.h
  src/turbomind/kernels/gemm/kernel_impl.h
  src/turbomind/kernels/gemm/kernel_impl_sm90.h
  src/turbomind/kernels/gemm/registry.cu
  src/turbomind/kernels/gemm/registry.h
  src/turbomind/kernels/gemm/test/test_gemm.cu
  src/turbomind/kernels/gemm/test/testbed_v2.h
  src/turbomind/kernels/gemm/tuner/params.h
  src/turbomind/kernels/gemm/types.h
  src/turbomind/models/llama/LlamaDenseWeight.cc
  src/turbomind/models/llama/LlamaDenseWeight.h
  src/turbomind/models/llama/LlamaFfnLayer.cc
  src/turbomind/models/llama/LlamaLinear.cu
  src/turbomind/models/llama/LlamaLinear.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/models/llama/moe_ffn_layer.cc
  src/turbomind/models/llama/unified_attention_layer.cc
Labels: improvement

#3737 add remote logs;optimize forward lock
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/executor/base.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/messages.py
Labels: improvement

#3828 Fix v1 comp protocol
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#3827 support deepgemm new api
  lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
  lmdeploy/pytorch/envs.py
  lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
  lmdeploy/pytorch/third_party/__init__.py
  lmdeploy/pytorch/third_party/deep_gemm/__init__.py
Labels: improvement

#3829 remove serving with gradio
  docs/en/index.rst
  docs/en/inference/load_hf.md
  docs/en/llm/api_server.md
  docs/en/llm/gradio.md
  docs/en/multi_modal/api_server_vl.md
  docs/en/quantization/w4a16.md
  docs/zh_cn/index.rst
  docs/zh_cn/inference/load_hf.md
  docs/zh_cn/llm/api_server.md
  docs/zh_cn/llm/gradio.md
  docs/zh_cn/multi_modal/api_server_vl.md
  docs/zh_cn/quantization/w4a16.md
  lmdeploy/cli/cli.py
  lmdeploy/cli/serve.py
  lmdeploy/serve/gradio/__init__.py
  lmdeploy/serve/gradio/api_server_backend.py
  lmdeploy/serve/gradio/app.py
  lmdeploy/serve/gradio/constants.py
  lmdeploy/serve/gradio/turbomind_coupled.py
  lmdeploy/serve/gradio/vl.py
  requirements/serve.txt
Labels: improvement

#3820 PytorchEngine support gpt-oss bf16
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/pytorch/backends/attention.py
  lmdeploy/pytorch/backends/cuda/attention.py
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/backends/dlinfer/attention.py
  lmdeploy/pytorch/backends/dlinfer/moe.py
  lmdeploy/pytorch/backends/moe.py
  lmdeploy/pytorch/configurations/gpt_oss.py
  lmdeploy/pytorch/kernels/cuda/blocked_fp8_fused_moe.py
  lmdeploy/pytorch/kernels/cuda/flashattention.py
  lmdeploy/pytorch/kernels/cuda/fused_moe.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
  lmdeploy/pytorch/models/gpt_oss.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/nn/attention.py
  lmdeploy/pytorch/nn/moe.py
  tests/pytorch/kernel/test_flash_attention.py
  tests/pytorch/kernel/test_fuse_moe_blocked_fp8.py
  tests/pytorch/kernel/test_fused_moe.py
  tests/pytorch/kernel/test_paged_attention.py
Labels: enhancement

#3779 build(docker): Try to optimize docker
  .github/workflows/docker.yml
  .github/workflows/test_docker.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  docker/Dockerfile
  docker/Dockerfile.ascend
  docker/Dockerfile_Hopper
  docker/Dockerfile_aarch64_ascend
  docker/build.sh
  docker/install.sh
  docker/prepare_wheel.sh
  src/turbomind/python/CMakeLists.txt
Labels: improvement

#3836 Make a common chat.py to replace each engine's
  lmdeploy/cli/chat.py
  lmdeploy/cli/cli.py
  lmdeploy/messages.py
  lmdeploy/pytorch/chat.py
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#3847 [dlinfer] fix get_backend err
  lmdeploy/pytorch/backends/dlinfer/__init__.py
  lmdeploy/pytorch/backends/selector.py
Labels: Bug:P1

#3861 fix partial rotary factor
  lmdeploy/pytorch/nn/rotary_embedding.py
Labels: Bug:P1

#3862 fix chatting with VLM model via CLI
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/vl_async_engine.py
Labels: Bug:P1

#3852 support logprobs
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/messages.py
Labels: improvement

#3846 Support GLM-4-0414 and GLM-4.1V
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/pytorch/models/glm4.py
  lmdeploy/pytorch/models/glm4_1v.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/glm4_1v.py
  lmdeploy/vl/model/glm4_v.py
Labels: enhancement

#3857 fix prebuild on cuda12.8
  builder/manywheel/Dockerfile_2014
  builder/manywheel/build_all_lmdeploy_builders.sh
  builder/manywheel/build_all_wheel.sh
  src/turbomind/kernels/gemm/tma.cu
Labels: Bug:P1

#3871 add missing docs
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
Labels: documentation

#3874 Fix uninitialized members in cuBLAS wrapper
  src/turbomind/kernels/gemm/cublas.cu
Labels: Bug:P0

#3873 fix flash-attn bc
  lmdeploy/pytorch/backends/cuda/attention.py
  lmdeploy/pytorch/third_party/flash_attn_interface.py
Labels: improvement

#3872 fix flashmla build for cuda12.4
  docker/prepare_wheel.sh
Labels: Bug:P1

#3877 [Fix] ray mp engine on ascend platform
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/engine/mp_engine/ray_engine.py
  lmdeploy/pytorch/ray.py
Labels: Bug:P1

#3868 fix bug: leaves empty
  lmdeploy/pytorch/paging/block_trie.py
Labels: Bug:P1

#3835 Improve turbomind's prefix cache
  lmdeploy/cli/chat.py
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/engine/request.h
  src/turbomind/models/llama/BlockTrie.cc
  src/turbomind/models/llama/BlockTrie.h
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/SequenceManager.cc
  src/turbomind/models/llama/SequenceManager.h
Labels: improvement

#3882 fix pytorch metrics in mp engine
  lmdeploy/pytorch/engine/mp_engine/base.py
  lmdeploy/pytorch/engine/mp_engine/base_worker.py
Labels: Bug:P1

#3883 Fix stream assert error when wakeup 30+ times
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P1

#3888 fix side effect brought by #3821
  lmdeploy/serve/async_engine.py
Labels: Bug:P1

#3886 support internvl3.5
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/turbomind/supported_models.py
Labels: enhancement

#3879 check_env in multiprocess
  lmdeploy/pytorch/engine/engine_checker.py
  lmdeploy/pytorch/engine/mp_engine/zmq_engine.py
  lmdeploy/pytorch/envs.py
Labels: Bug:P1

#3894 [ascend] add env to set rt visable by ray and disable warmup
  lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
  lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/envs.py
Labels: improvement

#3736 Update turbomind communication library
  src/turbomind/comm/CMakeLists.txt
  src/turbomind/comm/cuda_ipc/CMakeLists.txt
  src/turbomind/comm/cuda_ipc/allgather.cu
  src/turbomind/comm/cuda_ipc/allreduce.cu
  src/turbomind/comm/cuda_ipc/broadcast.cu
  src/turbomind/comm/cuda_ipc/common.h
  src/turbomind/comm/cuda_ipc/cuda_ipc_comm.cu
  src/turbomind/comm/cuda_ipc/cuda_ipc_comm.h
  src/turbomind/comm/cuda_ipc/device_semaphore.h
  src/turbomind/comm/cuda_ipc/fused_allreduce.cu
  src/turbomind/comm/cuda_ipc/fused_allreduce_ex.cu
  src/turbomind/comm/cuda_ipc/mscclpp.h
  src/turbomind/comm/cuda_ipc/multimem.cuh
  src/turbomind/comm/cuda_ipc/semaphore.cuh
  src/turbomind/comm/cuda_ipc/semaphore.h
  src/turbomind/comm/device_comm.h
  src/turbomind/comm/nccl/nccl.cu
  src/turbomind/comm/test_comm.cu
Labels: enhancement
