Repository InternLM/lmdeploy, pull requests merged in 2025-01, with the labels that each got.

#2979 add tool role in BaseChatTemplate as tool response in messages
  lmdeploy/model.py
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#2959 Support fp8 w8a8 for pt backend
  docs/en/quantization/w8a8.md
  docs/zh_cn/quantization/w8a8.md
  lmdeploy/cli/lite.py
  lmdeploy/cli/utils.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/pytorch/backends/cuda/qmodules.py
  lmdeploy/pytorch/backends/qmodules.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/kernels/cuda/w8a8_triton_kernels.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/internlm2_ve.py
  lmdeploy/pytorch/models/minicpmv26.py
  lmdeploy/pytorch/models/mistral.py
  lmdeploy/pytorch/models/phi3.py
  lmdeploy/pytorch/models/q_modules.py
  lmdeploy/pytorch/models/qwen.py
  lmdeploy/pytorch/models/qwen2.py
  lmdeploy/pytorch/models/qwen2_moe.py
  lmdeploy/pytorch/models/qwen2_vl.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/nn/norm.py
  tests/pytorch/kernel/test_fused_moe.py
Labels: improvement

#2975 Optimize lora kernel
  lmdeploy/pytorch/backends/cuda/lora.py
  lmdeploy/pytorch/kernels/cuda/fused_lora.py
Labels: improvement

#2907 Remove threadsafe
  benchmark/profile_generation.py
  docs/en/advance/pytorch_multithread.md
  docs/en/index.rst
  docs/zh_cn/advance/pytorch_multithread.md
  docs/zh_cn/index.rst
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_checker.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/paging/scheduler.py
  lmdeploy/serve/gradio/vl.py
  tests/pytorch/engine/test_request.py
Labels: improvement

#2989 Fix ascend dockerfile
  docker/Dockerfile_aarch64_ascend
  docs/en/get_started/ascend/get_started.md
  docs/zh_cn/get_started/ascend/get_started.md
Labels: Bug:P1

#2967 Support DeepseekV3 fp8
  lmdeploy/pytorch/backends/base.py
  lmdeploy/pytorch/backends/blockedf8_modules.py
  lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/backends/moe.py
  lmdeploy/pytorch/configurations/deepseek_v2.py
  lmdeploy/pytorch/kernels/cuda/blocked_fp8_fused_moe.py
  lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/nn/moe.py
  tests/pytorch/kernel/test_fuse_moe_blocked_fp8.py
  tests/pytorch/kernel/test_gemm_fp8.py
Labels: enhancement

#2968 Refactor async engine & turbomind IO
  autotest/interface/pipeline/test_pipeline_func.py
  autotest/utils/pipeline_chat.py
  benchmark/profile_pipeline_api.py
  benchmark/profile_throughput.py
  lmdeploy/messages.py
  lmdeploy/profiler.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/CMakeLists.txt
  src/turbomind/engine/CMakeLists.txt
  src/turbomind/engine/gateway.cc
  src/turbomind/engine/gateway.h
  src/turbomind/engine/model_request.cc
  src/turbomind/engine/model_request.h
  src/turbomind/engine/request.h
  src/turbomind/engine/request_queue.cc
  src/turbomind/engine/request_queue.h
  src/turbomind/engine/signal_buffer.h
  src/turbomind/kernels/gpt_kernels.cu
  src/turbomind/kernels/gpt_kernels.h
  src/turbomind/kernels/sampling_penalty_kernels.cu
  src/turbomind/kernels/sampling_penalty_kernels.h
  src/turbomind/kernels/sampling_topp_kernels.cu
  src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc
  src/turbomind/models/llama/CMakeLists.txt
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  src/turbomind/models/llama/Request.h
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/CMakeLists.txt
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.cc
  src/turbomind/triton_backend/llama/LlamaTritonModelInstance.h
  src/turbomind/triton_backend/transformer_triton_backend.hpp
  src/turbomind/utils/Tensor.h
  src/turbomind/utils/cuda_utils.h
Labels: improvement

#3001 fix xcomposer2 when transformers is upgraded greater than 4.46
  lmdeploy/vl/model/xcomposer2.py
Labels: Bug:P1

#2984 [dlinfer]rope refine
  lmdeploy/pytorch/kernels/dlinfer/apply_rotary_pos_emb.py
Labels: improvement

#2991 Expose spaces_between_special_tokens
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/gradio/vl.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#3008 Fix get_ppl & get_logits
  benchmark/profile_pipeline_api.py
  docs/en/llm/pipeline.md
  docs/en/multi_modal/vl_pipeline.md
  docs/zh_cn/llm/pipeline.md
  docs/zh_cn/multi_modal/vl_pipeline.md
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/utils.py
  lmdeploy/turbomind/decode.py
  lmdeploy/turbomind/turbomind.py
Labels: Bug:P1

#2977 [dlinfer]change llm op interface of paged_prefill_attention.
  lmdeploy/pytorch/backends/dlinfer/attention.py
  lmdeploy/pytorch/kernels/dlinfer/pagedattention.py
Labels: improvement

#3002 support new backend cambricon
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/backends/dlinfer/__init__.py
  lmdeploy/pytorch/backends/dlinfer/camb/__init__.py
  lmdeploy/pytorch/backends/dlinfer/camb/op_backend.py
  lmdeploy/pytorch/backends/selector.py
  lmdeploy/pytorch/check_env/deeplink.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/utils.py
  requirements/runtime_camb.txt
  requirements_camb.txt
Labels: enhancement

#3018 Fix typo in w4a16 guide
  docs/zh_cn/quantization/w4a16.md
Labels: Bug:P2

#3009 fix blocked fp8 moe kernel
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/kernels/cuda/blocked_fp8_fused_moe.py
Labels: Bug:P1

#3007 support-moe-fp8
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/backends/moe.py
  lmdeploy/pytorch/kernels/cuda/w8a8_fused_moe.py
  lmdeploy/pytorch/nn/moe.py
Labels: enhancement

#2981 Update request logger
  benchmark/profile_pipeline_api.py
  lmdeploy/logger.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/protocol.py
  src/turbomind/models/llama/LlamaBatch.cc
Labels: improvement

#3016 remove decoding
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/messages.py
Labels: improvement

#3029 Fix async engine
  lmdeploy/serve/async_engine.py
Labels: Bug:P0

#3026 support internlm3 on pt
  lmdeploy/model.py
  lmdeploy/pytorch/configurations/default.py
  lmdeploy/pytorch/models/internlm3.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/supported_models.py
Labels: enhancement

#3027 Support internlm3 quantization
  lmdeploy/cli/lite.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/gptq.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/lite/modeling/internlm3_gptq.py
  lmdeploy/lite/quantization/activation/observer.py
  lmdeploy/lite/quantization/awq.py
Labels: enhancement

#3030 Fix MoE gating for DeepSeek V2
  src/turbomind/kernels/gemm/moe_utils_v2.cu
  src/turbomind/kernels/gemm/moe_utils_v2.h
  src/turbomind/kernels/gemm/test/test_moe_utils.cu
  src/turbomind/models/llama/moe_ffn_layer.cc
Labels: Bug:P1

#3033 Fix potential hang during TP model initialization
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: Bug:P1

#2886 use weights iterator while loading
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/internvl.py
  lmdeploy/pytorch/models/llava.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/nn/moe.py
  lmdeploy/pytorch/weight_loader/model_weight_loader.py
Labels: improvement

#3074 fix error in interactive api
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#3068 fix sliding window mgr
  lmdeploy/pytorch/paging/block_manager/window_block_manager.py
Labels: Bug:P1

#3077 More arguments in api_client, update docstrings
  lmdeploy/serve/openai/api_client.py
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#3072 Add deepseek-r1 chat template
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#3061 Update tokenizer
  benchmark/profile_generation.py
  benchmark/profile_throughput.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/serve/async_engine.py
  lmdeploy/tokenizer.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/deploy/source_model/__init__.py
  lmdeploy/turbomind/deploy/source_model/meta_llama.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#3031 Add system role to deepseek chat template
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: Bug:P2
