Repository InternLM/lmdeploy, pull requests merged in 2025-04, with the labels that each got.

#3367 enable qwenvl2.5 graph mode on ascend
  lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
Labels: improvement

#3372 fix dp cudagraph
  lmdeploy/pytorch/backends/cuda/graph_runner.py
  lmdeploy/pytorch/backends/graph_runner.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/utils/cudagraph.py
Labels: Bug:P1

#3267 support ascend w8a8 graph_mode
  lmdeploy/cli/lite.py
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/pytorch/check_env/__init__.py
  lmdeploy/pytorch/check_env/deeplink.py
  lmdeploy/pytorch/kernels/cuda/__init__.py
  lmdeploy/pytorch/kernels/cuda/w8a8_triton_kernels.py
  lmdeploy/pytorch/kernels/default/__init__.py
  lmdeploy/pytorch/kernels/default/w8a8_kernels.py
  lmdeploy/pytorch/kernels/dispatcher.py
  lmdeploy/pytorch/kernels/dlinfer/__init__.py
  lmdeploy/pytorch/models/q_modules.py
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/utils.py
Labels: enhancement

#3375 fix flashmla eagermode
  lmdeploy/pytorch/backends/cuda/op_backend.py
Labels: Bug:P1

#3370 support all2all ep
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/backends/cuda/token_dispatcher.py
  lmdeploy/pytorch/backends/default/token_dispatcher.py
  lmdeploy/pytorch/backends/token_dispatcher.py
Labels: enhancement

#3382 disable sync batch on dp eager mode
  lmdeploy/pytorch/backends/cuda/graph_runner.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#3358 [Fix] fix `image_token_id` error of qwen2-vl and deepseek
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/model/qwen2.py
Labels: Bug:P1

#3380 fix for deepgemm update
  benchmark/profile_generation.py
  benchmark/profile_throughput.py
  lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
  lmdeploy/pytorch/check_env/transformers.py
  lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
Labels: improvement

#3386 Add string before hash tokens in blocktrie
  lmdeploy/pytorch/paging/block_trie.py
Labels: improvement

#3383 optimize ep in decoding stage
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/backends/cuda/token_dispatcher.py
  lmdeploy/pytorch/kernels/cuda/ep_moe.py
Labels: enhancement

#3356 optimize moe get sorted idx
  lmdeploy/pytorch/kernels/cuda/flashattention.py
  lmdeploy/pytorch/kernels/cuda/fused_moe.py
  tests/pytorch/kernel/test_fused_moe.py
Labels: improvement

#3213 use half/bf16 lm_head output
  src/turbomind/engine/model_request.cc
  src/turbomind/kernels/ban_bad_words.cu
  src/turbomind/kernels/gpt_kernels.cu
  src/turbomind/kernels/reduce_kernel_utils.cuh
  src/turbomind/kernels/sampling_kernels.cu
  src/turbomind/kernels/sampling_kernels.h
  src/turbomind/kernels/sampling_penalty_kernels.cu
  src/turbomind/kernels/sampling_penalty_kernels.h
  src/turbomind/kernels/sampling_topk_kernels.cu
  src/turbomind/kernels/sampling_topp_kernels.cu
  src/turbomind/layers/DynamicDecodeLayer.cc
  src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc
  src/turbomind/layers/sampling_layers/SamplingLayer.cc
  src/turbomind/layers/sampling_layers/StopCriteriaLayer.cc
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/LlamaV2.h
  tests/csrc/unittests/gtest_utils.h
  tests/csrc/unittests/test_penalty_kernels.cu
  tests/csrc/unittests/test_sampling_kernels.cu
  tests/csrc/unittests/test_sampling_layer.cu
Labels: improvement

#3384 fix stopping criteria
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P1

#3385 support List[dict] prompt input without do_preprocess
  .github/workflows/unit-test.yml
  generate.sh
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/vl_async_engine.py
Labels: Bug:P1

#3387 Warmup deepgemm
  lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/backends/cuda/warmup_manager.py
Labels: enhancement

#3408 support Llama4
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/pytorch/configurations/llama4.py
  lmdeploy/pytorch/models/llama4.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/nn/moe.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/llama4.py
Labels: enhancement

#3417 fix tensor dispatch in dynamo
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/model_inputs.py
Labels: Bug:P1

#3420 update ascend doc
  docs/en/get_started/ascend/get_started.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/get_started/ascend/get_started.md
  docs/zh_cn/supported_models/supported_models.md
Labels: documentation

#3429 find port
  lmdeploy/pytorch/engine/executor/dist_utils.py
Labels: improvement

#3436 Add ascend env variables to dockerfile
  docker/Dockerfile_aarch64_ascend
Labels: Bug:P1

#3381 add twomicrobatch support
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/backends/cuda/token_dispatcher.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/nn/attention.py
  lmdeploy/pytorch/nn/moe.py
Labels: enhancement

#3442 fix linting error by upgrade to ubuntu-latest
  .github/workflows/lint.yml
Labels: Bug:P1

#3435 fix awq tp for pytorch engine
  lmdeploy/pytorch/nn/linear.py
Labels: bug

#3446 update qwen2.5-vl-32b docs
  docs/en/multi_modal/qwen2_5_vl.md
  docs/zh_cn/multi_modal/qwen2_5_vl.md
Labels: documentation

#3443 ray async forward execute
  lmdeploy/pytorch/distributed.py
  lmdeploy/pytorch/engine/executor/base.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
Labels: improvement

#3450 map internvl3 chat template to builtin chat template internvl2_5
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#3458 fix mllm testcase fail
  lmdeploy/pytorch/models/internvl.py
Labels: Bug:P1

#3462 remove barely used code to improve maintenance
  README.md
  README_ja.md
  README_zh-CN.md
  autotest/config.yaml
  autotest/utils/get_run_config.py
  benchmark/benchmark_pytorch_engine_a100.sh
  benchmark/benchmark_turbomind_engine_a100.sh
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  examples/CMakeLists.txt
  examples/__init__.py
  examples/cpp/CMakeLists.txt
  examples/cpp/llama/CMakeLists.txt
  examples/cpp/llama/README.md
  examples/cpp/llama/llama_config.yaml
  examples/cpp/llama/llama_triton_example.cc
  examples/cpp/llama/start_ids.csv
  examples/cpp/llama/tokenizer.py
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/pytorch/configurations/dbrx.py
  lmdeploy/pytorch/configurations/falcon.py
  lmdeploy/pytorch/models/dbrx.py
  lmdeploy/pytorch/models/falcon.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/mini_gemeni.py
  tests/csrc/unittests/test_sampling.cu
  tests/test_lmdeploy/test_auto_backend.py
  tests/test_lmdeploy/test_model.py
  tests/test_lmdeploy/test_tokenizer.py
  tests/test_lmdeploy/test_turbomind/test_converter.py
Labels: improvement

#3452 remove paged attention autotune
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
Labels: Bug:P1

#3460 Remove empty prompts in benchmark scripts
  benchmark/profile_pipeline_api.py
  benchmark/profile_restful_api.py
  benchmark/profile_throughput.py
Labels: Bug:P1

#3467 Support phi4 mini
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/model.py
  lmdeploy/pytorch/kernels/cuda/apply_rotary_pos_emb.py
  lmdeploy/pytorch/models/phi3.py
  lmdeploy/pytorch/nn/rotary_embedding.py
Labels: enhancement

#3475 fix qwen2.5-vl chat template
  lmdeploy/model.py
  tests/test_lmdeploy/test_model.py
Labels: Bug:P2

#3474 Align forward arguments of deepgemm blockedf8
  lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
Labels: Bug:P1

#3479 fix turbomind lib missing to link nccl by exporting nccl path
  builder/manywheel/entrypoint_build.sh
Labels: Bug:P0

#3477 fix dsvl2 no attr config error
  lmdeploy/pytorch/models/deepseek_vl2.py
Labels: Bug:P1

#3481 Fix disorder of ray execution
  lmdeploy/pytorch/engine/executor/ray_executor.py
Labels: Bug:P1

#3482 update dockerfile
  docker/Dockerfile
  docker/Dockerfile_Hopper
Labels: Bug:P1

#3491 Fix Qwen2MoE shared expert gate
  src/turbomind/models/llama/moe_ffn_layer.cc
  src/turbomind/models/llama/moe_ffn_layer.h
Labels: Bug:P1

#3493 move partial_json_parser from ’serve.txt‘ to ‘runtime.txt‘
  requirements/runtime_ascend.txt
  requirements/runtime_camb.txt
  requirements/runtime_cuda.txt
  requirements/runtime_maca.txt
  requirements/serve.txt
Labels: improvement

#3499 fix replicate kv for qwen3-moe
  lmdeploy/pytorch/models/qwen3_moe.py
Labels: Bug:P1

#3503 support qwen3-dense models awq quantization
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/quantization/awq.py
Labels: improvement

#3500 Optimize MoE gate for Qwen3
  src/turbomind/kernels/gemm/moe_utils_v2.cu
Labels: improvement

#3505 support qwen3 fp8
  lmdeploy/pytorch/models/qwen3.py
  lmdeploy/pytorch/models/qwen3_moe.py
  lmdeploy/pytorch/nn/linear.py
Labels: enhancement

#3486 [Dlinfer][Ascend] Optimize performance of 310P device
  lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
  lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
  lmdeploy/pytorch/backends/dlinfer/linear.py
Labels: improvement

#3510 optimize longcontext decoding
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
Labels: improvement

#3506 Support min_p in openai completions_v1
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement
