Repository InternLM/lmdeploy, pull requests merged in 2025-07, with the labels that each got.

#3695 Defer build cache engine
  lmdeploy/pytorch/engine/executor/base.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#3706 add reward model documents
  docs/en/index.rst
  docs/en/supported_models/reward_models.md
  docs/zh_cn/index.rst
  docs/zh_cn/supported_models/reward_models.md
Labels: documentation

#3638 remove python3.8 support and add python3.13 support
  .github/workflows/cuda11.8-whl-release.yml
  .github/workflows/linux-x64-gpu.yml
  .github/workflows/pypi.yml
  .github/workflows/windows-x64-gpu.yml
  README.md
  README_ja.md
  README_zh-CN.md
  builder/manywheel/Dockerfile_2014
  builder/manywheel/build_all_wheel.sh
  docs/en/get_started/installation.md
  docs/zh_cn/get_started/installation.md
  setup.py
Labels: improvement

#3534 [Feature] metrics support
  .github/scripts/check_lmdeploy.py
  docs/en/advance/metrics.md
  docs/en/index.rst
  docs/zh_cn/advance/metrics.md
  docs/zh_cn/index.rst
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/metrics/__init__.py
  lmdeploy/metrics/loggers.py
  lmdeploy/metrics/metrics_processor.py
  lmdeploy/metrics/stats.py
  lmdeploy/monitoring/docker-compose.yaml
  lmdeploy/monitoring/grafana/dashboards/config/dashboard.yaml
  lmdeploy/monitoring/grafana/dashboards/json/lmdeploy-dashboard.json
  lmdeploy/monitoring/grafana/datasources/datasource.yaml
  lmdeploy/monitoring/prometheus.yaml
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/paging/scheduler.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
Labels: enhancement

#3727 Fix the logic of calculating max_new_tokens and determining finish_reason
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/turbomind.py
Labels: improvement

#3726 feat(build): Integrate and build turbomind backend directly in setup.py
  .github/workflows/cuda11.8-whl-release.yml
  .github/workflows/linux-x64-gpu.yml
  .github/workflows/pr_ete_test.yml
  .github/workflows/pypi.yml
  .github/workflows/unit-test.yml
  .github/workflows/windows-x64-gpu.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  builder/manywheel/entrypoint_build.sh
  builder/windows/README.md
  cmake/yaml-cpp_cmake_policy.patch
  docs/en/get_started/installation.md
  docs/zh_cn/get_started/installation.md
  generate.sh
  lmdeploy/turbomind/generate_gemm_config.py
  pyproject.toml
  requirements/build.txt
  setup.py
Labels: improvement

#3733 [Fix]: Avoid quantize qk norm for qwen3 dense models
  lmdeploy/pytorch/models/qwen3.py
  lmdeploy/pytorch/nn/norm.py
Labels: Bug:P1

#3746 [Fix]: kernel meta retrieval for SM7X does not work
  lmdeploy/pytorch/kernels/cuda/flashattention.py
Labels: Bug:P1

#3740 Generate the benchmark output filename with given arguments
  benchmark/benchmark_serving.py
  benchmark/lmdeploy.yml
  benchmark/profile_restful_api.py
Labels: improvement

#3756 fix internvl norm
  lmdeploy/pytorch/models/internvl.py
  lmdeploy/pytorch/models/internvl3_hf.py
Labels: Bug:P1

#3757 support qwen3 moe yarn and vlm hf_overrides
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/models/qwen3_moe.py
  tests/pytorch/config/test_hf_overrides.py
Labels: Bug:P1

#3762 [PD Disaggregation] fix double unshelf
  lmdeploy/serve/proxy/proxy.py
Labels: Bug:P1

#3765 Internvl pt
  lmdeploy/archs.py
  lmdeploy/model.py
  lmdeploy/pytorch/check_env/model.py
  lmdeploy/pytorch/configurations/internvl3_hf.py
  lmdeploy/pytorch/models/internvl3_hf.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/reasoning_parser/qwen_qwq_reasoning_parser.py
  lmdeploy/serve/openai/tool_parser/internlm2_parser.py
  lmdeploy/vl/model/internvl3_hf.py
  tests/test_lmdeploy/test_model.py
Labels: enhancement

#3769 Improve internvl for turbomind engine
  lmdeploy/turbomind/deploy/source_model/deepseek_vl.py
  lmdeploy/turbomind/deploy/source_model/glm4.py
  lmdeploy/turbomind/deploy/source_model/internlm2.py
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/source_model/llava.py
  lmdeploy/turbomind/deploy/source_model/minicpmv.py
  lmdeploy/turbomind/deploy/source_model/molmo.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
  lmdeploy/turbomind/supported_models.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/vl/model/internvl3_hf.py
  src/turbomind/models/llama/LlamaV2.cc
Labels: enhancement

#3776 fix vl nothink mode
  lmdeploy/serve/vl_async_engine.py
  lmdeploy/vl/engine.py
  lmdeploy/vl/model/base.py
  lmdeploy/vl/model/cogvlm.py
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/model/deepseek_vl2.py
  lmdeploy/vl/model/gemma3_vl.py
  lmdeploy/vl/model/glm_4v.py
  lmdeploy/vl/model/internvl.py
  lmdeploy/vl/model/internvl3_hf.py
  lmdeploy/vl/model/llama4.py
  lmdeploy/vl/model/llava_hf.py
  lmdeploy/vl/model/minicpmv.py
  lmdeploy/vl/model/mllama.py
  lmdeploy/vl/model/molmo.py
  lmdeploy/vl/model/qwen.py
  lmdeploy/vl/model/qwen2.py
  lmdeploy/vl/model/xcomposer2.py
Labels: Bug:P1

#3784 fix: turbomind backend config in cli serve
  lmdeploy/cli/serve.py
Labels: improvement

#3759 remove deprecated codes
  lmdeploy/archs.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/turbomind/triton_python_backend/README.md
  lmdeploy/serve/turbomind/triton_python_backend/client.py
  lmdeploy/serve/turbomind/triton_python_backend/config.pbtxt
  lmdeploy/serve/turbomind/triton_python_backend/model.py
  lmdeploy/turbomind/chat.py
  lmdeploy/turbomind/deploy/converter.py
  lmdeploy/turbomind/turbomind.py
  lmdeploy/turbomind/utils.py
  requirements/serve.txt
  tests/test_lmdeploy/test_async_engine.py
  tests/test_lmdeploy/test_auto_backend.py
Labels: improvement

#3796 update proxy docs
  docs/en/llm/proxy_server.md
  docs/zh_cn/llm/proxy_server.md
Labels: documentation
