Repository InternLM/lmdeploy, pull requests merged in 2025-06, with the labels that each got.

#3600 read distributed envs
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/envs.py
  lmdeploy/pytorch/models/deepseek_v2.py
Labels: Bug:P1

#3604 sampling on the tokenizer's vocab
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#3606 update deepgemm version
  lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
  lmdeploy/pytorch/backends/cuda/warmup_manager.py
  lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
Labels: improvement

#3582 support eplb for Qwen3-MoE
  lmdeploy/pytorch/models/qwen3_moe.py
Labels: enhancement

#3608 fix side-effect caused by PR 3590
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/serve/async_engine.py
  lmdeploy/turbomind/deploy/loader.py
Labels: Bug:P0

#3614 fix bug in qwen2
  lmdeploy/pytorch/models/qwen2.py
Labels: Bug:P2

#3610 [PDDisaggreagtion] Async migration
  lmdeploy/pytorch/disagg/backend/dlslime.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/executor/base_worker.py
  lmdeploy/pytorch/engine/executor/uni_executor.py
Labels: improvement

#3598 move dp loop to model agent
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/model_inputs.py
Labels: improvement

#3618 fix awq kernel
  lmdeploy/pytorch/kernels/cuda/awq_kernels.py
Labels: Bug:P1

#3617 fix flash mla interface
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/configurations/utils.py
  lmdeploy/pytorch/kernels/cuda/flash_mla.py
  lmdeploy/pytorch/models/utils/cudagraph.py
Labels: Bug:P1

#3622 add benchmark scripts about pipeline api and inference engines according to the config file
  benchmark/benchmark_pipeline.py
  benchmark/benchmark_serving.py
  benchmark/benchmark_throughput.py
  benchmark/lmdeploy.yml
  benchmark/profile_pipeline_api.py
  benchmark/profile_restful_api.py
  benchmark/profile_throughput.py
  lmdeploy/profiler.py
Labels: improvement

#3631 runtime weight quant fp8
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/lite/quantization/weight/quant_utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/check_env/cuda.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine_checker.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/models/patch.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/nn/moe.py
  lmdeploy/pytorch/nn/quant_utils.py
Labels: enhancement

#3640 fix for default quant
  lmdeploy/pytorch/nn/moe.py
Labels: Bug:P1

#3647 Fix 'Namespace' object has no attribute 'num_tokens_per_iter' when serving by gradio
  lmdeploy/cli/serve.py
Labels: Bug:P1

#3643 set ray envs
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/envs.py
Labels: improvement

#3681 fix pt engine stop & cancel
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/pytorch/messages.py
  lmdeploy/serve/async_engine.py
Labels: Bug:P1
