Repository InternLM/lmdeploy, pull requests merged in 2025-05, with the labels that each got.

#3508 fix sampling if data overflow after temperature penalty
  src/turbomind/engine/model_request.cc
  src/turbomind/kernels/ban_bad_words.cu
  src/turbomind/kernels/reduce_kernel_utils.cuh
  src/turbomind/kernels/sampling_kernels.cu
  src/turbomind/kernels/sampling_penalty_kernels.cu
  src/turbomind/kernels/sampling_topk_kernels.cu
  src/turbomind/kernels/sampling_topp_kernels.cu
  src/turbomind/layers/DynamicDecodeLayer.cc
  src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc
  src/turbomind/layers/sampling_layers/SamplingLayer.cc
  src/turbomind/layers/sampling_layers/StopCriteriaLayer.cc
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaV2.cc
  src/turbomind/models/llama/llama_kernels.cu
  src/turbomind/models/llama/llama_kernels.h
Labels: Bug:P1

#3513 [ascend] fix recompile on different rank
  lmdeploy/pytorch/engine/model_agent.py
Labels: Bug:P1

#3487 reduce ray memory usage
  lmdeploy/pytorch/engine/executor/ray_executor.py
Labels: improvement

#3489 use dlblas
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/backends/cuda/token_dispatcher.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/nn/moe.py
Labels: improvement

#3519 fix attention sm86
  lmdeploy/pytorch/kernels/cuda/flashattention.py
Labels: Bug:P1

#3527 internlm3 dense fp8
  lmdeploy/pytorch/models/internlm3.py
Labels: improvement

#3304 LMDeploy Distserve
  benchmark/profile_generation.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/disagg/README.md
  lmdeploy/pytorch/disagg/__init__.py
  lmdeploy/pytorch/disagg/backend/__init__.py
  lmdeploy/pytorch/disagg/backend/backend.py
  lmdeploy/pytorch/disagg/backend/base.py
  lmdeploy/pytorch/disagg/backend/dlslime.py
  lmdeploy/pytorch/disagg/backend/infinistore.py
  lmdeploy/pytorch/disagg/backend/mooncake.py
  lmdeploy/pytorch/disagg/config.py
  lmdeploy/pytorch/disagg/conn.py
  lmdeploy/pytorch/disagg/messages.py
  lmdeploy/pytorch/disagg/request.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_instance.py
  lmdeploy/pytorch/engine/executor/base.py
  lmdeploy/pytorch/engine/executor/base_worker.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/engine/executor/uni_executor.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/paging/scheduler.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/proxy/constants.py
  lmdeploy/serve/proxy/proxy.py
Labels: enhancement

#3448 ray nsys profile support
  lmdeploy/pytorch/engine/executor/__init__.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/envs.py
Labels: improvement

#3533 allow api server terminated through requests from clients
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/proxy/proxy.py
Labels: enhancement

#3532 update blockedfp8 scale name
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/internlm3.py
  lmdeploy/pytorch/models/qwen3.py
  lmdeploy/pytorch/models/qwen3_moe.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/nn/moe.py
Labels: improvement

#3523 start engine loop on server startup event
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#3540 update two microbatch
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/nn/moe.py
Labels: improvement

#3494 fix stopwords kv cache
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/messages.py
Labels: Bug:P1

#3535 support update params for pytorch backend from api server
  lmdeploy/messages.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/executor/__init__.py
  lmdeploy/pytorch/engine/executor/base.py
  lmdeploy/pytorch/engine/executor/base_worker.py
  lmdeploy/pytorch/engine/executor/mp_executor.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/engine/executor/uni_executor.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/serve/proxy/proxy.py
  lmdeploy/utils.py
Labels: enhancement

#3531 [ascend]set transdata dynamic shape true
  lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
Labels: improvement

#3547 [bug fix] fix PD Disaggregation in DSV3
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/paging/scheduler.py
Labels: Bug:P1

#3545 ray safe exit
  lmdeploy/pytorch/engine/executor/ray_executor.py
Labels: improvement

#3543 fix proxy server heart beat
  lmdeploy/serve/proxy/proxy.py
Labels: Bug:P1

#3555 fix dp>1 tp=1 ep=1
  lmdeploy/pytorch/engine/engine.py
Labels: Bug:P1

#3552 Skip dp dummy input forward
  lmdeploy/pytorch/distributed.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#3550 Unclock mutual exclusivity of argument: `tool-call-parser` and `reasoning-parser`
  lmdeploy/cli/serve.py
  lmdeploy/serve/openai/api_server.py
Labels: improvement

#3570 perform torch.cuda.empty_cache() after conversion
  lmdeploy/turbomind/deploy/source_model/llama.py
Labels: improvement

#3414 Launch multiple api servers for dp > 1
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/launch_server.py
  lmdeploy/serve/proxy/proxy_config.yml
Labels: improvement

#3559 support awq for Qwen2.5-VL
  lmdeploy/lite/apis/auto_awq.py
  lmdeploy/lite/apis/calibrate.py
  lmdeploy/lite/apis/smooth_quant.py
  lmdeploy/lite/quantization/awq.py
  lmdeploy/vl/model/qwen2.py
Labels: improvement

#3572 Eplb
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/nn/moe.py
Labels: improvement

#3580 fix mixtral on new transformers
  lmdeploy/pytorch/configurations/default.py
Labels: Bug:P2

#3578 Update benchmark
  .github/workflows/lint.yml
  benchmark/benchmark_serving.py
  benchmark/lmdeploy.yml
  benchmark/profile_restful_api.py
Labels: improvement

#3589 [Fix]: reset step after eviction
  .github/workflows/lint.yml
  lmdeploy/pytorch/paging/eviction_helper/recompute_eviction_helper.py
Labels: bug

#3592 Fix batch infer for gemma3vl
  .github/workflows/pr_ete_test.yml
  lmdeploy/vl/model/gemma3_vl.py
Labels: Bug:P1
