Repository InternLM/lmdeploy, pull requests merged in 2025-09, with the labels that each got.

#3845 [refactor][chat_template][1/N] adopt tokenizer's apply_chat_template
  lmdeploy/cli/chat.py
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  tests/test_lmdeploy/test_model.py
Labels: improvement

#3939 build(docker): fix ascend tag name
  .github/workflows/docker.yml
Labels: Bug:P1

#3937 Dispatch MXFP4 weight conversion for sm70 & sm75
  src/turbomind/kernels/attention/mainloop_sm70.h
  src/turbomind/kernels/core/array_ops.h
  src/turbomind/kernels/gemm/CMakeLists.txt
  src/turbomind/kernels/gemm/convert_v2.cu
  src/turbomind/kernels/gemm/kernel/sm70_s884_dynamic.cu
  src/turbomind/kernels/gemm/registry.cu
  src/turbomind/kernels/gemm/test/reference.cu
  src/turbomind/kernels/gemm/test/test_gemm_v2.cc
  src/turbomind/models/llama/LlamaDenseWeight.cc
Labels: enhancement

#3941 put eot_token to stop_words
  lmdeploy/model.py
Labels: Bug:P1

#3912 Fix tm rl usage in xtuner
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/core/tensor.cc
  src/turbomind/core/tensor.h
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/LlamaBatch.h
  src/turbomind/models/llama/LlamaWeight.cc
  src/turbomind/python/bind.cpp
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  src/turbomind/triton_backend/llama/LlamaTritonModel.h
Labels: Bug:P1

#3976 cherry pick PR-3708 to return token_id
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: improvement

#3863 Support GLM-4.5
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/pytorch/models/glm4_moe.py
  lmdeploy/pytorch/models/module_map.py
Labels: enhancement

#3974 Use blocking sync when TP engine is idling
  src/turbomind/comm/CMakeLists.txt
  src/turbomind/comm/barrier.h
  src/turbomind/comm/host_comm.h
  src/turbomind/comm/test_comm.cu
  src/turbomind/comm/test_host_comm.cc
  src/turbomind/comm/thread_comm.cc
  src/turbomind/models/llama/LlamaBatch.cc
Labels: improvement

#3962 support gpt-oss function/reasoning in /v1/chat/completions
  lmdeploy/model.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/harmony_utils.py
  lmdeploy/tokenizer.py
Labels: enhancement

#3984 support returning stop_str in output
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: enhancement

#3990 Disable prefix caching when serving a VLM model
  lmdeploy/api.py
  lmdeploy/serve/vl_async_engine.py
  requirements/runtime_ascend.txt
  requirements/runtime_camb.txt
  requirements/runtime_cuda.txt
  requirements/runtime_maca.txt
  requirements/runtime_rocm.txt
Labels: Bug:P1

#3994 remove NCCL_LAUNCH_MODE
  docker/Dockerfile
  docker/prepare_wheel.sh
  k8s/deployment.yaml
Labels: Bug:P1
