Repository InternLM/lmdeploy, pull requests merged in 2025-03, with the labels that each got.

#3194 [Feature] support qwen2.5-vl for pytorch engine
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/multi_modal/index.rst
  docs/en/multi_modal/qwen2_5_vl.md
  docs/en/supported_models/supported_models.md
  docs/zh_cn/multi_modal/index.rst
  docs/zh_cn/multi_modal/qwen2_5_vl.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/qwen2_5_vl.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/vl/model/qwen2.py
Labels: enhancement

#3147 PytorchEngine multi-node support v2
  benchmark/profile_throughput.py
  docs/en/advance/pytorch_multinodes.md
  docs/en/index.rst
  docs/zh_cn/advance/pytorch_multinodes.md
  docs/zh_cn/advance/pytorch_multithread.md
  docs/zh_cn/index.rst
  lmdeploy/messages.py
  lmdeploy/pytorch/backends/base.py
  lmdeploy/pytorch/backends/cuda/awq_modules.py
  lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
  lmdeploy/pytorch/backends/cuda/graph_runner.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/backends/cuda/qmodules.py
  lmdeploy/pytorch/backends/default/awq_modules.py
  lmdeploy/pytorch/backends/default/linear.py
  lmdeploy/pytorch/backends/graph_runner.py
  lmdeploy/pytorch/backends/selector.py
  lmdeploy/pytorch/chat.py
  lmdeploy/pytorch/check_env/dist.py
  lmdeploy/pytorch/distributed.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_checker.py
  lmdeploy/pytorch/engine/executor/__init__.py
  lmdeploy/pytorch/engine/executor/base.py
  lmdeploy/pytorch/engine/executor/base_worker.py
  lmdeploy/pytorch/engine/executor/dist_utils.py
  lmdeploy/pytorch/engine/executor/mp_executor.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/engine/executor/uni_executor.py
  lmdeploy/pytorch/engine/logits_process.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/engine/request.py
  lmdeploy/pytorch/messages.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/qwen2_moe.py
  lmdeploy/pytorch/multimodal/data_type.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/nn/moe.py
  lmdeploy/pytorch/paging/scheduler.py
  lmdeploy/pytorch/tools/__init__.py
  lmdeploy/pytorch/tools/utils.py
  lmdeploy/pytorch/utils.py
  lmdeploy/pytorch/weight_loader/model_weight_loader.py
  requirements/runtime_cuda.txt
Labels: enhancement

#3210 defaullt executor ray
  lmdeploy/pytorch/engine/executor/__init__.py
Labels: improvement

#3216 Specifiy lmdeploy version in benchmark guide
  docs/en/benchmark/benchmark.md
  docs/zh_cn/benchmark/benchmark.md
Labels: documentation

#3215 [ascend] fix multi-card distributed inference failures
  lmdeploy/pytorch/backends/default/op_backend.py
  lmdeploy/pytorch/backends/dlinfer/ascend/op_backend.py
  lmdeploy/pytorch/backends/selector.py
  lmdeploy/pytorch/distributed.py
  lmdeploy/pytorch/engine/executor/base_worker.py
  lmdeploy/pytorch/engine/executor/mp_executor.py
Labels: Bug:P1

#3221 fix for small cache-max-entry-count
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/kernels/cuda/blocked_fp8_fused_moe.py
Labels: Bug:P1

#3218 Add flash mla
  lmdeploy/pytorch/backends/attention.py
  lmdeploy/pytorch/backends/cuda/attention.py
  lmdeploy/pytorch/backends/cuda/op_backend.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/configurations/deepseek_v2.py
  lmdeploy/pytorch/configurations/utils.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/executor/base.py
  lmdeploy/pytorch/kernels/cuda/__init__.py
  lmdeploy/pytorch/kernels/cuda/flash_mla.py
  lmdeploy/pytorch/kernels/flash_mla.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/utils/cudagraph.py
  lmdeploy/pytorch/nn/attention.py
Labels: enhancement

#3239 [ascend] add Ascend docker image
  docs/en/get_started/ascend/get_started.md
  docs/zh_cn/get_started/ascend/get_started.md
Labels: documentation

#3251 change ascend&camb default_batch_size to 256
  lmdeploy/utils.py
Labels: improvement

#3198 Tool reasoning parsers and streaming function call
  docs/en/index.rst
  docs/en/llm/api_server_reasoning.md
  docs/en/llm/api_server_tools.md
  docs/zh_cn/index.rst
  docs/zh_cn/llm/api_server_reasoning.md
  docs/zh_cn/llm/api_server_tools.md
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/model.py
  lmdeploy/serve/async_engine.py
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/serve/openai/reasoning_parser/__init__.py
  lmdeploy/serve/openai/reasoning_parser/deepseek_r1_reasoning_parser.py
  lmdeploy/serve/openai/reasoning_parser/qwen_qwq_reasoning_parser.py
  lmdeploy/serve/openai/reasoning_parser/reasoning_parser.py
  lmdeploy/serve/openai/tool_parser/__init__.py
  lmdeploy/serve/openai/tool_parser/internlm2_parser.py
  lmdeploy/serve/openai/tool_parser/llama3_parser.py
  lmdeploy/serve/openai/tool_parser/qwen2d5_parser.py
  lmdeploy/serve/openai/tool_parser/tool_parser.py
  lmdeploy/serve/openai/tool_parser/utils.py
  lmdeploy/tokenizer.py
  requirements/runtime_cuda.txt
  requirements/serve.txt
  tests/test_lmdeploy/test_model.py
Labels: BC-breaking, improvement

#3242 remove torchelastic flag
  lmdeploy/pytorch/engine/executor/dist_utils.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
Labels: improvement

#3247 fix qwen2.5 pytorch engine dtype error on NPU
  lmdeploy/pytorch/models/qwen2_5_vl.py
Labels: Bug:P1

#3257 [Fix] failed to update the tokenizer's eos_token_id into stop_word list
  lmdeploy/messages.py
  lmdeploy/serve/async_engine.py
  tests/test_lmdeploy/test_messages.py
Labels: Bug:P1

#3263 fix dsv3 gate scaling
  lmdeploy/pytorch/models/deepseek_v2.py
Labels: Bug:P1

#3196 Fix the bug for reading dict error
  lmdeploy/pytorch/models/mllama.py
  lmdeploy/pytorch/models/qwen2_5_vl.py
  lmdeploy/pytorch/models/qwen2_vl.py
Labels: Bug:P1

#3271 disable flashmla warning on sm<90
  lmdeploy/pytorch/configurations/utils.py
Labels: improvement

#3268 Fix get ppl
  lmdeploy/serve/utils.py
Labels: Bug:P1

#3272 Add gemma3 implementation
  README.md
  README_ja.md
  README_zh-CN.md
  docs/en/multi_modal/gemma3.md
  docs/en/multi_modal/index.rst
  docs/en/supported_models/supported_models.md
  docs/zh_cn/multi_modal/gemma3.md
  docs/zh_cn/multi_modal/index.rst
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/archs.py
  lmdeploy/pytorch/configurations/gemma.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/gemma3_vl.py
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/siglip.py
  lmdeploy/pytorch/supported_models.py
  lmdeploy/vl/model/builder.py
  lmdeploy/vl/model/gemma3_vl.py
Labels: enhancement

#3282 fix activation grid oversize
  lmdeploy/pytorch/kernels/cuda/activation.py
  lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
  lmdeploy/pytorch/kernels/cuda/utils.py
  tests/pytorch/kernel/test_activation.py
  tests/pytorch/kernel/test_gemm_fp8.py
Labels: Bug:P1

#3283 Add spaces_between_special_tokens to /v1/interactive and make compatible with empty text
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
  lmdeploy/vl/model/cogvlm.py
  lmdeploy/vl/model/deepseek.py
  lmdeploy/vl/model/deepseek_vl2.py
  lmdeploy/vl/model/internvl.py
  lmdeploy/vl/model/minicpmv.py
  lmdeploy/vl/model/molmo.py
  lmdeploy/vl/model/qwen.py
Labels: improvement

#3291 add env var to control timeout
  benchmark/profile_restful_api.py
Labels: improvement

#3295 Set ensure_ascii=False for tool calling
  lmdeploy/serve/openai/tool_parser/internlm2_parser.py
  lmdeploy/serve/openai/tool_parser/llama3_parser.py
  lmdeploy/serve/openai/tool_parser/qwen2d5_parser.py
Labels: Bug:P2

#3164 refactor attn param
  lmdeploy/turbomind/deploy/config.py
  lmdeploy/turbomind/deploy/source_model/deepseek2.py
  lmdeploy/turbomind/deploy/source_model/deepseek_vl.py
  lmdeploy/turbomind/deploy/source_model/glm4.py
  lmdeploy/turbomind/deploy/source_model/internvl.py
  lmdeploy/turbomind/deploy/source_model/llama.py
  lmdeploy/turbomind/deploy/source_model/llava.py
  lmdeploy/turbomind/deploy/source_model/molmo.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
  lmdeploy/turbomind/turbomind.py
  src/turbomind/kernels/attention/attention_params.h
  src/turbomind/kernels/attention/attention_universal.h
  src/turbomind/kernels/attention/kv_cache_utils_v2.cu
  src/turbomind/kernels/attention/kv_cache_utils_v2.h
  src/turbomind/kernels/attention/rotary_embedding.h
  src/turbomind/kernels/attention/test_attention.cu
  src/turbomind/models/llama/LlamaBatch.cc
  src/turbomind/models/llama/llama_params.h
  src/turbomind/models/llama/llama_rope.h
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/models/llama/unified_attention_layer.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
  tests/test_lmdeploy/test_turbomind/test_converter.py
Labels: improvement

#3207 Torch dp support
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/backends/blockedf8_modules.py
  lmdeploy/pytorch/backends/cuda/attention.py
  lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
  lmdeploy/pytorch/backends/default/linear.py
  lmdeploy/pytorch/backends/dlinfer/linear.py
  lmdeploy/pytorch/backends/linear.py
  lmdeploy/pytorch/check_env/dist.py
  lmdeploy/pytorch/config.py
  lmdeploy/pytorch/distributed.py
  lmdeploy/pytorch/engine/cache_engine.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/executor/__init__.py
  lmdeploy/pytorch/engine/executor/base.py
  lmdeploy/pytorch/engine/executor/base_worker.py
  lmdeploy/pytorch/engine/executor/dist_utils.py
  lmdeploy/pytorch/engine/executor/mp_executor.py
  lmdeploy/pytorch/engine/executor/ray_executor.py
  lmdeploy/pytorch/engine/executor/uni_executor.py
  lmdeploy/pytorch/engine/model_agent.py
  lmdeploy/pytorch/kernels/cuda/apply_rotary_pos_emb.py
  lmdeploy/pytorch/kernels/cuda/fill_kv_cache.py
  lmdeploy/pytorch/kernels/cuda/multinomial_sampling.py
  lmdeploy/pytorch/kernels/cuda/pagedattention.py
  lmdeploy/pytorch/model_inputs.py
  lmdeploy/pytorch/models/baichuan.py
  lmdeploy/pytorch/models/chatglm2.py
  lmdeploy/pytorch/models/cogvlm.py
  lmdeploy/pytorch/models/deepseek.py
  lmdeploy/pytorch/models/deepseek_v2.py
  lmdeploy/pytorch/models/gemma.py
  lmdeploy/pytorch/models/internlm.py
  lmdeploy/pytorch/models/internlm2.py
  lmdeploy/pytorch/models/internlm3.py
  lmdeploy/pytorch/models/internvl.py
  lmdeploy/pytorch/models/llama.py
  lmdeploy/pytorch/models/minicpm3.py
  lmdeploy/pytorch/models/mistral.py
  lmdeploy/pytorch/models/phi3.py
  lmdeploy/pytorch/models/qwen.py
  lmdeploy/pytorch/models/qwen2.py
  lmdeploy/pytorch/models/qwen2_moe.py
  lmdeploy/pytorch/nn/attention.py
  lmdeploy/pytorch/nn/linear.py
  lmdeploy/pytorch/nn/moe.py
  lmdeploy/pytorch/nn/norm.py
  lmdeploy/pytorch/tools/make_inputs.py
  lmdeploy/pytorch/tools/utils.py
Labels: enhancement

#3287 Add deep gemm with tma pre allocated
  lmdeploy/pytorch/backends/cuda/blockedf8_modules.py
  lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
Labels: enhancement

#3302 fix sliding window multi chat
  lmdeploy/pytorch/paging/block_manager/window_block_manager.py
Labels: Bug:P2

#3305 Add Qwen3 and Qwen3MoE
  lmdeploy/turbomind/deploy/config.py
  lmdeploy/turbomind/deploy/module.py
  lmdeploy/turbomind/deploy/source_model/qwen.py
  lmdeploy/turbomind/supported_models.py
  src/turbomind/kernels/norm/rms_norm.cu
  src/turbomind/kernels/norm/rms_norm.h
  src/turbomind/models/llama/LlamaDecoderLayerWeight.cc
  src/turbomind/models/llama/LlamaDenseWeight.h
  src/turbomind/models/llama/llama_params.h
  src/turbomind/models/llama/unified_attention_layer.cc
  src/turbomind/models/llama/unified_attention_layer.h
  src/turbomind/triton_backend/llama/LlamaTritonModel.cc
Labels: enhancement

#3315 [Feature] support qwen3 and qwen3-moe for pytorch engine
  lmdeploy/pytorch/models/module_map.py
  lmdeploy/pytorch/models/qwen3.py
  lmdeploy/pytorch/models/qwen3_moe.py
Labels: enhancement

#3307 add `v` check
  lmdeploy/pytorch/kernels/cuda/flashattention.py
Labels: Bug:P1

#3336 Fix Qwen3MoE config parsing
  lmdeploy/turbomind/deploy/source_model/qwen.py
Labels: Bug:P1

#3334 optimize mla, remove load v
  lmdeploy/pytorch/kernels/cuda/fill_kv_cache.py
  lmdeploy/pytorch/kernels/cuda/flashattention.py
  lmdeploy/pytorch/kernels/cuda/flatten_kv_cache.py
Labels: improvement

#3338 Fix finish reasons
  lmdeploy/serve/openai/api_server.py
  lmdeploy/serve/openai/protocol.py
Labels: Bug:P1

#3206 [ascend]support deepseekv2
  docs/en/supported_models/supported_models.md
  docs/zh_cn/supported_models/supported_models.md
  lmdeploy/pytorch/backends/dlinfer/apply_rotary_emb.py
  lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
  lmdeploy/pytorch/configurations/utils.py
  lmdeploy/pytorch/kernels/dlinfer/flash_attention.py
  lmdeploy/pytorch/kernels/dlinfer/pagedattention.py
Labels: enhancement

#3327 remove think_end_token_id in streaming content
  lmdeploy/serve/openai/reasoning_parser/deepseek_r1_reasoning_parser.py
Labels: Bug:P1

#3311 support dp decoding with cudagraph
  lmdeploy/messages.py
  lmdeploy/pytorch/backends/cuda/graph_runner.py
  lmdeploy/pytorch/backends/graph_runner.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/model_agent.py
Labels: improvement

#3345 optimize quant-fp8 kernel
  lmdeploy/pytorch/kernels/cuda/blocked_gemm_fp8.py
Labels: improvement

#3350 Fix the finish_reason
  lmdeploy/serve/openai/api_server.py
Labels: Bug:P1

#3326 refactor dlinfer rope
  lmdeploy/pytorch/backends/dlinfer/ascend/graph_runner.py
  lmdeploy/pytorch/kernels/dlinfer/apply_rotary_pos_emb.py
Labels: improvement

#3313 add deepep
  lmdeploy/cli/serve.py
  lmdeploy/cli/utils.py
  lmdeploy/messages.py
  lmdeploy/pytorch/backends/cuda/moe.py
  lmdeploy/pytorch/backends/cuda/token_dispatcher.py
  lmdeploy/pytorch/backends/moe.py
  lmdeploy/pytorch/check_env/dist.py
  lmdeploy/pytorch/distributed.py
  lmdeploy/pytorch/engine/engine.py
  lmdeploy/pytorch/engine/engine_checker.py
  lmdeploy/pytorch/kernels/cuda/ep_moe.py
  lmdeploy/pytorch/nn/moe.py
Labels: enhancement

#3376 set cmake policy minimum version as 3.5
  .github/workflows/unit-test.yml
  generate.sh
Labels: Bug:P1
